### ISSUE TITLE
Cookies and headers not sent on various browsers when using the Flash simpleUpload method

### ISSUE THREAD

**Issue by kwikwag** [moxiecode/plupload#100]
Flash component doesn't send cookies nor headers on various browsers when it decides to use the simpleUpload path. Most chances are that this is specific to a version of Flash plug-in -- see the configuration details specified below.

At first I thought it happened because Rails set an HttpOnly option on my cookie, but after rigorous testing I found that neither headers nor cookie are sent regardless of the HttpOnly setting.

When specifying { urlstream_upload: true } in the uploader settings (thus forcing the advancedUpload path), all configurations work properly.
## Configuration details:

My configuration is Windows XP / plupload 1.2.4 / Rails 3.0.0 / Flash 10.1 r82, with the following browsers:
- Firefox 4.0b5
- Firefox 3.6.9
- Chrome 6.0.472.53
- Chrome 6.0.472.55
- Safari 5.0.1

Note: Internet Explorer 8.0.6001.18702 with a different version of Flash - 10.1.53.64 manages to send the cookie both in the simpleUpload and advancedUpload paths.

**Comment by aik099** [comment]
Was the `urlstream_upload` option removed in future Plupload versions? I don't see it on http://www.plupload.com/docs/Options page. Is there any way to pass through cookies, when Flash runtime is used?
