### ISSUE TITLE
Flash uplader throws error when removing file while active upload

### ISSUE THREAD

**Issue by dfuse** [moxiecode/plupload#101]
Flash uplader throws error when removing file while active upload.

Seems like the flash uploader fails on the next iteration when the file is actually removed, but flash is still polling changes.

file is undefined
if (file.status != plupload.FAILED) {
plupload.flash.js (строка 198)
file is undefined
if (file.status != plupload.FAILED) {
plupload.flash.js (строка 178)

**Comment by jayarjo** [comment]
Shouldn't be a problem in Plupload 2.x and up.
