### ISSUE TITLE
Resize and crop upscale?

### ISSUE THREAD

**Issue by precisionpete** [moxiecode/plupload#1017]
I'm very happy to have found plupload. This will save me tons of time. I've already spent a couple of days trying to roll my own.

I am anxiously looking forward to your adding bicubic scaling. That will improve the quality substantially.

While you are in there... Do you think you could add the option to resize and crop on upscale? It seems only to crop when the image size is reduced. 

I would like it to generate uniform thumbnails that are always the same aspect ratio. e.g. always a square. From what I have seen, it only resizes down... And crop only works when resizing?

i.e. If I ask it to resize and crop to 200x200, and I upload an image 100x150, it seems to leave it at the original size. I would like an option to upscale and crop to 200x200 in all cases. If not possible, the next best thing would be to at least maintain the crop aspect ratio - i.e. 100x100.

Thanks for a great tool!
Peter

**Comment by mix3d** [comment]
Plus one more for upscale; My scenario is downscaling+crop to 256x256, but if the uploaded image has a dimension smaller, it does not get scaled up to that square size. This is a considerable gap, and for now we will have to just check the onFileAdded for the dimensions and cancel the upload if the file is too small. Not an ideal UX at all.

**Comment by jayarjo** [comment]
I'm refactoring image resizing now. Cannot promise that will implement this one, but I will bear it in my mind.

**Comment by mix3d** [comment]
I found a different platform, FileAPI, that DOES resize upwards. I will be using this in the meantime. Cheers! http://mailru.github.io/FileAPI/

**Comment by jayarjo** [comment]
This has been implemented in 2.3.1 (although now we get requests to remove upscale).
