### ISSUE TITLE
Error message when user select file(s) with invalid extension or with size larger than max_size

### ISSUE THREAD

**Issue by PeterDaveHello** [moxiecode/plupload#1021]
Hi,

I found the error message is

```
File extension error. 
```

when user select a file with invalid extension,

and is 

```
File size error.
```

when user select a file which is too large

if is possible to change to error message, just tell the user the file extension is invalid, the size is large than max_size, not just a general meaning error?

Regards,
Thanks!

**Comment by bryanroth** [comment]
> You can intercept the error, and replace the message with whatever you like.

How is this possible?
