### ISSUE TITLE
Core API example is broken with default NuGet version

### ISSUE THREAD

**Issue by JackDuVal** [moxiecode/plupload#1023]
The Core API example puts the PostInit option in "init"

"Incase anyone else is having a problem with PostInit, the above examples may have worked in the past but do not anymore.  It appears that PostInit must be in the preinit section and will not work in init.  This doesn't seem to be documented anywhere.  (I am using Plupload2)" --matt 2013-06-21
http://www.plupload.com/punbb/viewtopic.php?id=604

In Visual Studio 2013, I installed PLUpload from NuGet, the default version being 1.5.7.1 I had to move PostInit from init to preinit to get the example to work

**Comment by jayarjo** [comment]
NuGet package has been updated to Plupload 2.2.1.
