### ISSUE TITLE
Calling Asp.net __doPostBack inside UploadComplete

### ISSUE THREAD

**Issue by rkalasky** [moxiecode/plupload#1029]
Hello, I'm using asp.net webforms and am attempting to call a 3rd party javascript function (__doPostBack) inside the plupload UploadComplete callback function.

In Chrome, this works fine. In other browsers, I get javascript errors. For example, in IE 11:

Accessing the 'caller' property of a function or arguments is not allowed in strict mode.

I see that Moxie.js has a 'use strict' declaration and if I comment that out, I do not get errors. Is there a workaround for this other than changing the library code?
I am using plupload v2.1.1 and moxie v1.2.0

**Comment by rkalasky** [comment]
In case anyone stumbles on this, I found a workaround. Calling the __doPostBack inside of a setTimeout seems to fix the issue. Something about delaying the execution prevents the error.

**Comment by bryanroth** [comment]
@rkalasky Thank you for remembering to come back to this issue and provide your solution.
