### ISSUE TITLE
don't stripped more files :(

### ISSUE THREAD

**Issue by kuaza61** [moxiecode/plupload#1057]
Maximum number of files: 50 But I choose pictures 100 units, boilers should remain: (

http://sv133.piclect.com/382412d546e8c1b1624400978dde4a3c/0c01e37a9/o/14/04/21/upload-hatasi.png

**Comment by jayarjo** [comment]
It strips extra files after you make a selection and close dialog. There's no way to constrain it in browse files dialog itself.
