### ISSUE TITLE
Node.js server side example needed (equivalent of upload.php)

### ISSUE THREAD

**Issue by homerjam** [moxiecode/plupload#1060]
It'd be great to have a working example of how to handle the uploads in node, I've found this [example](http://pastebin.com/Y0zufAfE) but it seems a little too simplified and doesn't look to support chunking etc.

Thanks

**Comment by jayarjo** [comment]
I guess we won't be providing this. Pull requests are welcome however.

**Comment by qwizztest** [comment]
If anyone else finds this thread from google, this link will help: [https://github.com/jupiter/express-plupload](https://github.com/jupiter/express-plupload)
