### ISSUE TITLE
Plupload 2.1.2 or 2.1.1 does not work with IE 8

### ISSUE THREAD

**Issue by kmatthew** [moxiecode/plupload#1072]
Hi, I am getting an error ('HTTP Error') when trying to attach a document using the latest plupload 2.1.1 in IE 8. However, IE10/Firefox/Chrome everything works fine and i am able to upload.

I am getting a number of ieframe.dll errors:
sec7111 https security is compromised by res://ieframe.dll/forbidframing.htm

<a id="abc-button" class="abc_btn_primary_10">Browse</a> 

Thanks.

**Comment by jayarjo** [comment]
Related: https://github.com/moxiecode/plupload/issues/1391.
