### ISSUE TITLE
Adding dynamic mutlipart_params not working

### ISSUE THREAD

**Issue by barbmc** [moxiecode/plupload#1082]
I am using the ui-widget and trying to add a dynamic param like so

$("#uploader").plupload({
        // General settings
        runtimes : 'html5,flash,silverlight,html4',
        url : 'includes/import.php',
        multipart_params: {
            user: user,
            uid: uid,
            client: client,
            approve: approve,
            overwrite: $('#overwrite').val()
        },

but no matter what the value of $('#overwrite').val() is it posts an empty string

Passing the same type of value to max_file_upload doesn't work either

**Comment by jayarjo** [comment]
This means that by the moment of upload `$('#overwrite').val()` is an empty string (single you retrieve it dynamically).
