### ISSUE TITLE
reduce plupload*js file size

### ISSUE THREAD

**Issue by cometta** [moxiecode/plupload#1083]
in version v1.5.6 plupload.full.js file size is 56KB. in v2.12  , plupload.full.min size is 109KB.  that is double the size. Can help to reduce the size as that will hinder visitors from required to download huge javascript file before can start using plupload.

**Comment by jayarjo** [comment]
@cometta sorry missed this report :) What you mean by - can help. I do not see how it can be reduced with all that stuff in it...?

**Comment by cometta** [comment]
I meant probably can consider to take out some features and put in and addon plugin. There is wide gap and different in js size between older version and newer version

**Comment by jayarjo** [comment]
It is possible to compile it without image manipulation support, then you will get less size by ~40kb and much smaller shims (Flash/Silverlight). Or you can compile it without additional runtimes altogether and gain even more. Then if you gzip it, should be around 20kb or less.

I don't think size matters this much these days anyway. But if you have practical suggestions I will consider them :)
