### ISSUE TITLE
GPL License Clarification

### ISSUE THREAD

**Issue by alberthdev** [moxiecode/plupload#1086]
I looked at your library, and I have to say that it's pretty darn good! However, there's a slight issue - licensing it under the GPL. GPL is not a bad license, especially for the open source community, but it does pose some problems for web developers. The GPL, using its own terms, requires any software even remotely using a GPL licensed software to disclose their source code.

For most software, this works perfectly. However, applying the GPL on web applications has a big impact - it means that *everything* must be disclosed. Indeed, HTML and JS are out there and in plain sight (and it would be rather hard to hide HTML/JS/CSS!), but this also has implications for the backend code - it would also have to be disclosed as well.

As a software developer, it's almost trivial to add and apply the GPL license to your code. (In fact, nearly all of my projects are GPL!) However, I too would've probably made the mistake of licensing a web-related code under the GPL!

As a web developer, it may not be possible to use a GPL licensed Javascript because disclosing the backend may pose security problems, not to mention that no one usually does this!

The solution, according to the [GPL FAQ](http://www.gnu.org/licenses/gpl-faq.html), is to add an exception:

> As a special exception to the GPL, any HTML file which merely makes function calls to this code, and for that purpose includes it by reference shall be deemed a separate work for copyright law purposes. In addition, the copyright holders of this code give you permission to combine this code with free software libraries that are released under the GNU LGPL. You may copy and distribute such a system following the terms of the GNU GPL for this code and the LGPL for the libraries. If you modify this code, you may extend this exception to your version of the code, but you are not obligated to do so. If you do not wish to do so, delete this exception statement from your version. 

As always, you can modify this exemption, or even not accept it at all - it's your choice. You can also add some clauses for commercial licensing - after all, everyone wants to be rewarded for their hard work!

Personally, I am planning on using your library for a community website. It's invite only to prevent abuse, and donation supported to keep the servers running.

Finally, there's some issues with licensing clarification. You mix LGPL and GPL in your README for plupload - totally different licenses! moxiecode/moxie has this issue too. It looks to me that it's LGPL (the README mentions LGPL), but the license.txt file indicates GPL. This could pose some major problems down the line, so it would be a good idea to fix this.

**Comment by lulalala** [comment]
I am also confused about whether this is LGPL or GPL. Can someone please clarify?

**Comment by jayarjo** [comment]
I think you guys overcomplicate things. Plupload and other similarly licensed products are free for personal use or for use in an open source project. Any other use case falls under [commercial license](http://www.plupload.com/license/oem), which you can check here: http://www.plupload.com/license/oem.

**Comment by jayarjo** [comment]
@Afraithe @spocke can you put a more detailed explanation for the issue in this ticket? And maybe in the referenced ones as well?

**Comment by Afraithe** [comment]
The contributing section had some errors in it that i fixed.

The license has always been, and will continue to be, GPLv2

**Comment by lulalala** [comment]
Thanks for clarification.

> Plupload and other similarly licensed products are free for personal use or for use in an open source project

Though it's free to use, it requires my MIT licensed project (frontend + backend) to be switched to GPL2, which I can't do, but thanks anyways :D
