### ISSUE TITLE
Bug in plupluad when trying to upload 0 kb file

### ISSUE THREAD

**Issue by orassayag** [moxiecode/plupload#1087]
Hi
2 people reported to me that when they dragged a folder into the plupload dragging area, there was javascript error and the upload coludn't start. My guess is that there was a hidden file of 0kb in folder with 500-1000 images.
When browsing a 0kb file - no response from plupload, and the file is not in queue.
Any chance to fix it?
![image](https://cloud.githubusercontent.com/assets/5759067/3315428/2c1057c2-f6fa-11e3-90e5-2ca5d41277b7.png)

**Comment by jayarjo** [comment]
We've added new filter [prevent_empty](https://github.com/moxiecode/plupload/wiki/Options#filtersprevent_empty), that is on by default, but can be turned off if needed.
