### ISSUE TITLE
Problem clearing queue on uploadcomplete

### ISSUE THREAD

**Issue by barbmc** [moxiecode/plupload#1089]
I'm using the latest version of the ui widget

I have added the following code to the uploadcomplete event to clear the queue

plupload.each(files, function(file) {
                    up.removeFile(file);
                });

Then I uploaded 4 images and only 2 were removed. Firebug showed the error e is undefined in plupload.min.js

You can see this at http://webrecipemanager.com/wrm-new

log in with user demo p/w demo99

then go to the manage recipes menu at the top and select Add Recipe->Enter Manually

then go down the page to the images plupload and try uploading several images

**Comment by jayarjo** [comment]
This happens because `files` array is altered as you cycle over it. Use [uploader.splice()](https://github.com/moxiecode/plupload/wiki/Uploader#splice-method-startlength) instead.
