### ISSUE TITLE
allow user selectable decimal places for percentage uploaded

### ISSUE THREAD

**Issue by kshelton77** [moxiecode/plupload#1091]
It would be a nice new feature if you could make Plupload so you could define the number of decimal places to use for the percentage uploaded. I'm using the Jquery UI version to upload some very large (several hundred megabytes) files to a server and with no decimal places in the reported percent uploaded it can take a long time for it to change from one percentage point to the next, leading me to wonder sometimes if anything is actually happening. If I could have Plupload display fractions of a percent uploaded the display for percent uploaded would be updated much more frequently and it would be much more obvious that the upload is actually occuring and has not stopped for some reason.

**Comment by jayarjo** [comment]
Don't think we will be adding such an option. But you could easily calculate percentage yourself, by doing some obvious arithmetic on loaded and total bytes.
