### ISSUE TITLE
Feature Request: event BeforeQueueUpload

### ISSUE THREAD

**Issue by viewpnt** [moxiecode/plupload#1094]
We have the event UploadComplete that Fires when all files in a queue are uploaded.
It would be helpful to have an event fired before all files in the queue start uploading, something like: BeforeQueueUpload, or BeforeQueueStart.

**Comment by jayarjo** [comment]
There's a StateChanged event, that fires each time Plupload is started or stopped. Then it is possible to check the actual state of the uploader, for example:

```
plupload.STARTED === up.state 
```

or

```
plupload.STOPPED === up.state
```

StateChanged amd up.state of plupload.STARTED can be considered as QueueStart. Other than that we probably won't be adding any other events.
