### ISSUE TITLE
support for protocol relative url

### ISSUE THREAD

**Issue by nurey** [moxiecode/plupload#1097]
Seems if I set url to a protocol relative url like "//otherdomain.name/upload_handler" from a site on domain.name, the xhr request is made to domain.name and not otherdomain.name

**Comment by wdmtech** [comment]
This is happening for me in the latest version, plupload is rewriting the `url:` option to the request's origin or something it seems - when it should be making a cross-origin request to a third-party API instead.

Possibly related: 

#919
#910
