### ISSUE TITLE
"Browse" button not working in IE after page reload

### ISSUE THREAD

**Issue by psenjirayar** [moxiecode/plupload#1102]
Emergency..
I am able to do the Upload and Drag and Drop at first time. When I refresh the browser, it is not working as it worked before. 
I am facing a problem similar to http://stackoverflow.com/questions/15792905/plupload-file-upload-not-working-in-ie10. But for me, Its working until I refresh the browser.
I have tried uploader.refresh(); No luck.:(

Thanks in advance.

**Comment by jayarjo** [comment]
v1,x is deprecated,you should not be using it anymore.
