### ISSUE TITLE
PlUpload 2 Thumbs Error #760 came back?

### ISSUE THREAD

**Issue by shanigee** [moxiecode/plupload#1110]
Recently I have been trying out the new version too and keep getting "WRONG_FORMAT: WRONG_FORMAT: ImageError 1" on Firefox and Chrome when I am upload

i tried to upload on the your live website example it crash the page.
![mfdc0006](https://cloud.githubusercontent.com/assets/8398755/3863531/461eb9c4-1f4a-11e4-82f9-19841b259509.JPG)

please look at it and if you could find a fix for rest of us?

**Comment by marekrynarzewski** [comment]
Why error WRONG_FORMAT: WRONG_FORMAT: ImageError 1 is shown in the console, instead of being passed to event Error.
