### ISSUE TITLE
Rails-assets/Bower compatible

### ISSUE THREAD

**Issue by drush** [moxiecode/plupload#1111]
Post-install message from rails-assets-plupload:
  This component doesn't define main assets in bower.json.
  Please open new pull request in component's repository:
  https://github.com/moxiecode/plupload

Add a bower.json file to the root so that plupload is compatible with bower and rails-assets (http://rails-assets.org)

**Comment by ricardosasilva** [comment]
+1 for bower support

**Comment by jayarjo** [comment]
Added `bower.json`. Although it seems there's an intensive campaign going on (lead by FB) to kill it off.
