### ISSUE TITLE
win7 safari html5 chunk upload bug

### ISSUE THREAD

**Issue by SunLn** [moxiecode/plupload#1122]
OS : WIN7
Safari version  : 5.1.7（7534.57.2）

My main init args like  :

``` javascript
        runtimes: 'html5,flash,html4',
        browse_button: 'pickfiles',
        container: 'container',
        drop_element: 'container',
        max_file_size: '100mb',
        flash_swf_url: 'js/plupload/Moxie.swf',
        dragdrop: true,
        chunk_size: '4mb',
```

I catch the http request via wireshark when I upload a file larger than 4m ,find the Content-Length is the whole file size not 4mb . So server returns error because '4mb'  is hoped  .The runtime is Html5.

I try to add 

``` javascript
            'required_features': 'slice_blob',
```

in init args.Then the runtime changes to Flash .But still have problems.

Some user report iPhone5s iOS7.0 safari also have the problem ,but I have not got their safari version.

Other advanced  browsers like chrome\ff\ie10 do not have this problem.

**Comment by jayarjo** [comment]
I might not remember correctly, but I think Safari on Windows didn't support file slicing, so there was basically no way to send it in chunks. But I guess now that Safari for Windows is gone, we can close this one.
