### ISSUE TITLE
Silverlight: Cookies not sent when 'headers' option is set

### ISSUE THREAD

**Issue by der-andy** [moxiecode/plupload#1125]
I have an app which uses the HTML5 engine with fallback to Silverlight and Flash. I was testing the Silverlight engine when I found out that my session ID cookie is not sent when I specify any header in the plupload options. Without the header option, all cookies are sent correctly. With HTML5 and Flash, cookies are also sent _with_ the headers option. Furthermore I remember that it even worked with Silverlight before I upgraded from 1.5.1.1 to 2.1.2.

**Comment by jayarjo** [comment]
It is a known issue, the mode that can send cookies in silverlight cannot send custom headers and vice versa. We have table of capabilities outlined here by runtimes and  operational modes: [https://github.com/moxiecode/plupload/wiki/Required-Features](Required Features).
