### ISSUE TITLE
Why can't I upload XML files?

### ISSUE THREAD

**Issue by ceylog** [moxiecode/plupload#1126]
Why can't I upload XML files?

**Comment by cTallberg** [comment]
@ceylog @jayarjo  Hi, where is it possible to configure my file filter? Can´t find it. Thanks! :)

**Comment by jayarjo** [comment]
@cTallberg not sure what the question is? Check: http://www.plupload.com/docs/v2/File-Filters.

**Comment by cTallberg** [comment]
@jayarjo Problem is that when I try to upload an XML-file to an Issue in Github.com it says that "XML files are restricted" 

How do I navigate in Github.com to customize my file filters so I can upload an XML-file to my Issue? :)

**Comment by jayarjo** [comment]
zip it maybe?

**Comment by cTallberg** [comment]
Yes of Course that works. I got the impression that there was a better way. anyways thanks:)

**Comment by jvanderberg** [comment]
See export of QuirkLocal blog
[quirklocal.WordPress.2023-10-31.xml.zip](https://github.com/moxiecode/plupload/files/13220521/quirklocal.WordPress.2023-10-31.xml.zip)
