### ISSUE TITLE
Image scaled up when preserve_headers set to false

### ISSUE THREAD

**Issue by Bnaya** [moxiecode/plupload#1127]
When the selected image is smaller then the resize width/height and supposedly not needs a dimension change, if preserve_headers is set to false it will be up scaled to the given resize width/height.

The bug is on these lines:
https://github.com/moxiecode/plupload/blob/master/js/plupload.dev.js#L1146-L1159

This is a crude fix for that issue:
https://github.com/Bnaya/plupload/compare/scaleup-bug?expand=1,
if its ok ill make a pr from it

**Comment by fletc3her** [comment]
I can confirm this bug as well. I was seeing images being scaled up to the max size I specified. Toggling preserve_headers to true has restored the proper behavior.

**Comment by mix3d** [comment]
Actually, this is a desirable outcome for me; but the latest code seems to not resize upwards anymore, even with `preserve_headers:false`. So the "bug" is fixed, but it's actually what I wanted.

 I'm trying to make sure our images are always square, and a set size; so when a smaller-than-the-crop-size is uploaded (the crop works, but not a scale), it ends up stretched when the image is displayed at the other end.

**Comment by jayarjo** [comment]
v2.2.0 now has some additional options for image resizing, specifically [crop and fit](http://www.plupload.com/docs/v3/Image-Resizing-on-Client-Side#crop-and-fit).
