### ISSUE TITLE
Choose file to upload from the server instead from the computer

### ISSUE THREAD

**Issue by bee-interactive** [moxiecode/plupload#1128]
Hi there!

I was wondering if there is a way to add a button to choose a file from the server, instead of browsing our files on the computer.
Like you give a special path on the server, and the user can choose in the file structure. Like the tinymce plugin does for the pictures. The idea here is to create a folder that many users can access online, so they all have access to all the pictures and files.

Thanks for your time!

**Comment by Fahadsalaam** [comment]
@jayarjo please can you provide an example/demo for choosing files from google drive?
