### ISSUE TITLE
Support for promises in events

### ISSUE THREAD

**Issue by lowski** [moxiecode/plupload#1131]
Hello,
It's more of a question rather than issue. Is there a way to support promises in the events? For example in beforeUpload I need to get token from my server before file can be uploaded, I also need to modify the url for uploading.

If I could use promise in the 'beforeUpload' event which changes the settings.url after my server returns the token that could solve my problem.

**Comment by redgenie** [comment]
+1

**Comment by matthewjmink** [comment]
This would be a great feature. We have the exact need as @lowski - retrieving a token prior to upload. Waiting for a promise to resolve before continuing would greatly simplify the process.

**Comment by jayarjo** [comment]
If you return false from `BeforeUpload` file won't be uploaded. Then you can do alterations or any async operations that you require and requeue the file by changing it's state to `plupload.QUEUED`. File will be picked on next upload iteration automatically.

We probably won't be adding promises to Plupload.
