### ISSUE TITLE
IE Silverlight crash if second plupload not visible

### ISSUE THREAD

**Issue by johnzangwill** [moxiecode/plupload#1141]
![capture](https://cloud.githubusercontent.com/assets/8927258/4419038/63cfc638-4566-11e4-94d5-4fd58b407b87.PNG)
Runtime: Silverlight on IE8 and IE9.

Adding a second plupload button in a container with style='display:none' (in our case in a tab) causes the visible button to fail when or before a file is selected.

There are different results if Flash is included in the runtime.

This worked fine with the previous version 1.5. I am evaluating version 2.1 with a view to renewing my corporate OEM license, but this bug is a showstopper.

The pictured example is a copy of the supplied examples/custom.html, with a second uploader included in a div with style='display:none'.

Selecting files from the visible uploader causes the error.

As far as I can see the error arises when runtime.mode is checked:
     if (!runtime.mode) {
        runtime.trigger('Error');
        return;
    }
This then calls runtime.destroy() which then has a further error when it tries to delete the shims.

**Comment by spenie** [comment]
thank you very much! I had solved my problem with you suggestion.
