### ISSUE TITLE
2.1.2 - Certain jpeg are not resized (not dependant on image dimension nor file size)

### ISSUE THREAD

**Issue by eltorio** [moxiecode/plupload#1146]
dear all,

I expect a problem with latest stable version and master version (2014-10-11)
Certain images are not resized.
I made some test with all runtimes under Chrome windows 37.0.2062.124 and IE 11.0.9600.17278

I'd like to resize on client side with height and width set to 640  
I have one image coming directly from my digital camera (DSCN0641) witch is not resized and sent as is, the second (DSCN0641-v2) was just exported with Photoshop CC 2014 for the web without resizing and with a quality of 90%  
DSCN0641-v2 is correctly resized!
Images size are identical (3000x4000) size are nearly identical 4613708 bytes (original) vs 4599139 bytes (v2)

![dscn0641](https://cloud.githubusercontent.com/assets/6966689/4601943/19da5c1e-511e-11e4-98b8-477c078e31c6.JPG)  
![dscn0641-v2](https://cloud.githubusercontent.com/assets/6966689/4601942/19d56c04-511e-11e4-96b3-a3651e7a0b97.jpg)  
I'm not sure that GitHub does not modify the file so raw files can be downloaded here:

[DSCN0641](https://www.dropbox.com/s/xnghoaxkd5kdw9b/DSCN0641.JPG?dl=0)  
[DSCN0641-v2](https://www.dropbox.com/s/u8smuxrt5p85vs3/DSCN0641-v2.jpg?dl=0)  

this is my javascript code
```
$(function() {
        var uploader = new plupload.Uploader({
          runtimes: "html5,html4,flash,silverlight",
          flash_swf_url: "<?php print dirname($_SERVER["SCRIPT_NAME"]).'/'.'plupload/js/Moxie.swf'; ?>",
          silverlight_xap_url: "<?php print dirname($_SERVER["SCRIPT_NAME"]).'/'.'plupload/js/Moxie.xap'; ?>",
          browse_button: 'browse',
          url: '/ictiovis/upload',
          multi_selection: false,
          max_file_size: "10mb",
          prevent_duplicates: true,
          filters:{
                  mime_types : [
                            { title : "Image files", extensions : "jpg,jpeg,png" }
                        ]
                 },
          resize: {
            width: 640,
            height: 640,
            preserve_headers: true
          }
        });

        uploader.init();

        uploader.bind('PostInit', function(up) {
                $('#console').html("METHOD: " + up.runtime);
        });

        uploader.bind('Error', function(up, err) {
                  $('#console').html( $('#console').html() + "\nError #" + err.code + ": " + err.message );
        });

        uploader.bind('FileUploaded', function(up,filei,object) {
                    $("#console").html("SUCCESS\n"+object.response);
                    if (object.response.substring(0, 7) === "FILEID:") {
                        $("#edit-photoid").val( object.response.substring(7) );
                        $("#container").css('display','none');
                        $("#submit-button").css('display','inline');
                    }
        });

        uploader.bind('FilesAdded', function(up, files) {
                  while (up.files.length > 1) {
                        up.removeFile(up.files[0]);
                         $('#filelist').html("");
                         }
                  var html = '';
                  plupload.each(files, function(file) {
                    html += '<li id="' + file.id + '">' + file.name + ' (' + plupload.formatSize(file.size) + ') <b></b></li>';
                  });
                  $('#filelist').html( $('#filelist').html() + html );
          });
        uploader.bind('UploadProgress', function(up, file) {
                  $('#'+file.id).children('b').html('<span>' + file.percent + "%</span>");
          });
        $('#start-upload').click( function() {
                  uploader.start();
          });

});

```
Please help!

**Comment by dlt-** [comment]
Same thing with 2.1.4. Some JPGs do work, some other do not.

**Comment by jayarjo** [comment]
Can you share jpegs that fail? I'm refactoring exif parser at the moment.

**Comment by dlt-** [comment]
This one resizes correctly: http://code.mediadrive.fi/plupload-resize-fail/phantom.jpg
..and this doesn't: http://code.mediadrive.fi/plupload-resize-fail/_IMG2487.jpg

The following resize parameters were used:
resize : {width : 2048, height : 1536, quality : 90 }

Chrome, Firefox and Safari - same result.
Removing or preserving exif metadata while resizing did not make any difference.

**Comment by skylinex** [comment]
Same problem (Plupload 2.1.4, html5, chrome 43.0.2357.125) with this picture: https://monphotoblognature.files.wordpress.com/2012/07/img_0647.jpg
parameters:
resize : {width : 2000, height : 1500, quality : 95 }

**Comment by jayarjo** [comment]
[2.1.5](https://github.com/moxiecode/plupload/releases/tag/v2.1.5) is out now with the fix.
