### ISSUE TITLE
provide a callback/way for modifying the file added

### ISSUE THREAD

**Issue by antokara** [moxiecode/plupload#1148]
So far, you only allow the downsize of an image added.
In case custom manipulation of a file/image is needed, 
would it be possible to provide a callback or a way to modify the file added through the FilesAdded event?

**Comment by jayarjo** [comment]
It is possible to hook onto BeforeUpload event and cancel it by returning *false*, then using core `moxie.file.FileReader` to preload file with `file.getNative()`, then doing whatever is planned and constructing the Blob, which can be added back to the queue via `uploader.addFile()`.

One will have to remove original file from the queue then.

I'm afraid there's no other way :/
