### ISSUE TITLE
Best way to reject file queue attempt

### ISSUE THREAD

**Issue by aik099** [moxiecode/plupload#1150]
Right now user can select 100 files, which will be added to queue and uploaded. I want to limit it to say 50.

Right now I do this by firing `Error` event from `FilesAdded` event handler. Internally Plupload is removing file from queue, however in the process I get JS error when Moxie tried to send next file chunk to the server.

I've found http://stackoverflow.com/questions/15513689/jquery-plupload-restrict-number-of-uploads/15520225#15520225 possible solution, but I don't want stall user with 50 alert windows (1 alert window per each file).

Instead I want to display file in queue but show an error next to it, like it has an error during upload. That's why I'm calling `Error` event of Plupload. In turn in my `Error` event handler I decorate queued elements differently (show an error in tooltip).

Maybe File filters (see http://www.plupload.com/docs/File-Filters) is the solution I should be using, because they naturally support throwing errors and rejecting queue attempts of needed files. And the error handler I had should be able to catch their errors.

**Comment by jayarjo** [comment]
Yep, I'm afraid there's no other way around. Or you could simply cycle through the files in FilesAdded and mark them as failed and show some custom ui for the case.

**Comment by aik099** [comment]
> Yep, I'm afraid there's no other way around.

You mean, that using file filters is recommended approach?

**Comment by jayarjo** [comment]
File filters are for filtering files out completely, and throwing customized error for each one. But if you want to keep files somehow, probably will be better to do it manually.
