### ISSUE TITLE
Bug: Unable to upload directly from mobile device's camera

### ISSUE THREAD

**Issue by henrywright** [moxiecode/plupload#1155]
Testing below was done on Samsung Galaxy S4 Mini running Android 4.2.2. Demo link: http://jsfiddle.net/385shjqf/

Steps to reproduce:

_as you will see, the following works:_

1. Click on Select files and choose an image from your mobile phone's gallery
2. The image's filename appears on screen. You can now click on Upload files to start the upload

_but this fails:_

1. Click on Select files and take a photo with your phone's camera
2. The image's filename **doesn't** appear on screen. Click Upload files to see that nothing happens

**Notes**

The problem doesn't happen at all when I use my tablet or desktop. I have also had a report from someone using an iPhone 5 that the problem doesn't happen for them.

Source code in the demo link was taken directly from here: http://www.plupload.com/examples/core

**Comment by korayguclu** [comment]
I have the same problem.! 
Plupload only triggers following events on andrdoi default browser
Init, 
PostInit
FilesAdded

but no upload takes place.
