### ISSUE TITLE
execute 'FileUploaded' handler in order

### ISSUE THREAD

**Issue by SunLn** [moxiecode/plupload#1156]
Hello，jayarjo：
I want to develop a plugin based on plupload, but have a problem.
I bind the the first 'FileUploaded' handler in which there is a ajax request. I hope that plupload executes the second  'FileUploaded' handler which is usually set by user after the ajax request is finished.
But plupload  executes  the second 'FileUploaded' handler before the first 'FileUploaded' handler is finished.
One way to solove this problem is  like this :

``` javascript
//plugin struct 
plugin =  function (option) {
 // statement a function  named 'B' ,
 // set it's value to 'FileUploaded' handler in  option's init.
 // set origin  'FileUploaded' handler  to null to prevent execute twice.

   var uploader = new plupload.Uploader(option);

  uploader.bind('FileUploaded' ,function(){
      // ajax call 
      // when ajax done,execute B()
  });
  return uploader;
}

// user's code 
var UserUploader = plugin.uploader({
   ...,
   init : {
      'FileUploaded' : function () {
          // code to be excuted afther the ajax call is done
      }
   }
});
```

But I think this way is ugly，and there is still a problem when user bind like :

``` javascript
UserUploader.bind('FileUploaded' : function () {
          // code to be excuted afther the ajax call is done
          // but still excute before the ajax call is done
})
```

It troubles me a long time,I have seached google,but still have no idea how to solve it.
Hope to get your reponse.
Thanks very much.

SunLn

**Comment by jayarjo** [comment]
Ugly or not that's how you handle async operations in JavaScript world :)
