### ISSUE TITLE
why filters not take effect

### ISSUE THREAD

**Issue by Jason2010** [moxiecode/plupload#1159]
upload version 2.1.2 ,using IE or chrome browser, have the problem like this ：

``` javascript
var admin_brand_edit_uploader = new plupload.Uploader({ 
            browse_button : 'admin_brand_edit_browse',
            url : '/admin/upload.do',
            flash_swf_url : 'js/Moxie.swf',
            silverlight_xap_url : 'js/Moxie.xap',
            filters:{
                mime_types:[{title:"picture",extensions:"jpg"}],
                max_file_size : '500kb', 
                prevent_duplicates : true
            }
        });
```

when I click the button( admin_brand_edit_browse), 
why still like this, not what i wanted : I just want the file extension is : picture (*.jpg) and I only can choose *.jpg file
the real result like this : sorry some is in chinese.

```
所有文件(*.*)
图片(*.gif,*.jpg,*.jpeg,*.png)
HTML(*.htm,*.html)
自定义文件（*.jpeg,*.jpg,*.jpe,*.jfif...)
```

**Comment by jayarjo** [comment]
It gets better as the time goes by and although browser support still inadequate, I;m going to close this one, since there is nothing we can do about it.
