### ISSUE TITLE
Missing file filtering for .csv and .json.

### ISSUE THREAD

**Issue by Ne4to777** [moxiecode/plupload#1160]
It looks unbelivable but any file extension works fine with file filter except .csv and .json. Even .sgdfdf or .5et55 works fine. I'm going crazy. (Win7x64). 
I just modified example file:

```
filters :
    {
        mime_types: 
            [
                {
                    "title": "Files",
                    "extensions":"json"
                }
            ]
    }
```

**Comment by cmb69** [comment]
Um, works fine here (Win7 64bit, html5 runtime, pluploadQueue widget).

**Comment by jayarjo** [comment]
Browsers now have better support for file filtering, so this should work everywhere now.
