### ISSUE TITLE
Getting Error #-200: HTTP Error. while uploading large files.

### ISSUE THREAD

**Issue by ijmachado** [moxiecode/plupload#1163]
I implemented the code given in Chunking section and it works fine for smaller files, i tried uploading a 6mb file and it worked, but when i try to upload a 27mb file it gives me Error #-200: HTTP Error after some minutes.

 Any idea what i may be doing wrong? The code im using is literally a copy paste of what is given in Chunking section of the project.

**Comment by DJD1** [comment]
Did you find a solution to this issue?  I'm now having the same problems for files over 8mb on a once previously working system!

I suspect it may be changes/settings at the host level as my local web server has no issues using the same code.

I have already tried changing the max limits for php on my host to no avail.

**Comment by DJD1** [comment]
After trying to get round this issue, I found that Increasing the chunk_size to 1mb fixed the problem for me!

I've just uploaded several large files without any issues, the largest being ~50mb.
