### ISSUE TITLE
Android upload from documents fails with "File extension error."

### ISSUE THREAD

**Issue by nextinterfaces** [moxiecode/plupload#1171]
1. Using an Android Nexus 7 tablet try uploading an image 
2. "Choose file to upload" popup appears. Choose /Documents 
3. Locate the file from Android file system

The following error is being dumped in Chrome dev console id: 
<b>Upload error:-601: File extension error.</b>
<code>{id: "o_197shsoo610qa1as5j311sk30h", name: "image%3A22", type: ""...}</code>

When decoded the Android image extension turns out to be in the format <b>image:numeric_value</b>

Question is, is there way to gracefully extend plupload to handle "File extension" checking exceptions?

**Comment by TissueFluid** [comment]
I have the same question on my Android phone.

**Comment by jayarjo** [comment]
The code that checks for the file type is fully standalone and here is how it is actually declared in the Plupload source:

```javascript
plupload.addFileFilter('mime_types', function(filters, file, cb) {
	if (filters.length && !filters.regexp.test(file.name)) {
		this.trigger('Error', {
			code : plupload.FILE_EXTENSION_ERROR,
			message : plupload.translate('File extension error.'),
			file : file
		});
		cb(false);
	} else {
		cb(true);
	}
})
```

`filters.regexp` is auto-generated internally every time `mime types` are changed (I don't recommend to rely on its existence).

`plupload.addFileFilter()` is public static method. You can easily add your own filters or redefine default ones. For example you could put some environment aware code into the filter, that will process image files on Android devices in a different way. We even have brief getting started guide here: [File Filters](http://plupload.com/docs/File-Filters).
