### ISSUE TITLE
file percent 100 while servers haven't return to client side

### ISSUE THREAD

**Issue by hectorguo** [moxiecode/plupload#1176]
While I  use `UploadProgress` event to get the `file.percent`, I find that when the file has been uploaded to the server but has not received the response info, the `file.percent` return **100**.
I know this shows that the file have been completely uploaded to the server,  
However, for users,  they may confuse why the file percent shows **100%** while the server haven't returned to success to me.

Can it be fixed that the upload percent shows 100% until the server return the success?

**Comment by CanRau** [comment]
great thanks guys!
