### ISSUE TITLE
Moxie.cdn.swf is not working

### ISSUE THREAD

**Issue by justmobilize** [moxiecode/plupload#1180]
Using your supplied jsFiddle: http://jsfiddle.net/gh/get/jquery/1.9.1/jayarjo/plupload-demos/tree/master/2.x/core/bundled and modifying line 9 to runtimes : 'flash'. Plupload will throw "Error #-500: Init error."

**Comment by jayarjo** [comment]
Probably GitHub doesn't allow hotlinking anymore. Otherwise seems to works as expected. Also we now have our own [Playground](http://play.plupload.com) for filing demos and problematic cases.
