### ISSUE TITLE
TypeError: I.getShim(...).exec is not a function

### ISSUE THREAD

**Issue by johonas** [moxiecode/plupload#1182]
When i set runtime to flash, other options are all default and start an upgrade, i get the following JS exception:

TypeError: I.getShim(...).exec is not a function

I Use Plupload 2.1.4 and FF 34.0

**Comment by johonas** [comment]
If i set container to document.body, the File-Dialog won't open by pressing on the button supplied with browse_button,

**Comment by johonas** [comment]
i solved the problem by assigning a high z-index to the container object.

**Comment by AH72KING** [comment]
HI i am having same issues
at my site url = [Mobile Baich ](http://www.mobilebaich.com/add-new/?action=change)
problem is when i add new images its fine but after limit when i added last image means 5th one in my site case it gives an error in console

`TypeError: u.getShim(...).exec is not a function`

so even i remove any image i cannot add more 
any solutions please thanks
