### ISSUE TITLE
No chunks sent using FF and Flash

### ISSUE THREAD

**Issue by johonas** [moxiecode/plupload#1188]
I'm using plupload 2.1.2 and chunked upload. Runtime is set to flash for testing, chunk-size is 5242880.

When i start uploading, i don't get any chunk uploading calls but after a short time, i get a FileUploaded callback.

The test-file I'm using is 160mb.

When i set runtime to html5 everything is working fine.

I tested using firefox 34.0.

The object is initialized like this:

    var settings = {
      runtimes : 'flash',
      browse_button : "id_of_the_dom_element",
      container: document.body,
      url : '/relative/url',
      flash_swf_url : 'assets/flash/Moxie.swf',
      multi_selection: false,
      chunk_size : '5242880'
    };
    
    var uploader = new plupload.Uploader(settings);
    
    uploader.init();

The problem occurs also when i disable chunking. I get a FileUploaded callback before the file gets uploaded.

-e-
i got the same issue using html4

**Comment by jayarjo** [comment]
Chunking is disabled in Flash runtime by default, since it doesn't do what it is meant to. Check: [When to use chunking and when not?](http://plupload.com/docs/Frequently-Asked-Questions#when-to-use-chunking-and-when-not).

If you want to enable chunking anyway, set: `required_features` to _true_.

**Comment by jayarjo** [comment]
Btw, chunk_size is meant to be number, not string. Although should work anyway.

**Comment by johonas** [comment]
When i set required_features to true, i get an "Init error".

As i understand the documentation under [1], required_features is used to force plupload to choose a runtime that fulfills the required features in the config.

[1]
http://www.plupload.com/docs/Options#required_features

**Comment by Arantor** [comment]
I had this too. Couldn't seem to figure out how to get Plupload to accept chunking on Flash - because the circumstances I primarily deal with, the memory issue is not a concern.
