### ISSUE TITLE
Adding dynamically created image file to uploader object

### ISSUE THREAD

**Issue by vijay52** [moxiecode/plupload#1192]
Actually I'm using plupload to upload image to my server. Now I'm using another jQuery cropper plugin to crop the image and then return a base64 data for the cropped image.

Now I'm removing the previous original image file from uploader object by using removeFile(), and then created a Moxie.file of the cropped image and then adding it using addFile() method, but that doesn't go that much well. 

The new file object is not getting added to  uploader object. 

I've tried adding plupload file object for the cropped image as described in link:  http://www.plupload.com/docs/Uploader#addFile-filefileName-method

But that is also not working. 

Also I don't want to use the plupload's crop feature as it has certain limitations for cropping. (http://www.plupload.com/docs/Image-Resizing-on-Client-Side)

Please help me with this.

**Comment by mschipperheyn** [comment]
Any success w this?

**Comment by fakihariefnoto** [comment]
hai, sorry if this late, but i'm getting what you did to, so there was post from davit on plupload forum and i'm just doing this

`function dataURItoBlob(dataURI) {
    /* convert base64/URLEncoded data component to raw binary data held in a string */
    var byteString;
    if (dataURI.split(',')[0].indexOf('base64') >= 0)
        byteString = atob(dataURI.split(',')[1]);
    else
        byteString = unescape(dataURI.split(',')[1]);

    /* separate out the mime component*/
    var mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];

    /* write the bytes of the string to a typed array */
    var ia = new Uint8Array(byteString.length);
    for (var i = 0; i < byteString.length; i++) {
        ia[i] = byteString.charCodeAt(i);
    }

    return new Blob([ia], {type:mimeString});
}

function add_new_picture(resultingBlob) {
    var file = new o.File(null, resultingBlob);
    file.name = "newImage.png"; // giving it an arbitrary name here
    uploader.addFile(file);
}`

you can convert your base64 to blob and than assign to file
add_new_picture(dataURItoBlob(yourbase64));
hope this help
