### ISSUE TITLE
Upload EXE using Plupload corrupt file

### ISSUE THREAD

**Issue by nigrosimone** [moxiecode/plupload#1193]
Plupload works very well with most of the file type (jpg, mpeg, zip). However if I try to load an exe in some case, these are corrupt.

When the exe are corrupt, if I try to open them with notepad++, I find:

```
------------Ef1Ef1ae0ae0Ef1ae0KM7Ef1cH2KM7
Content-Disposition: form-data; name="Filename"

Project1.exe
------------Ef1Ef1ae0ae0Ef1ae0KM7Ef1cH2KM7
Content-Disposition: form-data; name="name"

Project1.exe
------------Ef1Ef1ae0ae0Ef1ae0KM7Ef1cH2KM7
Content-Disposition: form-data; name="file"; filename="Project1.exe"
Content-Type: application/octet-stream

[binary stream]
------------Ef1Ef1ae0ae0Ef1ae0KM7Ef1cH2KM7
Content-Disposition: form-data; name="Upload"

Submit Query
------------Ef1Ef1ae0ae0Ef1ae0KM7Ef1cH2KM7--
```

otherwise I find only binary stream

if I try to remove them with notepad++, after save the file, it works properly.

I tried with different exe, it seems that if the weight goes beyond the 2MB, this is always corrupt.

I'm using the examples and I have not changed anything

My setting:

```
PHP Version 5.5.9
System          Windows NT PC-XXX 6.0 build 6002 (Windows Vista Service Pack 2) i586 
Compiler        MSVC11 (Visual C++ 2012) 
Architecture    x86 
Server API      Apache 2.0 Handler 
```

I also wrote (with more details) on stackoverflow
http://stackoverflow.com/questions/27998852/php-javascript-upload-exe-using-plupload-corrupt-file

**Comment by jayarjo** [comment]
Can you share failing exe file? 'cause in our tests we do not encounter such thing.

**Comment by nigrosimone** [comment]
Download all my setup (plupload-2.1.2 + Exe + Corrupted file)
http://www.sndesign.it/shared/stackoverflow/plupload-2.1.2.zip

The zip also contains a corrupted upload file in plupload-2.1.2/examples/upload/file_54c4c1d05c2ef folder 

Prepare for the test:
1. Unzip plupload-2.1.2.zip in your htdocs
2. Open IE 9 (IE 9 always fails), and go to: http://localhost/plupload-2.1.2/examples/custom.html
3. Select file in %YourHtdocs%/plupload-2.1.2/examples/TryMe.exe
4. go in upload folder %YourHtdocs%/plupload-2.1.2/examples/upload/ and find the uploaded file

thanks for the help

**Comment by jayarjo** [comment]
Don't have IE9, tried in IE8 (Flash and Silverlight), can't repeat the glitch. Btw, couldn't open the zip properly - it failed to extract the corrupted uploaded file.
