### ISSUE TITLE
The problem of IDN, chinese domain names

### ISSUE THREAD

**Issue by 55574065** [moxiecode/plupload#1194]
In the IE 789 browser, Chinese domain cannot be uploaded files,The bug is very easy to reproduce.
Both the flash runtimes or the Silverlight runtimes is the same.

**Comment by jayarjo** [comment]
Could you provide an example?

**Comment by 55574065** [comment]
Hi,Reproduce this problem requires a specific environment .
1. you must make the environment in the Chinese domain name ,
2. and must be flash runtimes.

I used BIND  to parse Chinese Domain Name . The code as examples, nothing special.

**Comment by jayarjo** [comment]
Can you post typical domain name in chinese, that you are having a problem with?

**Comment by jayarjo** [comment]
I'd suggest to encode your  domain in Punycode. Formore details see my response to: https://github.com/moxiecode/plupload/issues/1336#issuecomment-320492390.
