### ISSUE TITLE
Is that possible to add multiple custom API plupload in same form?

### ISSUE THREAD

**Issue by Plupload** [moxiecode/plupload#1197]
like this:
<form>

<div width="20px" id="progressbar"></div>

<div id="container1">
    <a id="pickfiles1" href="javascript:;">[Select files]</a> 
    <a id="uploadfiles1" href="javascript:;">[Upload files]</a>
</div>

<div id="container2">
    <a id="pickfiles2" href="javascript:;">[Select files]</a> 
    <a id="uploadfiles2" href="javascript:;">[Upload files]</a>
</div>

</form>

If possible than please give me solution for that

**Comment by jayarjo** [comment]
Yes, as many as you like, however custom api doesn't add any form fields automatically, so one will have to do it himself.

How did you came up with the username like that? Don't you have some firstname-lastname? Should have reserved it when I could :)

**Comment by Plupload** [comment]
Yup my name is reserved:)
