### ISSUE TITLE
Chunking not working as it should ... unusual behaviour 

### ISSUE THREAD

**Issue by phillmoore** [moxiecode/plupload#1202]
Hi,

I'm hoping someone can help me. I've setup plupload using the queue widget on HTML5. I'm using upload.php 'out of the box' and on the latest version.

Everything works fine with chunking turned off. I can upload any file (and any filetype) I wish. I do need to turn chunking on, but when I do so ...

i) everything works fine if the file is a text or image filetype, ... but ...
ii) all other filetypes fail at the end of the first chunk, no file is written, not even the first .part file.
iii) this is not connected to the file extension as I have changed these in my testing

Tests I've performed:

i) Chunking an image file ... success/Upload without chunking ... success
ii) Chunking a text file ... success/Upload without chunking ... success
iii) Taking a text file and changing the extension to .zip and chunking ... success/Upload without chunking ... success
iv) Chunking a zip file ... FAIL (as described above)//Upload without chunking ... success
v) Repeated iv) for access files, excel files, executables etc ... same outcome in both scenarios

Has anyone had a similar experience. Host is a windows shared host running php5.3.

Thanks in advance

**Comment by jayarjo** [comment]
Are you sure those field types that make it through for enabled chunking are actually chunked? They could be simply smaller than the you specify for the single chunk. It should be something about your environment, since it works in the usual scenario.

What is the error that you receive back from the upload.php?

**Comment by phillmoore** [comment]
Hi, yes they are actually chunked. Chunk size is set to 2mb, i'm testing on 17mb files. The 'fails' do not get to upload.php which is very confusing. I.e. a 17mb text file being chunked works perfectly, a 17mb excel/word/zip/pdf etc loads the first chunk in the runtime environment, i.e. shows 12%, but then does not call upload.php. I have tested this by putting a directory write on the first line of upload.php. In all scenarios where it works, the directory gets created, in the fails it does not, so upload.php cannot be being called by the javascript by the looks of things.

**Comment by jayarjo** [comment]
Sounds like you have some kind of restriction either in your upload.php or in your server env, since Plupload doesn't really differentiate between file types by itself.

**Comment by jayarjo** [comment]
Could you arrange a test case online?

**Comment by phillmoore** [comment]
I would agree, but in that scenario the non chunked uploads of the identical files would also fail, but they do not - that rules out the server env. The upload.php is the latest version straight from the plupload website. I will put up an online example ... thanks for trying to help

**Comment by phillmoore** [comment]
ok...

http://www.regentaccounting.co.uk/axsdb/dbupload.php
http://www.regentaccounting.co.uk/axsdb/dbupload_chunk.php

The only difference between the two urls is '_chunk' has chunking set to 2MB. If you use a non-text file, that is larger than 2MB but less than 20MB (system upload limit).

If you submit your file to the first url, it will work.
If you submit exactly the same file to the second url, it will fail.

The two urls are copies of each other, just with chunk_size added to the second.

**Comment by phillmoore** [comment]
Upload.php is as follows ...

```
<?php
/**
 * upload.php
 *
 * Copyright 2013, Moxiecode Systems AB
 * Released under GPL License.
 *
 * License: http://www.plupload.com/license
 * Contributing: http://www.plupload.com/contributing
 */

#!! IMPORTANT: 
#!! this file is just an example, it doesn't incorporate any security checks and 
#!! is not recommended to be used in production environment as it is. Be sure to 
#!! revise it and customize to your needs.

// Make sure file is not cached (as it happens for example on iOS devices)
header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
header("Cache-Control: no-store, no-cache, must-revalidate");
header("Cache-Control: post-check=0, pre-check=0", false);
header("Pragma: no-cache");

/* 
// Support CORS
header("Access-Control-Allow-Origin: *");
// other CORS headers if any...
if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
	exit; // finish preflight CORS requests here
}
*/

// 5 minutes execution time
@set_time_limit(5 * 60);

// Uncomment this one to fake upload time
// usleep(5000);

// Settings
$targetDir = "../axsdb/tmp";
$cleanupTargetDir = true; // Remove old files
$maxFileAge = 5 * 3600; // Temp file age in seconds

// Create target dir
if (!file_exists($targetDir)) {
	@mkdir($targetDir);
}

// Get a file name
if (isset($_REQUEST["name"])) {
	$fileName = $_REQUEST["name"];
} elseif (!empty($_FILES)) {
	$fileName = $_FILES["file"]["name"];
} else {
	$fileName = uniqid("file_");
}

$filePath = $targetDir . DIRECTORY_SEPARATOR . $fileName;

// Chunking might be enabled
$chunk = isset($_REQUEST["chunk"]) ? intval($_REQUEST["chunk"]) : 0;
$chunks = isset($_REQUEST["chunks"]) ? intval($_REQUEST["chunks"]) : 0;


// Remove old temp files	
if ($cleanupTargetDir) {
	if (!is_dir($targetDir) || !$dir = opendir($targetDir)) {
		die('{"jsonrpc" : "2.0", "error" : {"code": 100, "message": "Failed to open temp directory."}, "id" : "id"}');
	}

	while (($file = readdir($dir)) !== false) {
		$tmpfilePath = $targetDir . DIRECTORY_SEPARATOR . $file;

		// If temp file is current file proceed to the next
		if ($tmpfilePath == "{$filePath}.part") {
			continue;
		}

		// Remove temp file if it is older than the max age and is not the current file
		if (preg_match('/\.part$/', $file) && (filemtime($tmpfilePath) < time() - $maxFileAge)) {
			@unlink($tmpfilePath);
		}
	}
	closedir($dir);
}	


// Open temp file
if (!$out = @fopen("{$filePath}.part", $chunks ? "ab" : "wb")) {
	die('{"jsonrpc" : "2.0", "error" : {"code": 102, "message": "Failed to open output stream."}, "id" : "id"}');
}

if (!empty($_FILES)) {
	if ($_FILES["file"]["error"] || !is_uploaded_file($_FILES["file"]["tmp_name"])) {
		die('{"jsonrpc" : "2.0", "error" : {"code": 103, "message": "Failed to move uploaded file."}, "id" : "id"}');
	}

	// Read binary input stream and append it to temp file
	if (!$in = @fopen($_FILES["file"]["tmp_name"], "rb")) {
		die('{"jsonrpc" : "2.0", "error" : {"code": 101, "message": "Failed to open input stream."}, "id" : "id"}');
	}
} else {	
	if (!$in = @fopen("php://input", "rb")) {
		die('{"jsonrpc" : "2.0", "error" : {"code": 101, "message": "Failed to open input stream."}, "id" : "id"}');
	}
}

while ($buff = fread($in, 4096)) {
	fwrite($out, $buff);
}

@fclose($out);
@fclose($in);

// Check if file has been uploaded
if (!$chunks || $chunk == $chunks - 1) {
	// Strip the temp .part suffix off 
	rename("{$filePath}.part", $filePath);
}

// Return Success JSON-RPC response
die('{"jsonrpc" : "2.0", "result" : null, "id" : "id"}');

```

**Comment by maarten-vh** [comment]
Just tested the chunked upload url. It works perfectly with all kinds of files (see screenshots).
What browser do you use? I've tested with latest Chrome version on Windows 7.

![schermafdruk 2015-02-12 08 54 08]
(https://cloud.githubusercontent.com/assets/10941577/6163617/32e050f0-b295-11e4-9e09-7be0a176187a.png)
![schermafdruk 2015-02-12 08 51 19](https://cloud.githubusercontent.com/assets/10941577/6163616/32de5250-b295-11e4-93d0-ef1cc077f558.png)

**Comment by phillmoore** [comment]
Thank you for this ... I hadn't tried chrome but like you say, it does work on there.

Thanks to both of you :)

**Comment by maarten-vh** [comment]
Just for the record, which browser and operating system did you use?

**Comment by phillmoore** [comment]
For the original testing with the fails ...

IE11 on Windows 8.1; and
FF35 on Windows 8.1

I'm not near my Windows 8.1 environment today so couldn't test chrome on that, but I tested chrome on an xp environment and it worked. I also tested FF on an xp environment and that also worked.

**Comment by ErAshu** [comment]
When i use this api by iOS device, this is give the error 103 but by Android device, its working perfectly.


What is the reason and where i am wrong?

**Comment by NomanJaved** [comment]
Hey I am getting this error message.
{jsonrpc: "2.0", error: {code: 102, message: "Failed to open output stream."}, id: "id"}

Also how can I change the directory path?

**Comment by nelwa** [comment]
> Hey I am getting this error message. {jsonrpc: "2.0", error: {code: 102, message: "Failed to open output stream."}, id: "id"}
> 
> Also how can I change the directory path? ![capture](https://user-images.githubusercontent.com/8793822/33394579-9a171bd8-d564-11e7-8b94-2279b8f2ad81.PNG)

Did you ever manage to solve this?  I'm getting this error suddenly out of the blue.
