### ISSUE TITLE
Request: Don't set Content-Type header unless not sent via up.settings.headers

### ISSUE THREAD

**Issue by kwentworth** [moxiecode/plupload#1203]
Rackspace CloudFiles, uses the Content-Type header to set the mime type on the file.  Can you please modify the code base to only send a Content-Type header if one isn't specified?  

Because you are using an XMLHttpRequest object, the Content-Type header gets concatenated, not replaced.

Something like:

``` javascript
// line 1476: 
// Set custom headers
                var contentType = false;
                plupload.each(up.settings.headers, function(value, name) {
                    if(name == 'Content-Type') {
                        contentType = true;
                    }
                    xhr.setRequestHeader(name, value);
                });

                if(!contentType) {
                    xhr.setRequestHeader('Content-Type', 'application/octet-stream'); // Binary stream header
                }
```

**Comment by jayarjo** [comment]
That makes sense. But are you sending files as binary streams?

**Comment by kwentworth** [comment]
I am sending binary, but CloudFiles appears to only want the single content-type header (image/jpeg, etc.)

**Comment by rek** [comment]
Did you find a solution to this?
