### ISSUE TITLE
the demo of UI Widget doesnt work in IE8

### ISSUE THREAD

**Issue by heeye** [moxiecode/plupload#1204]
the demo on the jsfiddle does not work in IE8...
(I save the "RESULT" as a html file and open it in IE8)
Just displayed " Your browser doesn't have Flash, Silverlight or HTML5 support. "

http://jsfiddle.net/gh/get/jquery/1.9.1/dependencies/ui/jayarjo/plupload-demos/tree/master/2.x/ui/bundled

**Comment by jayarjo** [comment]
jsFiddle itself stopped supporting IE8.

**Comment by heeye** [comment]
but if I deleted the part of submit function, it did work...

**Comment by jayarjo** [comment]
Does it work when you load bundled examples directly in IE8?

**Comment by heeye** [comment]
I downloaded the package again and load in IE8, neither does it.

**Comment by jayarjo** [comment]
It works here, so it should be something about your environment. Are you sure you actually have Silverlight or Flash installed in your IE8?

**Comment by heeye** [comment]
yeh, I'm pretty sure. not only mine, in my colleagues' laptops, didnt work too...so strange
