### ISSUE TITLE
License: GPLv2 only? or GPLv2 or later?

### ISSUE THREAD

**Issue by kijin** [moxiecode/plupload#1206]
I don't think this is a duplicate of #1086, so here's a new issue.

On the [License page](http://www.plupload.com/license/gplv2), you stated that you "decided to not use the GPLv3 license".

Could you clarify that a bit more?

Currently, there are 4 ways to put a GPL license on a program: (A) GPLv2 only, (B) GPLv2 or later, (C) GPLv3 only, and (D) GPLv3 or later. Since v3 is the latest version of GPL at this time, C and D are equivalent. It is also very clear that C and D have nothing to do with PLUpload, since you decided not to use GPLv3.

But what about A and B? Which one does PLUpload use?

A lot of GPLv2 programs use the following boilerplate in addition to the actual text of the license, as [recommended](https://www.gnu.org/licenses/gpl-2.0.html#SEC4) by the FSF. This makes them B (emphasis added):

> This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, _or (at your option) any later version._

But PLUpload does not use the standard boilerplate, so the above information is missing.

In the absence of that information, one must assume the more restrictive interpretation (A), and therefore I am unable to use PLUpload in a GPLv3 project of mine. Is that what you really intended, or was it just an oversight?

**Comment by Afraithe** [comment]
GPLv2 and only GPLv2 is the license of Plupload at this moment.

**Comment by jayarjo** [comment]
Open source license has been switched to [AGPLv3](http://www.plupload.com/license/agplv3).
