### ISSUE TITLE
Upload aborts on IE9

### ISSUE THREAD

**Issue by cskiwi** [moxiecode/plupload#1207]
hi,

so I implemented the plUpload.

on Chrome and FF it works great on hml5 runtime. but it has to support IE9, and then it uses Flash or Silverlight like it should.

But the fileupload are being aborted for some reason, while when I use FF with Silverlight, the upload just works like it should.

![image](https://cloud.githubusercontent.com/assets/847540/6331160/f49c0a22-bb7d-11e4-982e-903546152a80.png)

![image](https://cloud.githubusercontent.com/assets/847540/6331179/0f37a35a-bb7e-11e4-8340-19c228bcdc25.png)

**Same page on FF**

![image](https://cloud.githubusercontent.com/assets/847540/6331208/437ccafa-bb7e-11e4-8afc-70fed6d04221.png)

![image](https://cloud.githubusercontent.com/assets/847540/6331212/4feaa348-bb7e-11e4-9666-0d215c636628.png)

It says `No Content` but it works just fine
any clue why this is aborting?

**Comment by cskiwi** [comment]
Ok, found out the problem + sollution

Apparently IE doesn't like it if there is no reply, so by sending a 200 when the uploading is done, it works on every browser. so the `no Content` was the problem after all :p

**Comment by roman02** [comment]
@cskiwi So, no aborting happens?

**Comment by cskiwi** [comment]
@roman02 the abort only happens when the API doesn't respond.

**Comment by roman02** [comment]
@cskiwi Is sending a 200 something we all have to implement or is this supposed to be handled by the code provided by the plUpload devs?

**Comment by cskiwi** [comment]
If you don't send a reply you'll get an Abort on your call in IE9, so it's totally up to you to implement,
but the plugin has nothing to do with the error :)
