### ISSUE TITLE
Uploader elements inside container only necessary on some browsers

### ISSUE THREAD

**Issue by pncolvr** [moxiecode/plupload#1209]
I was using plupload to create a upload mechanism on a MVC site. It works wonderfully. :)
I tested on some desktop browsers (Chrome, Safari, Internet Explorer and Firefox) and it worked ok.
Currently I'm evolving the website to a responsive version, on Android it worked perfectly but on iOS I had an issue.
The issue was that the file picker UI was not shown (also no error message was available on the console), my uploader elements, file picker button and upload button, were outside of the container that I specified.
I think that the documentation should be updated so that developers are notified of this issue. I don't think that the documentation is clear enough on this aspect.

**Comment by jayarjo** [comment]
I do not immediately see how something like this could happen. It might have been an issue with 1.x version where we didn't set `container` implicitly, but in 2.x and up we automatically set container to the immediate parent of `browse_button` element. If for some reason it fails you have an option to specify container [manually](http://www.plupload.com/docs/v2/Options#container).
