### ISSUE TITLE
HTTP 200 Error On Sucessful File Upload

### ISSUE THREAD

**Issue by marcopolo8** [moxiecode/plupload#1211]
I installed Plupload (Core API), adjusted the necessary settings for the server (upload.php -- basically adjusted the path to upload, that's it) and when I go to upload files, they indeed get to the server but I'm returned "Error #-200: HTTP Error."
1. The files are getting to the server successfully
2. Permissions are set correctly on the destination directory
3. When I removed this line: rename("{$filePath}.part", $filePath); -- the .part file still gets to the server correctly and the returned error goes away.

Any reason why this would be happening? Any obvious things I should check? I've used this same basic Core API setup on a number of other instances, same server setup and this is the first I'm experiencing this problem.

Any tips are appreciated.

**Comment by fellu** [comment]
+1

**Comment by jayarjo** [comment]
I believe it has something to do with your upload handler and the response that it sends back to Plupload. Are you using our bundled `upload.php`? Have you modified it?
