### ISSUE TITLE
multi_selection=true, how to `CancelUpload` one of them, when they are in process.

### ISSUE THREAD

**Issue by icai** [moxiecode/plupload#1212]
function onError(up, err) {
		if (err.code === plupload.INIT_ERROR) {
			up.destroy();
		}
		// Set failed status if an error occured on a file
		else if (err.file) {
			err.file.status = plupload.FAILED;
			calcFile(err.file);

			// Upload next file but detach it from the error event
			// since other custom listeners might want to stop the queue
			if (up.state == plupload.STARTED) { // upload in progress
				up.trigger('CancelUpload');
				delay(function() {
					uploadNext.call(up);
				}, 1);
			}
		}
	}

do you provide some method like `trigger('Error')`?

**Comment by sambiomatters** [comment]
Uploader.trigger() it's in the api docs I believe

**Comment by jayarjo** [comment]
Do you want to cancel specific one, or what exactly is your question? `CancelUpload` will abort the upload.

**Comment by icai** [comment]
@jayarjo, yes.

---

@sambiomatters @jayarjo  I found that the solution on jqueryui plugin which use `removeFile`.
