### ISSUE TITLE
PLUpload is abandoned ?

### ISSUE THREAD

**Issue by JFOC** [moxiecode/plupload#1214]
No more development for Plupload?

**Comment by jayarjo** [comment]
Why this question? Is there something you want to be in Plupload, that is not already there?

We are working on html5 version only, that will probably have some other name.

**Comment by JFOC** [comment]
I just exciting to know about PLUpload roadmap in near future

**Comment by futureweb** [comment]
As we are in the process of choosing a new Uploader for our CMS which is used for hundreds of different Websites we also would be very interested in the Roadmap of this Uploader ... as we don't want to choose an apparent death project ...

**Comment by Daijobou** [comment]
"We are working on html5 version only, that will probably have some other name."

Cool! I'm very interessted in this new html5 only version. plupload ist great, but i missed some feature, like min/max width/heigth.

**Comment by jayarjo** [comment]
@Daijobou, min/max width/heigth?

**Comment by Daijobou** [comment]
A option to set a minimum resolution like 1280x200 and maximum resolution like 1920x200

**Comment by jayarjo** [comment]
Development is still going on, but much slower. Mostly bug fixes. There was an attempt to restructure Plupload in version 3. And bugfix release for it will be out next week.
