### ISSUE TITLE
Chunking does not work

### ISSUE THREAD

**Issue by kisenok1989** [moxiecode/plupload#1215]
When chunking is enabled, the post request is not sent at all. It just shows pending status until time limit is reached.
I tried to use Chrome, IE and Firefox. Everywhere I get the same issue.
![image](https://cloud.githubusercontent.com/assets/11529619/6700046/db78d9e0-cd10-11e4-95f1-dfad8c829953.png)
Maybe someone had the same problem?

**Comment by jayarjo** [comment]
Not a typical case, I'd say. [Fiddle](http://play.plupload.com) might help.
