### ISSUE TITLE
Documentation error? Sizes don't get parsed in File Filters examples

### ISSUE THREAD

**Issue by najamelan** [moxiecode/plupload#1217]
http://www.plupload.com/docs/File-Filters

In the real code, there is a line: `maxSize = plupload.parseSize(maxSize);` but in the filter examples in the documentation this line is missing creating the impression the parsing has already been done when the function receives the parameter `maxSize`. I don't understand how the minSize example would be able to function unless plupload had some code to detect sizes and parse them in the settings processing.

**Comment by jayarjo** [comment]
Fixed in the wiki: https://github.com/moxiecode/plupload/wiki/File-Filters. Website will update.
