### ISSUE TITLE
the html title modified

### ISSUE THREAD

**Issue by 270408722** [moxiecode/plupload#1226]
when the plug-in initialized on ie9,"#" is added after the html title;
when a file is added on ie9,the html title becomes "#"
give me a hand,thanks

**Comment by JohnRSim** [comment]
Any updates on this issue? 

Thanks
J.

**Comment by jayarjo** [comment]
Hm... I think I missed this one the first time.

**Comment by jayarjo** [comment]
@JohnRSim are you experiencing this issue too? I'm not able to repeat it. Could you post more details about your case?

**Comment by JohnRSim** [comment]
I can replicate this in IE9 or (IE9 mode with user agent Internet explorer 9) in IE11.

The Title changes to # for me.

If you replicate an anchor tag in IE - ie go here
http://www.plupload.com/examples/core/#

You will see the title changes to "Plupload: Core API#"
But when you select "Select Files" it changes to "#"

This is running the flash runtime.

J.

**Comment by jayarjo** [comment]
This seems to be some kind of IE + Flash bug, not Plupload related, but something global. You can try any page with flash movie on it, like [this one](https://www.adobe.com/devnet/video/articles/fmp_player/_jcr_content/articlecontentAdobe/videomodal_0.content.html#hjk) from adobe. Add a hash at the end before you paste in the url and then once it loads, simply click on the flash object.

Not sure what we can do about it. One workaround would be to restore original title once the object is focused. But not sure if messing with the title manually is the right thing.

**Comment by JohnRSim** [comment]
I can remove the # tag.. and change the anchor to a div to get around this issue :)
:+1:
