### ISSUE TITLE
How can i trigger plupload select dialog after page load automatically.

### ISSUE THREAD

**Issue by kesavankrishnan** [moxiecode/plupload#1227]
How can i trigger plupload select dialog after page load automatically.Its working fine when we click on button but i need to open after page load .

**Comment by comtronix** [comment]
That "add files" button is a flash button. So, you cant trigger it automatically simply, without tewaking that file. 

http://stackoverflow.com/questions/9210905/plupload-directly-open-dialog-on-instance
