### ISSUE TITLE
Resize not working on DPI over 1000

### ISSUE THREAD

**Issue by ymorin007** [moxiecode/plupload#1228]
When the image is over 1000 DPI the resize method wont work. Even if the image is bigger in width and height as setup.

**Comment by jayarjo** [comment]
There's artificial constraint in Plupload, which keeps it from trying to resize anything that is larger than 8192x8192 (on either side). This is basically done because if browser for some reason runs out of memory, we have no way to intercept that and throw a meaningful error.

**Comment by jayarjo** [comment]
Related: https://github.com/moxiecode/plupload/issues/1502
