### ISSUE TITLE
CDN hosting

### ISSUE THREAD

**Issue by ajitpawar** [moxiecode/plupload#1229]
Strictly speaking this is not an issue, so apologies.
Have you considered using a free CDN such as [cdnjs.com](https://cdnjs.com/). These guys host many libraries that Google and Microsoft don't.
Many of us run our apps on Heroku and serving files locally is slow. A CDN could help

**Comment by ajitpawar** [comment]
Just to add. cdnjs is hosted by Cloudflare

**Comment by jayarjo** [comment]
Looks like it's [already there](https://cdnjs.com/libraries/plupload), thanks.
