### ISSUE TITLE
bind() breaks unbind()

### ISSUE THREAD

**Issue by DanielWeiner** [moxiecode/plupload#1231]
`plupload.bind` calls `EventTarget.bind()` with a _different_ function than the one supplied by the user. This function is inaccessible. `unbind` and `removeEventListener` are rendered useless because of this.

**Comment by DanielWeiner** [comment]
https://github.com/moxiecode/plupload/blob/master/src/plupload.js#L1877

**Comment by jayarjo** [comment]
Might have been problem at the moment, but definitely is not anymore.
