### ISSUE TITLE
File extension filters don't apply in Internet Explorer 10 & 11 file boxes with HTML5 uploader

### ISSUE THREAD

**Issue by joebtron** [moxiecode/plupload#1238]
Hi, 

Thanks for making such a fully featured uploader. Unfortunately I've found that with the HTML5 uploader IE10 & IE11 don't filter files in the file box by the extensions you specify. The extension error event is triggered when selecting the wrong file type though and IE8 & 9 work fine with the flash uploader.

Is there a way to fix this? I've searched the issues to no avail.

Thanks

**Comment by aik099** [comment]
Maybe it is a browser bug? Does filtering work if you just create HTML5 <input type="file"/> with mime types specified?

**Comment by joebtron** [comment]
Doesn't seem to be. For instance, this allows fiddle allows me to select only image files in ie11 https://jsfiddle.net/hng7ronk/

**Comment by joebtron** [comment]
Seems like it might be down to the mime type you specify, I'm trying ppt. Trying a few from here https://msdn.microsoft.com/en-us/library/ms775147%28v=vs.85%29.aspx it seems IE is picky as to which mime types it will filter by.

**Comment by jayarjo** [comment]
We have mime types for ppt in our internal registry. Seems to work here: http://play.plupload.com/0__J_/
