### ISSUE TITLE
Appending input fields after files have been added in UI widget

### ISSUE THREAD

**Issue by wdmtech** [moxiecode/plupload#1239]
I'm trying to hook into the UI widget to add form input fields after a user has added a file, so they may enter information about the file before it is uploaded. It seems the HTML is rendered AFTER the file has been added ("FilesAdded" event), so I cannot therefore modify the output in, for example, the following element:

``` HTML
<div class="plupload_file_name">
    <span>10MB.zip</span>
</div>
```

... to be more like the following:

``` HTML
<div class="plupload_file_name">
    <span>
        <input type="text">10MB.zip</input>
    </span>
</div>
```

Any ideas?

**Comment by aik099** [comment]
You can render elements in queue yourself and when file is added to the queue you provide complete HTML, including upload progress bar, yourself.

**Comment by wdmtech** [comment]
Thanks @aik099, I've opted for the following, which involves adding a custom bind event 'AfterFilesAdded' and calling that in the 'FilesAdded' event as such:

```JS
uploader.bind('AfterFilesAdded', function (up, file) { ... }

uploader.bind('FilesAdded', function (up, file, info) {

    file.forEach(function( file ) {
        uploader.trigger('AfterFilesAdded', this, file);
    });

});
```

**Comment by wdmtech** [comment]
Turns out this doesn't work either - i'm merely extending the FilesAdded event here, so therefore never get access to the rendered elements I want to append the inputs to as they haven't been created yet.

**Comment by wdmtech** [comment]
@aik099, would you mind elaborating where I would add my rendered elements? Essentially, this is what I'm trying to end up with:

![capture](https://cloud.githubusercontent.com/assets/7282262/7562038/f6e8f902-f7c8-11e4-81c6-d1f0e1939bb4.PNG)

**Comment by aik099** [comment]
Since you're obviously (based on screenshot) using queue plugin, then I recommend looking at what events it uses to render UI. Then you can either extend that plugin (I don't know if it's possible) or just copy-paste and add your code where you need it.

What I think is happening is that plugin is either using different events or your event handler is executed before plugin one does and therefore yours have no effect because plugin replaces HTML completely.

**Comment by momer79** [comment]
any luck?

**Comment by momer79** [comment]
i am trying to achieve the same thing with plupload but input control doesn't retain values after adding second file.

**Comment by jayarjo** [comment]
List of files and inputs is redrawn after each `QueueChange`, so one would need to add those custom fields again and again.I would suggest to hook onto `BeforeUpload` and use [multipart_params](https://github.com/moxiecode/plupload/wiki/Options#multipart_params) to send additional fields with every upload.
