### ISSUE TITLE
SyntaxError: missing } after property list in v2.1.3

### ISSUE THREAD

**Issue by comtronix** [moxiecode/plupload#1240]
SyntaxError: missing } after property list
jquery.ui.plupload.js
Line 1056

https://github.com/moxiecode/plupload/releases/tag/v2.1.3

**Comment by comtronix** [comment]
it's in the downloaded zipfile  jquery.ui.plupload.js
![knipsel](https://cloud.githubusercontent.com/assets/3840400/7575477/546adf98-f835-11e4-8ad7-b347208c121e.PNG)

**Comment by jayarjo** [comment]
Strange it doesn't appear here and neither does affect anything, even in IEs. How did you extract the zipball, and what is the platform and browser where you get the error?

**Comment by jayarjo** [comment]
#1113.

**Comment by comtronix** [comment]
extract with 7zip. Windows 8, FF. #113 is the same error/character.
