### ISSUE TITLE
when file add could get sha1 ?

### ISSUE THREAD

**Issue by ghost** [moxiecode/plupload#1241]

**Comment by aik099** [comment]
What you mean? You want to get SHA1 of uploaded file before or after upload is happened? What's your usecase?

**Comment by taijisun** [comment]
before

**Comment by taijisun** [comment]
for check this file is exists.

**Comment by aik099** [comment]
So you want to prevent user from uploading file if it was already uploaded. I guess you can use HTML5 FileApi to do that stuff manually and then send an AJAX request to server to confirm that file exists.

**Comment by taijisun** [comment]
thank you , i will try

**Comment by eyong4736** [comment]
Can I get the file's SHA1 before uploading in IE ?

**Comment by jayarjo** [comment]
It's not about IE, it's about whether the browser (can be any model, and variety of versions) support File API (FileReader specifically).

**Comment by jayarjo** [comment]
Closing this, since it is more of generic question rather than an issue report.
