### ISSUE TITLE
Responsive Design Issue - Shim Positioning

### ISSUE THREAD

**Issue by Jak893** [moxiecode/plupload#1244]
Hi,

I've been trying to resolve an issue with plupload for a few days now and it seems everything I try has led me to a dead end so hopefully I can either get this logged as a bug, or someone might have had similar issues before and can offer some advice.

At the moment, jsFiddle also seems to be down so I can't produce a fiddle of this yet, so I will attempt to convey the issue with code snippets and images until I can get a fiddle made up.

        <div class="row">
            <div id="plupload-container" class="col-xs-12">
                <div id="upload-container">
                    <div id="drop-target">
                    </div><div id="table-container">
                        <table id="fileList">
                            <tbody id="fileNodeList"></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

I have a very rough HTML layout above which, when rendered, produces something like img1.png. Note the position of the html5 shim, this works fine for desktops as the user can click on the right hand white box and the file picker is displayed, like-wise, files can be dropped on there and are added to the upload queue.

Now, when I use Chrome Dev Tools, or even actual Android, WP8 and iOS devices and attempt to view the page, the file browser is seemingly broken. When I take a look at the elements on the page, img2.png, it seems that the SHIM has been enlarged and placed erroneously within the DOM, knowing this, I can click on the file list div and the file browser appears....this seems like very odd behavior to me.

    var uploader = new plupload.Uploader({
            runtimes: 'html5, flash',
            browse_button: 'drop-target',
            drop_element: 'drop-target',
            container: 'plupload-container', //Have also tried using 'upload-container' and removing the     container option completely
            url: '@ViewBag.UploadUrl',
            chunk_size: '5mb',
            unique_names: true,
            filters: {
                max_file_size: '@ViewBag.MaxFileSize',
                mime_types: @Html.Raw(ViewBag.PermittedExtensions),
                excluded_extensions: @Html.Raw(ViewBag.ExcludedExtensions),
                min_file_size: "0Mb"
            }

You can see above I have attempted to specify numerous elements to act as the container so that when viewed on a mobile device, the uploader will function correctly but to no avail. Also worth noting, when I set the container to also be 'drop-target', it does control the movement of the SHIM to an extent, but the flipside is that intermittently, the uploader will become completely dysfunctional, plupload will initialize but clicking on the browse element or even dropping files on it results in nothing at all.

Once jsFiddle is up, I will attempt to create an example showing this problem.

Has anyone come across something like this before who might be able to shed some light on the issue?

![img1](https://cloud.githubusercontent.com/assets/664193/7656040/dfa0a0e2-fb1f-11e4-90c8-ca375a65893f.png)
![img2](https://cloud.githubusercontent.com/assets/664193/7656081/1dc1204a-fb20-11e4-81ef-ccac15df194c.png)

**Comment by Jak893** [comment]
A current example can be seen here http://codepen.io/anon/pen/LVNwgd you'll have to run this locally as CodePen doesn't currently allow the viewing of mobile styled content.

Doing some digging, I've got an almost fix by hooking into the jQuery window resize event and calling uploader.refresh(), this is probably a bit over kill but seems to be the closest to a solution....but not quite!

    $( window ).resize(function() {
      uploader.refresh();
    });

The issue seems to be that when the page is loaded in the mobile responsive view, the uploader needs to be refreshed to assume the correct positioning in the page, but since the window isn't being resized when Bootstrap is adjusting the content, then the above method fails.

My next step was try calling the refresh method on the window.load() or document.ready() events but again neither of those two have had any impact. I get the feeling the issue is so simple to solve, but the answer is just out of reach.

**Comment by jayarjo** [comment]
If you have container for the Plupload resizing or the browse button moves within that container for some other reason, you will have to call `uploader.refresh()` after each movement. That's what it was created for in first place. It's not an overkill, what it does is just reposition and resize Plupload shim to match the browse button again.

There's only way you can avoid calling `uploader.refresh()` - that would be by placing browse button to a container that doesn't stretch in any way. It can float within a document in are responsive way, but it should retain dimensions. That would be it. But if you require to have a browse button that resizes with the layout, there is no way you can ask Plupload to resize automatically, unless you put `uploader.refresh()` in the handler for the resize event.
