### ISSUE TITLE
Preview images got rotated

### ISSUE THREAD

**Issue by hujunyi** [moxiecode/plupload#1245]
I read this post  http://www.bennadel.com/blog/2563-showing-plupload-image-previews-using-base64-encoded-data-urls.htm and use the way mentioned to preview image. The images uploaded to the server are ok. But for some images, they got rotated by 90deg if I preview them using Base64 Data Url.

**Comment by jayarjo** [comment]
It means those images contain Orientation tag, that gets stripped for thumbnails (we are trying to generate them as fast as possible). And they are not visually adjusted anymore. 

This is expected behaviour.
