### ISSUE TITLE
plupload 2.1.3 bug  : file browser shows up two times on chrome and safari

### ISSUE THREAD

**Issue by zbexworld** [moxiecode/plupload#1246]
when i try to upload a file on chrome  the file browser window shows up twice , but in firefox it works fine  sorry i was so stressed to the point that i forgot to include the code.
NB :  i use it in conjunction with Angular js

app.directive('uploadFile', function() {

    return {

        // Restrict it to be an attribute in this case

        restrict: 'A',

        // responsible for registering DOM listeners as well as updating the DOM

        link: function(scope, element, attrs) {

          console.log(element);

          var uploader = new plupload.Uploader({

                      runtimes : 'html5,flash,silverlight,html4',

                     

                      browse_button : 'parcourirProfilPic', // you can pass in id...

                       

                      url : "/examples/upload",

                       

                      filters : {

                          max_file_size : '10mb',

                          mime_types: [

                              {title : "Image files", extensions : "jpg,gif,png"},

                              {title : "Zip files", extensions : "zip"}

                          ]

                      },

                   

                   

                      init: {

                      Error: function(error) {

                          console.log(error.code);

                          },

                         

                      Browse: function() {

                          console.log("browse");

                          },

                          FilesAdded: function(up, files) {

                          var imgContainer = $(".profilPicWrapper");

                      var image = $( new Image() ).appendTo( imgContainer );

                            var preloader = new mOxie.Image();

                  preloader.onerror = function (error, error1, error2, error3) {

                  console.log(error);

          };

                  preloader.onload = function() {

                    console.log("loooad");

                    image.prop( "src", preloader.getAsDataURL() );

                  };

                  preloader.load( files[0].getSource() );

                          },

                      }

                  });

          function handlePlUploadFilesAdded( uploader, files ) {

            console.log( uploader.id );
            // Show the client-side preview using the loaded File.

            showImagePreview( files[ 0 ] );
            uploader.start();
          }
          function showImagePreview( file ) {

                //var item = $( "<li></li>" ).prependTo( dom.uploads );
                var imgContainer = $(".profilPicWrapper");
                var image = $( new Image() ).appendTo( imgContainer );
                var preloader = new Moxie.Image();

                preloader.onerror = function (error, error1, error2, error3) {

                console.log(error);

        };
                preloader.onload = function() {
                    image.prop( "src", preloader.getAsDataURL() );
                };
                preloader.load( file.getSource() );

          }
          uploader.init();
        }

    };

**Comment by jayarjo** [comment]
That's not a case in general can you describe your scenario in more details? And provide a config maybe.

**Comment by jayarjo** [comment]
It is not exactly clear from your excerpt how Plupload is instantiated. Make sure that you are not instantiating it twice for the same `browse_button`, inspect the DOM from developer tools for example.
