### ISSUE TITLE
Reset function for pluploader

### ISSUE THREAD

**Issue by srees** [moxiecode/plupload#1247]
I'd like to see a method to handle resetting the uploader state after an upload is complete, so that the queue can be modified and more files added.

The use case:
In our Drupal 6 installation, we've tied in clam-AV to the upload process so that an error is thrown during the processing if there is a virus. I'm trapping this error by binding to pluploadQueue's FileUploaded function. It's straightforward enough to yank the infected file from the queue, but I'd like a way to reset the interface so that the user can add another file at that point. I've tried following other suggestions to adjust the visibility of the buttons, but then the 'Add Files' button no longer launches the file dialog box, and if I manage to force it, I get errors - indicating I'm missing something in resetting the uploader.

**Comment by jayarjo** [comment]
You can use [uploader.splice()](https://github.com/moxiecode/plupload/wiki/Uploader#splice-method-start0length) method to clear the whole queue.

**Comment by ivohelloween** [comment]
FileUploaded: (up, files, info) =>
  files.status = plupload.UPLOADING;
  up.trigger('UploadFile', files);
