### ISSUE TITLE
plupload.Uploader refuses to be destroyed

### ISSUE THREAD

**Issue by Radagaisus** [moxiecode/plupload#1249]
![screen shot 2015-05-24 at 06 41 59](https://cloud.githubusercontent.com/assets/550061/7786561/04a949b8-01e0-11e5-95e7-1d1e1375cb7d.png)

**Comment by jayarjo** [comment]
`pluploader.destroy()` simply removes associated html structures and internal references, so that object can be garbage collected when not required anymore.

And where this idea even comes from? I do not see how this can be done from inside of uploader object anyway.

**Comment by Radagaisus** [comment]
@jayarjo Maybe the screenshot was not a great example of what I tried to convey. Basically, I have a pluploader on the page that I destroy and re-initialize whenever the view is re-rendered, but some uncanny reason, `.destroy()` does not stop it from binding events, nor does `.unbindAll()`.
