### ISSUE TITLE
CMYK image lost jpeg data

### ISSUE THREAD

**Issue by makwanaajay** [moxiecode/plupload#1251]
I have converted the RGB jpeg image into CMYK and upload it through the plupload. But after uploading the image, when I am trying to open the uploaded image with the Photoshop, it shows the error that problem parsing JPEG data and not able to open it with photoshop.
Please find the below attach image which is converted into CMYK from RGB.
![o_19m800epi19h5cq1fbq4o95rlp](https://cloud.githubusercontent.com/assets/12611858/7814404/92a8c6e8-03df-11e5-97f9-e5ee008685a0.jpg)
Please provide me the reason or solution for this. It is very urgent for me.

**Comment by aik099** [comment]
1. Have you compared original image (that you're uploading) VS one that were saved on web server by plupload (e.g. size match, content match)?
2. What if you repeat upload image again you get same problem?
3. Does uploading image on the demo site of Plupload work?

**Comment by makwanaajay** [comment]
(1) Dimensions are same and small increased in size
(2)Same issue
(3)No, I have upload it my application

I have uploaded it through another application like flash uploader and there is no any issue with that.
Please provide me the solution. Thanks for your quick response and support.

**Comment by aik099** [comment]
> (3)No, I have upload it my application

This means, that you're able to upload that CMYK file on Plupload demo website and all was fine. But you're not able to do so on your website.

This means, that an equivalent of `upload.php` file from demo website that is getting your file from browser (even when doing chunked upload) isn't assembling them back right or doing some kind of transformation (e.g. resizing) along the way, that breaks it.

These should be no size/content change for file saved on web server vs file you're selected for upload on your computer.

**Comment by makwanaajay** [comment]
So what is the solution. How can i upload the image without chunk and with full image data and information?

**Comment by aik099** [comment]
From what I understand there is something in your Plupload configuration that results in an error. Could you please post JS code used to initialize Plupload.

**Comment by jayarjo** [comment]
There are two cases when something might happen to your image file on the way to server:

1. If you are using chunking and as @aik099 mentioned not reassembling the file back properly.
2. If you have a `resize` option enabled in your configuration - then depending on the settings that you have there, Plupload might attempt to strip the meta headers off.

In all other cases your file should travel over intact. Post your config if you want us to troubleshott this further.

**Comment by makwanaajay** [comment]
Below are the configuration.
container : 'windows',
		runtimes : 'html5',
		url : jspath+'plupload/upload.php',
		unique_names: true,
		// User can upload no more then 20 files in one go (sets multiple_queues to false)
		max_file_count: 20,
		
		chunk_size: '1mb',
		resize: false,
		multipart_params : {
			"isFront" : isFront,
			"isUpload" : 1,
			"toolType" : toolType,
		},

**Comment by jayarjo** [comment]
Does it fix itself if you remove `chunk_size: '1mb'`?

**Comment by jayarjo** [comment]
@makwanaajay, I cannot open that image in Photoshop neither after, nor before the upload. Apparently Plupload doesn't have anything to do with the error.

Closing this. Feel free to reopen if you have more details to share.
