### ISSUE TITLE
Plupload 2.1.4: Select files button doesn't work when it is inside a jquery 

### ISSUE THREAD

**Issue by BabuSujith** [moxiecode/plupload#1254]
Plupload: Select files button doesn't work when it is inside a jquery modal in ipad

Hi I am using Plupload for uploading images in my application. And it's working fine in IE, chrome and firefox etc. But when I test my application in Ipad safari, "Add Files" button is not triggering. But in Ipad, if I use chrome as my browser, it's working. I am using a jquery modal pop-up to show the plupload widget (the jquery modal poup up will appear when I click "Upload Images" button from my application. 

I tried to refresh the upload after you open the dialog, but still it's not working

Do I need to do any additional code. Please advise

Code:
    function fnOpenUploadPopUp(val, msg) {
        $("#DocType").val(val);
        $('#HeaderMessage').html(msg);
        $("#dialog-upload").dialog("open");
        $('#uploader').plupload('refresh');
    } 

Plupload initializing
------------------------------

@*<div id="dialog-upload">
    <div id="UserMessage"></div>
    <span id="boxMI"></span>
    <table style="border: 5px solid #ededed;">
        <tbody>
            <tr class="upld_section">
                <td class="upload-tabs-rt">

                    <div class="examples examples-ui" id="up-ui">
                        <section id="content">
                            <div class="container">
                                <div id="example">
                                    <div id="uploader">
                                        <p>Your browser doesn't have Flash, Silverlight or HTML5 support.</p>
                                    </div>
                                    <script type="text/javascript">
                    // Initialize the widget when the DOM is ready
                    $(function () {
                        var ETA = 0;
                        var count = 1;
                        var index = 0;
                        var text = "";
                        var regex = /(?:\.([^.]+))?$/;
                        var datetime = @DateTime.Now.ToString("MMddyyyyhhmmss") + '';

                        $("#uploader").plupload({
                            // General settings
                            runtimes: 'html5,flash,silverlight,html4',
                            url: "@Url.Action("UploadToDocVault", "healthrecord", new { area = "", id = Model.Patient.PersonId }, true)",
                            // Maximum file size
                            max_file_size: '1000mb',
                            chunk_size: '200mb',
                            max_retries: 3,
                            // Rename files by clicking on their titles
                            rename: true,
                            // Sort files
                            sortable: true,
                            // Enable ability to drag'n'drop files onto the widget (currently only HTML5 supports that)
                            dragdrop: true,
                            // Views to activate
                            views: {
                                list: true,
                                thumbs: true, // Show thumbs
                                active: 'thumbs'
                            },
                            multiple_queues: true,
                            multipart: true,
                            multipart_params: { taskId: '' },
                            rename: true,

                            preinit: {
                                FilesAdded: function (up, files) {
                                    if ($('#DocType').val() == 0) {
                                        $('#DocType').val(5);
                                    }
                                    var i = 0;
                                    $.each(files, function (i, file) {
                                        //if ($('#DocType').val() == 5) {
                                        var name = file.name.substr(0, file.name.lastIndexOf('.')) || file.name;
                                        var ext = regex.exec(file.name)[1];
                                        //var fName = name + count + '_' + i;
                                        var fName = name + '_' + datetime + count + i;
                                        file.name = (ext == undefined) ? fName : fName + '.' + ext;
                                        //}
                                        file.name = file.name + '|' + $('#DocType').val() + ":" + count;

                                        //for imaging just show only one file and hide all others
                                        if (i > 0 && $('#DocType').val() == 5) {
                                            $('#' + file.id).hide();
                                        }
                                        i = i + 1;
                                    });
                                    count = count + 1;
                                },
                                UploadProgress: function (up, file) {
                                    if (up.total.bytesPerSec > 0) {
                                        var time_left_seconds_overall = Math.round((up.total.size - up.total.loaded) / up.total.bytesPerSec);
                                        ETA = time(time_left_seconds_overall);
                                    } else {
                                        ETA = 0.1;
                                    }

                                    var msg = '<div class="box info noicon" id="info">' +
                                                '<span style="position: relative;bottom:8px;">Your file(s) are being uploaded. Please wait...</span>' +
                                                '&nbsp;&nbsp;<img src="@Url.Content("~/content/images/Spinner.gif")" />';
                                    msg = msg + '&nbsp;&nbsp;<span style="position: relative;bottom:8px;">Estimated time: ' + ETA + '</span>';
                                    msg = msg + '<div class="close" onclick="fnClose()" id="btnclose">X</div></div>';
                                    $("#UserMessage").empty();
                                    $("#UserMessage").css("display", "block");
                                    $('#UserMessage').html(msg);
                                },
                                FileUploaded: function (up, file, response) {
                                    var fileName = file.name.split('|')[0];
                                    var docType = file.name.split('|')[1].split(':')[0];
                                    var ident = file.name.split('|')[1].split(':')[1];
                                    if (docType == 5 && index != ident) {
                                        text = '@DateTime.Now.ToString("yyyyMMddHHmmss")' + ident;
                                        index = ident;
                                    }

                                    $.ajax({
                                        url: '@Url.Action("InsertMedicalDoc", "healthrecord", new { area = "", id = Model.Patient.PersonId }, true)',
                                        data: "{ 'filename': '" + fileName + "','docType': '" + docType + "','text': '" + text + "' }",
                                        type: 'POST',
                                        dataType: "json",
                                        contentType: 'application/json; charset=utf-8'
                                    });
                                    keepSignedIn(false);
                                },
                                UploadComplete: function (up, files) {
                                    if (up.files.length == (up.total.uploaded + up.total.failed) && up.total.uploaded > 0) {
                                        $("#UserMessage").empty();
                                        $("#UserMessage").css("display", "block");
                                        $('#UserMessage').html('<div class="box warning gn-icon gn-icon-warning" id="warning1">' +
                                                                'Please wait while we process your record(s). Dont refresh the page, this may take some time.' +
                                                                '</div>');
                                        $.ajax({
                                            url: '@Url.Action("CompleteUploadProcess", "healthrecord", new { area = "", id = Model.Patient.PersonId }, true)',
                                            type: 'GET',
                                            contentType: 'application/json; charset=utf-8',
                                            success: function (data) {
                                                $('#placeHolder').empty();
                                                $('#placeHolder').html(data);
                                                $("#UserMessage").empty();
                                                $("#UserMessage").css("display", "block");
                                                $('#UserMessage').html('<div class="box success" id="success">' +
                                                                        '<div class="gn-icon gn-icon-thumbsup">Your file(s) have been successfully uploaded.' +
                                                                        '<div class="close" onclick="fnClose()" id="btnclose">X</div></div>');
                                                document.getElementById("med_rec_vault").style.display = "block";
                                                scrollTo(0);
                                                setArrows();
                                            },
                                            error: function (response) {
                                                $("#UserMessage").empty();
                                                $("#UserMessage").css("display", "block");
                                                $('#UserMessage').html('<div class="box error" id="error">' +
                                                                        '<div class="gn-icon gn-icon-close">Oops, something went wrong. Please try again later or contact support@secondopinionexpert.com.' +
                                                                        '<div class="close" onclick="fnClose()" id="btnclose">X</div></div>');
                                                setArrows();
                                            }
                                        });
                                        $.each(files, function (i, file) {
                                            $('#' + file.id).remove();
                                        });
                                        up.splice();
                                        up.refresh();
                                    }
                                }
                            },
                            error: function () {

                            },
                            stop: function () {
                                fnAjaxBegin('Cancel Upload in progress...');
                                $("#UserMessage").empty();
                                $("#UserMessage").css("display", "none");
                                $.ajax({
                                    url: '@Url.Action("CancelMedicalDocs", "healthrecord", new { area = "", id = Model.Patient.PersonId }, true)',
                                    data: "{ 'healthProfile': '" + @Model.FromHealthProfile + "' }",
                                    type: 'POST',
                                    dataType: "json",
                                    contentType: 'application/json; charset=utf-8',
                                    success: function (result) {
                                        if (typeof (result.url) != 'undefined') {
                                            hidelAll();
                                            window.location.href = result.url;
                                            showSuccess('Upload cancelled.');
                                        }
                                        setArrows();
                                    },
                                    error: function (response) {
                                        hideBusyBarOvrly();
                                        hideBusyBar();
                                        setArrows();
                                    }
                                });
                            }
                        });
                        //$('#uploader').plupload('refresh');
                        //$('#uploader > div.plupload browse_button').css('z-index', '99999!important');
                    });
                                    </script>
                                </div>
                            </div>
                        </section>
                    </div>

                </td>
            </tr>
        </tbody>
    </table>
</div>*@

**Comment by Daijobou** [comment]
I have maybe the same problem.

Plupload version 2.1.3 working fine, but upgrade to 2.1.4 (nothing changed) all buttons not working anymore. But that problem is (only) in firefox? chrome working fine.

**Comment by BabuSujith** [comment]
Same here also. Everything works fine before I upgrade to 2.1.4. The issue is only in Firefox.

**Comment by jayarjo** [comment]
You should call `refresh` only after the dialog is shown, otherwise it's useless. Attach an event lister to the [open](http://api.jqueryui.com/dialog/#event-open) event of UI Dialog and call `refresh` from there.

**Comment by jayarjo** [comment]
Also is there any reason to mix regular and UI Widget style event listeners, like you do in your sample?

**Comment by BabuSujith** [comment]
Thanks for your reply. Its working perfect now. Included some styles to handle custom messages/ warnings as popup.

**Comment by jayarjo** [comment]
[2.1.5](https://github.com/moxiecode/plupload/releases/tag/v2.1.5) is out now. Upgrade recommended.
