### ISSUE TITLE
moxie.js 1.3: Drag and drop not working in IE 10+

### ISSUE THREAD

**Issue by fricca** [moxiecode/plupload#1255]
In Plupload 2.1.4 which uses moxie.js 1.3, drag&drop no longer works in IE10+. The examples at http://www.plupload.com/examples/ are broken except the last one http://www.plupload.com/examples/events which somehow seems to use 1.2.1 (*)

I think the culprit is `o.Env.version` returning `NaN`.
moxie.js 1.3, line 1141:

    version: parseFloat(UAParser.browser.major),
should be

    version: parseFloat(UAParser.browser.version),
because in `regexes.browser` there's no `MAJOR` any more.
The test in line 6219

    return (('draggable' in div) || ('ondragstart' in div && 'ondrop' in div)) && (Env.browser !== 'IE' || Env.version > 9);
 fails in IE 10 and 11 and the drag&drop feature isn't initialized.

(*)
plupload.full.min.js is included twice:
http://www.plupload.com/plupload/js/plupload.full.min.js
and in the source area:
http://rawgit.com/moxiecode/plupload/master/js/plupload.full.min.js
Might be by accident because the html entites aren't escaped?

**Comment by aik099** [comment]
What is `UAParser.browser` and how come it had `.major` property before but no more? Could you please send a PR with a fix?

**Comment by fricca** [comment]
> What is UAParser.browser 

It's the browser sniffing part done by regexes, line 898 ff. in moxie.js 1.3

> and how come it had .major property before but no more?

No idea, why it was changed.
In 1.2.1 (line 950 ff.) `regexes.browser` had [NAME, VERSION, MAJOR], in 1.3 (line 711 ff) there's only [NAME, VERSION]

> Could you please send a PR with a fix?

To be honest, I'm not familiar with doing Pull Requests and don't have the time to learn that ATM for the change of one word, sorry.

**Comment by aik099** [comment]
It's pretty easy in fact for such small change. You just do this:

1. open a file on GitHub
2. click on pencil icon in top right corner to edit (it will say, that you're not repo owner and it will be forked to you)
3. now you see file in editor
4. make necessary change
5. click save or send PR button somewhere on the page

**Comment by fricca** [comment]
Thank you! Following these steps was pretty easy indeed. :)

**Comment by jayarjo** [comment]
Fix has been incorporated into: https://github.com/moxiecode/moxie/commit/3b925d07fbdb9b10a280ff1b04bd03d5b3a9e5a5. Thanks @fricca.
