### ISSUE TITLE
Is HTML4 runtime still supported?

### ISSUE THREAD

**Issue by dovp** [moxiecode/plupload#1258]
Hello,
I'm trying to make plupload work on IE9.

I took the current example (https://github.com/moxiecode/plupload/blob/master/examples/custom.html), and it seems like only flash works.
When flash is within the runtimes parameter (of Uploaded initialization) everything works (via the flash), but when I keep only the html4 it doesn't work.
It doesn't work in a way that the file's size is zero, and The server gets an empty data (and fails).

What am I missing here? and if it is not supported, the example should not contains the html4 inside the runtimes parameter...

**Comment by jayarjo** [comment]
HTML4 is still supported and example that you mention is functional. While file size is not available in HTML4 inside IE9, upload should just work. It works in our unit tests. 

If you still experience this issues please provide more details, the config (in case you changed it), upload handler (if its different from bundled `upload.php`) and the file that gets uploaded empty.

**Comment by dovp** [comment]
Thanks.

I have two questions regarding HTML4:
1) Does it support slicing (chunking)? According to the following link I see it's not: http://www.plupload.com/docs/Required-Features
If it's not supported, the only way to send it with chunks is to implement something on my own?
2) Is it mandatory to use multipart in HTML4?

**Comment by jayarjo** [comment]
HTML4 is there only as last resort. It doesn't support chunking and yes - it can only send multipart. If you require these, you simply shouldn't use HTML4. Rely on HTML5, Silverlight and Flash.

In case you do not need to support legacy browsers simply use HTML5 only and you will have it all.
