### ISSUE TITLE
Broken filter mime_type 

### ISSUE THREAD

**Issue by skylinex** [moxiecode/plupload#1259]
Filter mime_type is probably broken in v.2.1.5. It alerts wrong file format, even it if it is right. (On Chrome 43.0.2357.125 (64-bit))
```js
filters: {
    max_file_size: '20mb',
    mime_types: [
        {title: "Image files", extensions: "jpg,png"}
    ]
},
```
Above options worked well on v.2.1.4.

**Comment by Nikoms** [comment]
Same here

**Comment by jayarjo** [comment]
Try: [2.1.6](https://github.com/moxiecode/plupload/releases/tag/v2.1.6).
