### ISSUE TITLE
2.1.5: Drag and Drop not working in IE10

### ISSUE THREAD

**Issue by fricca** [moxiecode/plupload#1262]
In 2.1.4, drag&drop in IE10+ didn't work because of issue #1255.

In 2.1.5, IE10+ is recognized as "drag &and drop able" again, but when you drop files into the container, it doesn't work.

When I revert the changes done in moxie.js, commit d2c1daa5a in function each(), (hunks from [line 175 ff.](https://github.com/moxiecode/plupload/commit/d2c1daa5a34e94c83aae3ffe5b5d09ed127382ef#diff-b139402807a10b7204d3958e3151eec3L175) and [190 ff.](https://github.com/moxiecode/plupload/commit/d2c1daa5a34e94c83aae3ffe5b5d09ed127382ef#diff-b139402807a10b7204d3958e3151eec3L190)), it works in IE10+ again. (Didn't debug any further.)

**Comment by jayarjo** [comment]
Yes, seems like the fix for `each()` method actually killed it. Made a fix here: https://github.com/moxiecode/moxie/commit/40f9e1684339ebc18ff0731793014700c5a1f9d5.

**Comment by fricca** [comment]
I tested the latest changes in moxie,js (including [https://github.com/moxiecode/moxie/commit/354605816f987e3a6e33cc1c956fc27d9b1909c6]) with plupload v2.1.5 and it looks good so far. Drag & drop in IE10+ is working again. :)

**Comment by jayarjo** [comment]
Here: https://github.com/moxiecode/plupload/releases/tag/v2.1.6.
