### ISSUE TITLE
Error Thumbnail: "urlp is undefined" 2.1.6

### ISSUE THREAD

**Issue by nebrot** [moxiecode/plupload#1264]
After selecting an image there is no thumbnail because of an error:

![plupload](https://cloud.githubusercontent.com/assets/6941112/8455507/68737b38-2005-11e5-85d1-1bdfbabba4c2.png)

Version: 2.1.6 + UI Widget
Runtime: HTML5
Browser: Firefox 38, Chrome 43

This was working in 2.1.2! Perhaps error was introduced here: https://github.com/moxiecode/moxie/pull/127 ?

**Comment by jayarjo** [comment]
Image selection wouldn't be a typical trigger for this. Can you post your config?

**Comment by nebrot** [comment]
In file-dialog-window i selected one image and after that i clicked on the button "Öffnen" (Open/OK?) (language specific), so that the file was added to the view. The script failed to generate a thumbnail (see error above).

```
var _app_uploadanzahl = 0;
var _app_uploadcompleted = false;

$("#uploaderdatei").plupload(
{
	runtimes: "html5,flash",
	url: "/fileadmin/" + _app_prefix_ordner + "/upload.php?sessionid=" + $("#f_sessionid").val() + "&sid=" + parseInt($("#f_sid").val(), 10),
	flash_swf_url: "/fileadmin/" + _app_prefix_ordner  + "/lib/plupload/Moxie.swf",
	max_file_size: "50mb",
	multi_selection: false,
	autostart: false,
	sortable: true,
	dragdrop: false,
	prevent_duplicates: true,
	rename: false,
	thumb_width: 150,
	thumb_height: 90,
	filters: 
	[
		{title : "Bilder", extensions : "bmp,jpg,jpeg,gif,png"},
		{title : "Videos", extensions : "mp4"},
		{title : "Dokumente", extensions : "pdf,doc,docx,xls,xlsx,ppt,pptx,pps,ppsx,odf,odg,odp,ods,odt"}
	],
	buttons:
	{
		browse: true,
		start: true,
		stop: false
	},
	views: 
	{
		list: false,
		thumbs: true,
		active: 'thumbs'
	}
});


$("#uploaderdatei").on("uploaded", function(up, files)
{
	_app_uploadanzahl++;
});


$("#uploaderdatei").on("complete", function(up, files)
{
	_app_uploadcompleted = true;
	window.location.href = _app_backend + "&func=datei&func2=verwalten";
});
```

Thank you for your help and great work!

**Comment by jayarjo** [comment]
I'm not able to repeat the error in usual scenario. Are you getting the error in the bundled UI example as well?

**Comment by nebrot** [comment]
Yes, the example "jquery_ui_widget.html" works, no error.
I have created a fiddle, where you should see the error: http://jsfiddle.net/9dnxvy93/6/

**Comment by jayarjo** [comment]
Thank you for taking your time to report this.

**Comment by nebrot** [comment]
Thank you for the quick fix.
