### ISSUE TITLE
IE9 and HTML4 runtime problem - open or save file?

### ISSUE THREAD

**Issue by provegard** [moxiecode/plupload#1267]
When I try to upload a file using the HTML4 runtime in IE9, I never get a FileUploaded event from plupload. Instead, IE asks if I want to open or save the response:

![image](https://cloud.githubusercontent.com/assets/795010/8529673/520dd0c6-241c-11e5-8dc1-b10f6a770cf7.png)

The server responds with plain JSON, content type `application/json; charset=utf8`.

The HTML5 runtime works well in Chrome, IE10 and IE11. The Flash runtime works in IE9.

Plupload version is 2.1.7.

**Comment by provegard** [comment]
Solved it by returning `text/html` from the server instead when the client is IE9. Ugly, but works. Is this documented somewhere?

**Comment by jayarjo** [comment]
Yes, ugly. But I'm afraid it is the only way to make `html4` interpret json response properly.

**Comment by provegard** [comment]
I got around the ugly User-Agent-checking part by checking the runtime in the Init event handler and adding a query string to the URL that instructs the server to set content type text/html.

But anyway, is there any documentation related to the server part? I couldn't find anything about having to use text/html for the html4 runtime.

**Comment by jayarjo** [comment]
Well... it is not really a requirement to send `text/html` header, `html4` runtime will work even if you don't send any header. It's specifically `application/json` header that causes download behaviour. I believe problem has been mentioned multiple times in the forum.

We have a description of basic server-side handler in our [Getting Started](https://github.com/moxiecode/plupload/wiki/Getting-Started) guide and the handler for the chunked upload in [Chunking](https://github.com/moxiecode/plupload/wiki/Chunking#server-side) guide. Also check the code for our sample [Plupload PHP Handler](https://github.com/moxiecode/plupload-handler-php).

**Comment by moahmn** [comment]
@provegard  man , i meet same problem , how do you fix that?

**Comment by provegard** [comment]
@moahmn I fixed it in the way I described in this comment: https://github.com/moxiecode/plupload/issues/1267#issuecomment-119556589
