### ISSUE TITLE
Is JPG (not JPEG) not a supported file type?

### ISSUE THREAD

**Issue by georaldcamposano** [moxiecode/plupload#1270]
For some reason, I can't get file selection to have jpg as an extension filter. While I have yet to update plupload since I'm using an older version (2.1.1), I noticed the same behavior in your website example section.

**Comment by jayarjo** [comment]
In which os/browser?

**Comment by georaldcamposano** [comment]
Windows + latest version of Firefox (39). The problem is *.jpg files are not available for selection, only *.jpeg (eventhough filter extension is set to something like "jpg,gif,png")

Seems to work fine in Chrome by the way

**Comment by jayarjo** [comment]
Related #1263.

**Comment by jayarjo** [comment]
I'm afraid one simply needs to add `jpeg` to the list of extensions.
