### ISSUE TITLE
Plupload Queue widget, iPad Chrome: unable to add video to the queue.

### ISSUE THREAD

**Issue by evpozdniakov** [moxiecode/plupload#1271]
I can't add video files to the queue using iPad Chrome. (iPad Safari works fine.)

I tested my old version plupload 1.5.3 + queue widget — works fine in both.

Feel free to check test pages, I've created during my research.
http://bumagi.net/u/plupload/plupload-queue.html
http://bumagi.net/u/plupload/plupload-queue-2.html

Thank you

**Comment by evpozdniakov** [comment]
I found the origin of the problem: when you add a video (in iOS Chrome), for some reason file size is zero and Plupload ignores it.

As a workaround I use ```html4``` runtime for iOS Chrome.

**Comment by jayarjo** [comment]
We do not ignore empty files anymore.
