### ISSUE TITLE
Bug about load plupload.full.min.js in a iframe

### ISSUE THREAD

**Issue by csethomas** [moxiecode/plupload#1275]
when I load plupload.full.min.js in a ifram, It will be failed. The error is 'Cannot read property 'addEventListener' of null'. My browser is chrome.

**Comment by aik099** [comment]
You mean, that you have page, that has `iframe` on it and the page, that loads in `iframe` has `<script>` tag to load plupload? Then it doesn't work?

**Comment by csethomas** [comment]
yes, I can't load plupload in a iframe.

**Comment by csethomas** [comment]
sorry, I find the the real problem happened when I call init method. I can't work in a iframe.

**Comment by jayarjo** [comment]
Does the same document work when you load it directly in the browser?
