### ISSUE TITLE
IE9 & Chrome Flash Runtime Core API issue. (Result returns null)

### ISSUE THREAD

**Issue by JohnRSim** [moxiecode/plupload#1276]
I have tried with 2.1.2 and 2.1.8

Running IE11 user Agent Internet Explorer 9 with Document mode 9.
As well as Internet explorer 9 in a vm from modern.ie

The core api with just the flash runtime - 
http://www.plupload.com/examples/core

Reaches 100% and looks to upload but the server does not receive the document.

This does work - if I switch to the Queue Widget and upload using flash runtime.

I am running examples provided updating only the URL to the correct path and making sure the runtime is set only to flash.

Also try to upload to 
http://www.plupload.com/examples/core in IE9 and you will receive

{"jsonrpc" : "2.0", "result" : null, "id" : "id"}

I am getting the following error from my server -
Content item '(null)' was not successfully checked in. The stream terminated before being able to read HTTP protocol line.

HTML4 runtime works fine.

**Comment by JohnRSim** [comment]
I found if I add the following the upload works.. 
required_features: 		'send_binary_string',

**Comment by jayarjo** [comment]
So, are you running .NET WebAPI server as well?

**Comment by JohnRSim** [comment]
I'm using a Content Management Application by Oracle.

I need to also be able to upload 2-5gb of assets to the system. 
html4 works fine for it.

**Comment by JohnRSim** [comment]
I noticed with required_features: 'send_binary_string', 
Uploading documents 10-15mb that the upload progress file.percent reaches 10, 11% and then hits 100%.. 

On checking the file on the server the whole file has been uploaded and is not corrupt.
Is this an issue with required_features sending as binary?..

**Comment by jayarjo** [comment]
If it's a Flash runtime, then in send_binary_string mode progress is not available and is roughly approximated. Should gradually improve if you are uploading more then one file.
