### ISSUE TITLE
Windows 10 Chrome - Lag on file choose

### ISSUE THREAD

**Issue by brainfoolong** [moxiecode/plupload#1278]
Hi!

I use plupload since a long time and it's great.
Last days i got Windows 10 and i use my websites in the same way as before with Windows 8.1.
Now i am experiencing some weird "stuck" moment when i choose a file with Plupload.

The event "FilesAdded" take a few seconds to fire, most of the time only once after you've closed and re-opened the browser.

I've a testcase here
https://jsfiddle.net/opeyswvj/7/

Open it with chrome and choose a file, the event fires some seconds after the file choose.
Maybe try different times with browser open and close if it does not happen for the first time.

My system: Windows 10, Chrome 44.0.2403.125 m
Plupload Version 2.1.4 for the testcase, also doesn't work for the newest 2.1.8.
Tested also with flash only and html5 only, same problem.

**Comment by buddycat75** [comment]
Windows 10 --> Same problem, and multiple files selection does'nt work (using CTRL task)
