### ISSUE TITLE
filter mime-type does not accept the official format for the "accept" attribute

### ISSUE THREAD

**Issue by luxigo** [moxiecode/plupload#1279]
It is not possible to specify the official format for the accept attribute, where one can supply comma-separated list of mime types as mentionned here: https://github.com/moxiecode/plupload/wiki/Options#filters.mime_types

...because of "Uncaught TypeError: Cannot read property 'split' of undefined" occuring @ 
https://github.com/moxiecode/plupload/blob/165c05588ba898b9810678f473593f740c46e5d5/js/plupload.dev.js#L1232

**Comment by jayarjo** [comment]
Can you post your config?

**Comment by luxigo** [comment]
filters: {
    mime_types : "image/*"
}
