### ISSUE TITLE
IE9, flash and chunking

### ISSUE THREAD

**Issue by siromega** [moxiecode/plupload#1281]
I've reviewed the documentation and I know it says that flash isn't the best for chunking, but I still need to use flash for chunking large file uploads that the server cant handle all at once. 

In IE9, I am encountering a -500 init error when initializing plupload. My settings are as follows: 

    runtimes : 'html5,flash',
    browse_button : 'pickfiles', 
    url : '/Home/Upload',
    flash_swf_url: '/Scripts/plupload/moxie.swf',
    chunk_size: "50mb",
    required_features: 'chunks',
    
	filters : {
		max_file_size : '250mb',
		mime_types: [
			{title : "Image files", extensions : "jpg,gif,png"},
			{title : "Zip files", extensions : "zip"}
		]
	},

The backend server is IIS/.NET. This same configuration works fine in Chrome (since its using HTML5). 

EDIT: fiddle http://jsfiddle.net/6ghzhfeb/3/

**Comment by jayarjo** [comment]
Init error might have following reasons:
* browse_button (or it's container) is not present in the DOM at the time of initialisation, is hidden or doesn't have dimensions.
* Flash Player version doesn't match minimum requirement of 10.3.
* Frequent reason for the fail is also wrong url for the swf shim, recheck the console for 404 errors.

**Comment by siromega** [comment]
I verified that I have the correct URL specified for the swf file. Browse button is created in the DOM (the script tag that instantiates plupload is at the end of the body). I have Flash version 18,0,0,232 installed. 

I checked the console.log in IE9 with devtools and found the following: 

LOG: Instantiating FileInput... 
LOG: Trying runtime: html5 
LOG: [object Object] 
LOG: 	default mode: browser 
LOG: 	selected mode: false 
LOG: Runtime 'html5' failed to initialize 
LOG: Trying runtime: flash 
LOG: [object Object] 
LOG: 		slice_blob: true (compatible modes: null) 
LOG: 		select_multiple: true (compatible modes: null) 
LOG: 	default mode: client 
LOG: 		slice_blob: true (compatible modes: null) 
LOG: 		select_file: true (compatible modes: null) 
LOG: 	selected mode: false 
LOG: Runtime 'flash' failed to initialize

**Comment by jayarjo** [comment]
Seems to be a regression (fixed it in: https://github.com/moxiecode/moxie/commit/5152098cacf9b5c1de00ff18ea63908029fc4bb4). 

To get a quick fix for this you could change [the following line](https://github.com/moxiecode/plupload/blob/master/js/plupload.dev.js#L38):

```javascript
chunks: 'slice_blob',
 ```

to this:

```javascript
chunks: 'access_binary',
 ```

**Comment by siromega** [comment]
Works, thanks!
