### ISSUE TITLE
Do not show 100% until upload is acknowledged by the server

### ISSUE THREAD

**Issue by Chouhada** [moxiecode/plupload#1282]
Suggestion: PLUpload should never show "100%" until it receives the success JSON.

Reason:
PLUpload will show "100%" in the progress indicators, even when it has not received a JSON response to indicate success.
This is ambiguous to the user and I've found they often navigate away from the page when uploading large files. "100%" is often translated as "complete"  in an end user's mind.

Consider the following out of upload.php:

// Return Success JSON-RPC response
die('{"jsonrpc" : "2.0", "result" : null, "id" : "id"}');

If you change this to:
sleep(5)
// Return Success JSON-RPC response
die('{"jsonrpc" : "2.0", "result" : null, "id" : "id"}');

You will be able to see the issue. Any server side processing / script execution can be problematic as a result. This isn't a huge issue for upload.php included with PLUpload, but when you start modifying this heavily to do other work (sometimes intensive), it can cause problems as the client will print "100%" right away, even when the server is not done.

The 'tick' gets shown to the user on the far right when the JSON response is sent. This is good behaviour.
I suggest that "100%" should only ever be shown in conjunction with this tick / JSON response. Until then, 99%, going to 100% on sending the success JSON.

**Comment by CanRau** [comment]
I like :+1:

**Comment by jayarjo** [comment]
Plupload doesn't depend on server responses or their formats. We tried to keep it purely a client-side solution. So we won't be implementing this in the Core API. And in the widgets I think we adequately highlight files that are uploading..? Incase you are using your own custom implementation, you could do the same - unambiguously express the current state of the file and even hide the percentage completely.
