### ISSUE TITLE
please include the http error code when failures occur

### ISSUE THREAD

**Issue by tkellen** [moxiecode/plupload#1284]
I'm using Wordpress for the first time and I was getting upload errors like this:
![image](https://cloud.githubusercontent.com/assets/1004324/9339307/4e4ec988-45b7-11e5-9e42-209404bfe02f.png)

...it appears this error message is being passed through via this dependency. I know I can see the status code in the network tab, but it would be really helpful to show the error code in the error message. "HTTP error." is basically useless for troubleshooting.

**Comment by meiranolick** [comment]
I'm encountering this problem and getting quite frustrated at the lack of useful information in the error message returned. It's not even returning a valid HTTP code, rather a -200, so I don't even know what the issue could be.
In my case, plupload is getting no response from the server-side upload script, yet when I run it normally, it works fine.

**Comment by jayarjo** [comment]
Second argument to [Error](http://www.plupload.com/docs/Uploader#Error-event) event contains all response headers in addition to code and message.
