### ISSUE TITLE
Your browser doesn't have Flash, Silverlight or HTML5 support

### ISSUE THREAD

**Issue by easonfg** [moxiecode/plupload#1285]
I ran into the problem where it says "Your browser doesn't have Flash, Silverlight or HTML5 support," when I configured PLUPLOAD and tried out the custom.html you provided on my local machine and server. I have used Firefox, Chrome, and Safari. Also all the jsfiddle demos gave me the same error message. I was wondering what could fix this? Using Internet Explorer??

**Comment by fr33tux** [comment]
Same here, with latest plupload and latest Chrome version.

**Comment by jayarjo** [comment]
@fr33tux this is not a typical case. Can you file your case at http://play.plupload.com?
