### ISSUE TITLE
Changing runtime after load (Silverlight/Flash after HTML breaks)

### ISSUE THREAD

**Issue by Yoelx** [moxiecode/plupload#1286]
I'm trying to give the user the option to change runtime, in case a runtime isn't working well for them (Usually IE users).

What I have now is on button-press I .destroy() the uploaders, and create them again. But it only works in some cases:

It works well for HTML5 and HTML4, but Silverlight and Flash only work if HTML5 or HTML4 has NOT run before. So:

Silverlight > HTML 4 > HTML 5 > HTML 4     they all work.
HTML 5 > Silverlight > HTML 4 > HTML 5     Silverlight does not work, the other 3 work
Silverlight > Flash > Silverlight > Flash           they all work.

Anyone has any idea what can cause this or what I could try? Why are the HTML runtimes disrupting the new Silverlight/Flash runtime uploaders, even though the old HTML uploader was destroyed?

Calling .refresh() doesn't help, and I also tried to completely remove the element from DOM and add it back, after destroy(). But no luck.

Any help is appreciated! Thanks a lot!

**Comment by jayarjo** [comment]
Does the `HTML 5 > Flash > HTML 4 > HTML 5` sequence work?

**Comment by Yoelx** [comment]
No, both Flash and Silverlight fail as soon as HTML 4 or HTML 5 has run before.
So with ```Flash > HTML 5 > HTML 4 > HTML 5``` they all work (flash also), but
```HTML 5 > Flash > HTML 4 > HTML 5``` only the HTML runtimes work, but not Flash.

And for example
```Flash > Silverlight > Flash > HTML 5 > Flash > HTML 4``` only the last Flash runtime (5th position) does not work, the first ones (flash, silverlight, flash) work fine. So it really is just only when HTML runtime has run before.

**Comment by jayarjo** [comment]
Ok, it seems some `zIndex` issue. Quick fix for this would be to reset the `zIndex` for the `browse_button` element to zero, after each destroy, something like this:

```javascript
document.getElementById('pickfiles').style.zIndex = 0;
```

Btw, IE shouldn't be affected by this issue (IE that requires Flash/Silverlight shims).

**Comment by jayarjo** [comment]
Addressed it in: https://github.com/moxiecode/moxie/commit/ced843d478a305eb5dec4cfdab78b5f0aac8a2bd.

**Comment by Yoelx** [comment]
Great! That seems to do the trick indeed!

Thank you very much for the quick response and the help!

**Comment by jayarjo** [comment]
You are welcome.
