### ISSUE TITLE
Add full path when uploading directory in Chrome

### ISSUE THREAD

**Issue by WoLpH** [moxiecode/plupload#1288]
When dragging/dropping directories on plupload (using jquery ui) plupload simply strips everything except for the filename. As you might expect, this causes problems if multiple subdirectories contain the same filename.

Right now I've worked around the issue by prepending the `relativePath` to the `name` using a filter. I would propose that this behaviour becomes the default (or at least configurable) since the behaviour is broken right now.

```
        plupload.addFileFilter('absolute_filename', function(absolute, file, cb) {
            var source = file.getSource();
            if(absolute && source.relativePath){
                /* Strip the first slash */
                path = source.relativePath.replace(/^\//, '');
                /* Set the name for both the file and the source to the full path */
                source.name = file.name = path;
            }
            cb(true);
        }); 
```

**Comment by jayarjo** [comment]
That shouldn't be a problem, if `prevent_duplicates` filter is disabled in your config.

**Comment by WoLpH** [comment]
@jayarjo: I don't believe that works, looking at the prevent duplicates code suggests that it would work only in the case of identical filesize.

```
plupload.addFileFilter('prevent_duplicates', function(value, file, cb) {
	if (value) {
		var ii = this.files.length;
		while (ii--) {
			// Compare by name and size (size might be 0 or undefined, but still equivalent for both)
			if (file.name === this.files[ii].name && file.size === this.files[ii].size) {
				this.trigger('Error', {
					code : plupload.FILE_DUPLICATE_ERROR,
					message : plupload.translate('Duplicate file error.'),
					file : file
				});
				cb(false);
				return;
			}
		}
	}
	cb(true);
});
```

Regardless, having the full path available might be more convenient anyhow.

**Comment by jayarjo** [comment]
We probably won't be implementing that. However I'm going to add `relativePath` property to `plupload.File` instances. 

One could also use [unique_names](https://github.com/moxiecode/plupload/wiki/Options#unique_names) option to generate completely unique names.
