### ISSUE TITLE
Directory drag drop in Firefox results in file with N/A size that can't be uploaded

### ISSUE THREAD

**Issue by WoLpH** [moxiecode/plupload#1289]
Not sure what it's supposed to do since Firefox doesn't seem to support directory drag/drop, but the current behaviour appears broken. Is there any easy way to detect these uploads? It appears that these uploads don't even pass the fileFilters so I can't filter it over there either.

Screenshot of the result:
![image](https://cloud.githubusercontent.com/assets/270571/9603239/a8205ffa-50af-11e5-8c6b-e532e14d57e3.png)

This is the result after pushing the "start upload" button

**Comment by jayarjo** [comment]
Do you maybe remember what was that Firefox version? At the moment Firefox does support drag'n'drop of folders.

**Comment by WoLpH** [comment]
I do not unfortunately.

A quick Google told me that it's available since version 50: https://bugzilla.mozilla.org/show_bug.cgi?id=876480
