### ISSUE TITLE
Plupload without moxie?

### ISSUE THREAD

**Issue by nazar-pc** [moxiecode/plupload#1291]
I do not care at all about IE9- and making custom build every time with HTML5 runtime only.
If I'm using only modern browsers, why should Plupload still depend on some polyfill?
I guess it should be very thin wrapper if everything is supported natively, but currently I'm forced to add 50+ KiB of JS for unnecessary polyfills...

**Comment by jayarjo** [comment]
I'm re-organising Plupload for the next release currently. I will take this into account.

**Comment by jayarjo** [comment]
Extra runtime stuff (at least its JavaScript part) takes extra 20kb or so. Image manipulation code that does client-side resizing before upload takes up to 30kb+. The rest is are utilities and Plupload itself. So you do not gain that much by stripping off extra runtimes.

But I'm altering the builder for the Plupload and it will be possible to build it with only the runtimes one requires or with/without image support, directly. One won't need to build moxie first, unless he wants to recompile the swf/xap shims.

**Comment by nazar-pc** [comment]
What if I'm not using client-side resizing? Would be nice to have build (or possibility to make it) without extra stuff.

**Comment by nazar-pc** [comment]
I rewrote my code to use wrapper around `$.ajax` which implements single/multiple files uploads, progress tracking, files dropping support - everything I need in just 150 lines of JS which is 4.5 KiB non-minified.
I do not care about this issue anymore, so I'm closing issue, reopen if it makes any sense to Plupload.
