### ISSUE TITLE
Plupload not work in my custom template in IE 7

### ISSUE THREAD

**Issue by Singh29** [moxiecode/plupload#1295]
when i debug through the plupload.full.min.js, i saw i get the error  when i submit image to load ,

for (var e = new Uint8Array(r.length), t = 0; t < r.length; t++) e[t] = 255 & r.charCodeAt(t);
                        f.send(e.buffer)
(show error : The parameter is incorrect. )
                    }() : f.send(r), s.trigger("loadstart")

This comes only in case when i load the image using plupload in IE 7.

Please help..!!

**Comment by jayarjo** [comment]
Why don't you try unminified scripts that come in the package? They might give more meaningful error and help us troubleshoot it better.

That part of the code shouldn't be even functional in IE7 btw, as it includes features that the latter doesn't have.

**Comment by Singh29** [comment]
I tried adding all files ..but that doesn't works...
The pacakge i downloaded is "plupload-2.1.8"

So here is my code which i am using in...
___________________________________________________________
$(document).ready(function() {
                    $("#Uploader").plupload({
                        runtimes: 'html5,html4',
                        url: "<%=Url.Action("DoUploadPhotos", "MaintainPhotos", new { module = "InputMaint", id = Model.ListingId }) %>",
                        max_file_size: '<%= ViewData["MaxFileSizeMb"] %> mb',
                        max_file_count: <%= ViewData["MaxFiles"] %> ,
                        chunk_size: '1mb',
                        unique_names: false,
                        resize: { width: 600, height: 400, quality: 90, crop: true },
                        filters: [{ title: "Image files", extensions: "jpg,jpeg,gif,png,gif,tif,tiff,bmp" }],
                        rename: true,
                        sortable: true,
                        dragdrop: true,
                        views: {
                            list: true,
                            thumbs: true,
                            active: 'thumbs'
                        },                       
                        multiple_queues: false,
                        prevent_duplicates: false,
                        multi_selection: false,
                        multipart_params: {
                            "listingID": '<%=Model.ListingId%>',
                            "callingWindow": '<%=ViewData["CallingWindow"]%>',
                            "isMulti": '<%=ViewData["IsMulti"]%>',
                            "fileToReplace": '<%= Html.JsEncode(ViewData["FileToReplace"] as string) %>'
                        }                      
                    });
                });
____________________________________________________________

And the files that i am calling are,
jquery.ui.plupload.min.js,
plupload.full.min.js,
jquery.ui.plupload.css

When i ran the same code in IE 8,9,10...the photo "Add" and " Submit:" works...

While when I use the IE7...i get the error "The parameter is incorrect. "


This value is coming when i checked the r.length,
----------------------------------------------------------------------------------------------------------------
"------moxieboundary1442380261319\r\nContent-Disposition: form-data; name=\"name\"\r\n\r\nPenguins.jpg\r\n------moxieboundary1442380261319\r\nContent-Disposition: form-data; name=\"listingID\"\r\n\r\n63591\r\n------moxieboundary1442380261319\r\nContent-Disposition: form-data; name=\"callingWindow\"\r\n\r\n\r\n------moxieboundary1442380261319\r\nContent-Disposition: form-data; name=\"isMulti\"\r\n\r\nFalse\r\n------moxieboundary1442380261319\r\nContent-Disposition: form-data; name=\"fileToReplace\"\r\n\r\n\r\n------moxieboundary1442380261319\r\nContent-Disposition: form-data; name=\"file\"; filename=\"Penguins.jpg\"\r\nContent-Type: image/jpeg\r\n\r\nÿØÿà"

-----------------------------------------------------------------------------------------------------------------

Appreciate your help ..!!

**Comment by Singh29** [comment]
When i use the plupload example UI Widget...it works in IE 7 also....so i don't know why its not working in my custom call..

**Comment by Singh29** [comment]
Here is the image of error which i got in IE 7
![img1](https://cloud.githubusercontent.com/assets/14303339/9910343/4fb24ae0-5c62-11e5-86d6-e815cb089a02.png)

![img](https://cloud.githubusercontent.com/assets/14303339/9910348/555ab932-5c62-11e5-8870-bee43e879ed0.png)

**Comment by Singh29** [comment]
For IE 8,9,10, when debugger goes to that f.send(e.buffer)...it works and doesn't show error...and passed to s.trigger process....while in case of IE 7...it shows error.

**Comment by jayarjo** [comment]
Any reason why you ignore flash runtime? It was created specifically for those legacy browsers.

**Comment by Singh29** [comment]
We need to provide the custom solution for photo upload...single & multiple photo upload.
And this feature we provide where the flash is not available..i mean only HTML5 and HTML4 support...

So thats why we not using...?

Is that section necessary..?

**Comment by Singh29** [comment]
So now i am using the flash and silverlight runtime..and also calling the flash and silverlight url...and that error which coming earlier gone.

But now i am getting another error,

" HTTP Error. 
Upload URL might be wrong or doesn't exist."

Here is my code:-

<asp:Content ID="Content1" ContentPlaceHolderID="TitleContent" runat="server">
    <%= Html.Encode(ViewData["title"]) %>
    Maintain Photos
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="HeaderContent" runat="server">
    <%=Html.CssPackage("MaintainPhotos")%>  
    <style type="text/css">
   .ui-widget-header {
      height: 42px;
}
   .ui-icon-circle-minus {
       background-color: #ff0000;
   }
   .ui-icon-circle-check {
       background-color: #008000;
       pointer-events: none;
   }
   .ui-icon-circle-close {
       pointer-events: inherit;
   }
</style>
  
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="MainContent" runat="server">
  
	<div id="uploader">
		<p>Your browser doesn't have Flash, Silverlight or HTML5 support.</p>
	</div>
     <div style="float: inherit; width: 900px;" class="f-email-attachment-heading">
                    <p>
                        <%=Model.UploaderInstruction(ViewData["IsMulti"].ToString().ToLower().Contains("true")) %>
                    </p>
                    <p id="pError">
                    </p>
                </div>
    <div id="noFlash" style="margin: 30px; display: none;">
         <div class="f-email-attachment-heading">
                    <p>
                        <%=Model.UploaderInstruction(false) %></p>
                </div>
        </div>
	<br />
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ScriptContent" runat="server">    
   <%= Html.JsPackage("MaintainPhotos")%>
    <input type="hidden" id="isMulti" name="isMulti" value="<%=ViewData["IsMulti"]%>" />
        <input type="hidden" id="callingWindow" name="callingWindow" value="<%=ViewData["CallingWindow"] %>" />
        <input type="hidden" id="fileToReplace" name="fileToReplace" value="<%:ViewData["FileToReplace"] %>" />
    
        <script type="text/javascript">
            var ismulti = '<%=ViewData["IsMulti"].ToString()%>';
            var verifyPhotoUrl = '<%=Url.Action("VerifyCount", "MaintainPhotos", new { module = "InputMaint", id = Model.ListingId }) %>';

            if (ismulti === "False") {
                $(document).ready(function() {
                    $("#uploader").plupload({
                        runtimes : 'html5,flash,silverlight,html4',
                        container:'uploader',
                        url: "<%=Url.Action("DoUploadPhotos", "MaintainPhotos", new { module = "InputMaint", id = Model.ListingId }) %>",
                        max_file_size: '<%= ViewData["MaxFileSizeMb"] %> mb',
                        max_file_count: <%= ViewData["MaxFiles"] %> ,
                        chunk_size: '1mb',
                        unique_names: false,
                        resize: { width: 600, height: 400, quality: 90, crop: true },
                        filters: [{ title: "Image files", extensions: "jpg,jpeg,gif,png,gif,tif,tiff,bmp" }],
                        rename: true,
                        sortable: true,
                        dragdrop: true,
                        views: {
                            list: true,
                            thumbs: true,
                            active: 'thumbs'
                        },
                        // Flash settings
                        flash_swf_url : 'http://rawgithub.com/moxiecode/moxie/master/bin/flash/Moxie.cdn.swf',

                        // Silverlight settings
                        silverlight_xap_url : 'http://rawgithub.com/moxiecode/moxie/master/bin/silverlight/Moxie.cdn.xap',
                        multiple_queues: false,
                        prevent_duplicates: false,
                        multi_selection: false,
                        multipart_params: {
                            "listingID": '<%=Model.ListingId%>',
                            "callingWindow": '<%=ViewData["CallingWindow"]%>',
                            "isMulti": '<%=ViewData["IsMulti"]%>',
                            "fileToReplace": '<%= Html.JsEncode(ViewData["FileToReplace"] as string) %>'
                        }                      
                    });                    
                });
            } else {
                $(document).ready(function() {
                    $("#uploader").plupload({
                        runtimes : 'html5,flash,silverlight,html4',
                        container:'uploader',
                        url: "<%=Url.Action("DoUploadPhotos", "MaintainPhotos", new { module = "InputMaint", id = Model.ListingId }) %>",
                        max_file_size: '<%= ViewData["MaxFileSizeMb"] %> mb',
                        max_file_count: <%= ViewData["MaxFiles"] %> ,
                        chunk_size: '1mb',
                        unique_names: false,
                        resize: { width: 600, height: 400, quality: 90, crop: true },
                        filters: [{ title: "Image files", extensions: "jpg,jpeg,gif,png,gif,tif,tiff,bmp" }],
                        rename: true,
                        sortable: true,
                        dragdrop: true,
                        views: {
                            list: true,
                            thumbs: true,
                            active: 'thumbs'
                        },
                        // Flash settings
                        flash_swf_url : 'http://rawgithub.com/moxiecode/moxie/master/bin/flash/Moxie.cdn.swf',

                        // Silverlight settings
                        silverlight_xap_url : 'http://rawgithub.com/moxiecode/moxie/master/bin/silverlight/Moxie.cdn.xap',
                        multiple_queues: true,
                        prevent_duplicates:false,
                        multi_selection: true,
                        multipart_params: {
                            "listingID": '<%=Model.ListingId%>',
                            "callingWindow": '<%=ViewData["CallingWindow"]%>',
                            "isMulti": '<%=ViewData["IsMulti"]%>',
                            "fileToReplace": '<%= Html.JsEncode(ViewData["FileToReplace"] as string) %>'
                        }                      
                    });                    
                });
            }
        </script>
</asp:Content>


![img2](https://cloud.githubusercontent.com/assets/14303339/9969181/a0c0e318-5e12-11e5-91ef-ae049f3dd398.png)


This error which shown in above screenshot is coming when i check through IE 7( in IE i set the document mode to 7) ....and then get the error.....


Appreciate help...!!

**Comment by Singh29** [comment]
Need help for the above issue ........!!

Appreciate help..!!

**Comment by Singh29** [comment]
what would be the flash file path...i am using the Moxie.swf file inside my c#.net code.It is inside the project folder   so do i pass like this   :  flash_swf_url: '~/Scripts/plupload/moxie.swf',

**Comment by Singh29** [comment]
Also do i need to use upload.php....

rightnow i am passing in,

 url : "<%=Url.Action("DoUploadPhotos", "MaintainPhotos", new { module = "InputMaint", id = Model.ListingId }) %>"

This is working on chrome,firefox,safari and IE 9-10

But when i check in IE 7 and 8..i get the http error.

**Comment by Singh29** [comment]
I got.

I was doing wrongly in above code..............The url which i was passing to flash_swf_url in above mentioned code was not correct.I need to pass the absolute url of the flash file which was located in my code.

Thanks...!!
