### ISSUE TITLE
Thread file resize and upload

### ISSUE THREAD

**Issue by AndyWorral** [moxiecode/plupload#1298]
- Add a value sent back for "index"
- thread uploading to multiple files at once
- If threading upload doesn't make sense, at least thread resize of image so that if you have multiple large image files that while one is being uploaded, resize the next on in memory so its ready to upload once previous file is done uploading.
- having the index sent will keep order for images on server side.  Currently I included a "session" in upload url so I know all photos included in the upload session I append a _<index> to file.name prior to upload in the "start" event so I can parse it out later on server.

**Comment by jayarjo** [comment]
Simultaneous uploads of chunks and files is supported in Plupload v3.x. We won't take it any further probably.
