### ISSUE TITLE
Cannot catch error while uploading corrupted jpeg files

### ISSUE THREAD

**Issue by keremdemirer** [moxiecode/plupload#1299]
I'm trying to handle errors for users uploading corrupted files. Upload works perfectly well when resize option is not enabled but moxiecode throws following error and onerror event does not catch it. So the file does not get error state and the application stucks as is.

Exception thrown: Uncaught WRONG_FORMAT: WRONG_FORMAT: ImageError 1 

Is there any workaround to solve this?

**Comment by ShangXinbo** [comment]
I get this error too!
