### ISSUE TITLE
Pause upload doesn't work

### ISSUE THREAD

**Issue by yss14** [moxiecode/plupload#1302]
Hi
I just found a older solution in the plupload [forum](http://www.plupload.com/punbb/viewtopic.php?id=1302) to pause an upload because I have to do some XHR before.

``` javascript
BeforeUpload:   function(up, file){
    var j = {
        //Some json
    }
    DataController.getUploadToken(function(uploadToken){
        j.uploadToken = uploadToken;
        uploader.setOption("url", apiUrl.replace("https", "http") + "?json=" + JSON.stringify(j));
        uploader.trigger("UploadFile", file);
    });
    return false;
},

UploadFile:     function(up, file){
    console.log("Upload started!!");  
},
```

The UploadFile Event is triggered but there is no request to the server.

**Comment by tomick** [comment]
Yes, it's not working. 
For now you must add 
`file.status = plupload.UPLOADING`
before trigger. I hope it helps :)

**Comment by KennanChan** [comment]
Same issue here. For every added file, I would like to request the server for a temporary token to upload the file. When the server responds, I need to reset the url of the uploader to the correct url and add some more parameters to continue uploading. But the current version of plupload won't wait for asynchronous http request after the uploader calls BeforeUpload. I am now using synchronous request to solve the issue which is deprecated by the latest browsers. It will be perfect if the file upload process can be paused and resumed manually.
