### ISSUE TITLE
How to tell plupload that the downloaded file is not compliant?

### ISSUE THREAD

**Issue by RomanKoff** [moxiecode/plupload#1305]
What response should come from the server that the script generated the error event?
For example, after verification revealed that the actual file type is different from the assigned extension or the file already uploaded to the server.

IIS, ASP.NET MVC

**Comment by jayarjo** [comment]
Plupload doesn't depend on server responses and doesn't trigger any error by itself, unless there was  some unsatisfying HTTP status code in response. So if you return erroneous HTTP header, Plupload will report upload problem. However I prefer to return an actual message from the server (it can be any format, but I recommend JSON as the simplest), then capture it in FileUploaded handler (as the third argument) and display it or act accordingly.
