### ISSUE TITLE
plupload cannot choose jar file on mac safari

### ISSUE THREAD

**Issue by nilday** [moxiecode/plupload#1310]
I use plupload 2.1.8 as my file uploader. It works well on several browsers ,but does not work on Mac Safari.
I use filters like:
filters : {
        mime_types : [ {
            title : "Jar files",
            extensions : "jar"
        }, {
            title : "Zip files",
            extensions : "zip"
        } ]
    },
But Mac Safari users can't choose jar file(The file is gray and cannot be chosen).
As I noticed the FAQ on the official website, I added 
mOxie.Mime.addMimeType("application/java-archive,jar");
when page inits, but It seems like it doesn't work.
Have any of you ever meet this problem?

**Comment by jayarjo** [comment]
It might be that you were choosing wrong mime-type. Anyway this nightmare should have ended by now, since browsers started to support filtering by extensions directly. So forget mime-types and `addMimeType` method.
