### ISSUE TITLE
Filter video upload by video quality

### ISSUE THREAD

**Issue by vaske** [moxiecode/plupload#1311]
I had been searching for such filter, do you have support for this?
Want to prevent users to upload videos which width is less than 320px.

**Comment by jayarjo** [comment]
We do not have video quality filter in Plupload.But I can imagine how one could [write one his own](http://www.plupload.com/docs/v2/File-Filters).

**Comment by vaske** [comment]
@jayarjo this was almost 2yrs ago, I managed it in the mean time :)

**Comment by jayarjo** [comment]
Sorry. Closing off old tickets.
