### ISSUE TITLE
Plupload :- Drag and Drop of photos is not working in IE version 10,11 and edge.

### ISSUE THREAD

**Issue by Singh29** [moxiecode/plupload#1314]
Need help...!!

How to fixed this drag and drop in IE versions 10,11 and edge.

**Comment by jayarjo** [comment]
Seems to work fine: http://play.plupload.com/y/4

**Comment by binal24** [comment]
That given sample link is not working IE 11 & Edge.
Is there any specific requirement of browser. Require any add-ons for Drag and Drop ?

**Comment by jayarjo** [comment]
@binal24 it is working. If you mean it doesn't work for `mp4` files, then I've replied to your question in the #1514 thread.
