### ISSUE TITLE
Wish: Rotate Image Using Metadata

### ISSUE THREAD

**Issue by MikMuller** [moxiecode/plupload#1315]
I'm not sure how this would be done, but if there is meta data in the image file indicating which way is "up" please find and rotate the image before resizing and uploading. Especially on iPhones, which, if the camera is held upright (vertically), the camera is actually sideways, and the images uploaded wind up horizontal, with "up" being to the left. Thanks!

**Comment by MikMuller** [comment]
Any thoughts on this item? Or is there a tool I can snap in to look at the EXIF data and rotate before resizing occurs?

**Comment by toke182** [comment]
have the same issue, images uploaded directly with mobile devices in vertical, gets rotated to horizontal automatically.

Anyone fixed this or has a workaround?

**Comment by jayarjo** [comment]
Resizing options have a special flag: [preserve_headers](http://www.plupload.com/docs/v3/Image-Resizing-on-Client-Side#strip-headers). By default Plupload retains EXIF headers, so if there is an Orientation tag in there, Plupload will keep it. So it will be up to your client software (preview tool, etc) how it will handle it. However if you set it to *false* - meta headers will get stripped, including Orientation tag. In such case we internally auto-rotate the image in the direction specified by Orientation tag.

Play with the option to see if it helps.

**Comment by jayarjo** [comment]
Related: https://github.com/moxiecode/plupload/issues/1414.

**Comment by strider72** [comment]
One issue with this may be that the Safari engine on iOS displays an image according to its EXIF rotation. NO other browsers do this.  So you would essentially have to browser-sniff to detect iOS

https://caniuse.com/#search=image-orientation
