### ISSUE TITLE
Problem with safari iOS when initializing

### ISSUE THREAD

**Issue by altimea** [moxiecode/plupload#1318]
I have a problem, everything works in the rest of platforms but in my code when I click on the add file button on a safari iOS nothing happens. I have to debug the iphone with the usb Cable and in console execute manually window.uploader.init() for the button to work.

What could be causing this behaviour?

Thanks

**Comment by altimea** [comment]
I finally was able to fix the issue but I would like to know how to do the same thing the right way.

My fix was to change the default "position: absolute" to "initial" on the "moxie-shim" class generated by plupload after calling uploader.init()

Why would I need to do this for the button to work on safari iOS?

**Comment by jayarjo** [comment]
You shouldn't need to do it. Can you post your code and config?

**Comment by rek** [comment]
Fix worked for us too! Thanks!

**Comment by madmaker** [comment]
Hi,
Can you explain what did you changed and where?
I mean filename and code before and after.

I have the same issue.

**Comment by madmaker** [comment]
I had same issue.
Find out the reason. Because of my own code "input type=file" rendered in "moxie-shim" was hidden.
Just check that this element is visible and in right place.

**Comment by nouphaltklm** [comment]
This fix worked for us too. We were having plupload in a popup. ( Plupload  v2.3.1 )

**Comment by jayarjo** [comment]
Plupload cannot initialize on hidden elements in some browsers. That's why we `uploader.refresh()` method. It's whole purpose is to address just that. Be sure to call it after you show up `browse_button` element.

**Comment by sergemaksimov** [comment]
Looks like this fix is causing styling issues on desktop. See here: https://retrievept.cmsmax.com/for-providers
It is adding a lot of space below the upload button.
