### ISSUE TITLE
on  ios safari(iphone 6s), maually call browse_btn.click() cannot trigger file select action 

### ISSUE THREAD

**Issue by netweaver** [moxiecode/plupload#1323]
i only use plupload core
for example:
settings:
browse_button:”btn1"

manually trigger click event to open file select dialog in a function, such as 
$('#btn1').click();   //jquery
$('#btn1').trigger("click");  //jquery
document.getElementById("btn1").click()  

on pc chrome, ie, firefox,or  andriod phone brownser, or even windows safari,   it is ok.
but on iphone 6s with ios safari, nohting happens

btw, i tried to add onclick="func()" property to  btn1 tag, and click btn1 with mouse,  func() was not executed, this may help to locate the issue

thanks

**Comment by netweaver** [comment]
IE 6-9 also have this problem

**Comment by jayarjo** [comment]
Replied to your problem here: https://github.com/moxiecode/moxie/issues/150. Basically such functionality is not supported by some browsers, especially the old ones, like those you named above. Sad but true.
