### ISSUE TITLE
Chunking not working on chrome 47.0.2526.80

### ISSUE THREAD

**Issue by nishankbangera** [moxiecode/plupload#1324]
Hi,

We are using Plupload version v2.1.2

Our upload with chunking has suddenly stopped on chrome ( 47.0.2526.80) after upgrade to latest chrome version. It is still working on IE and Firefox.
It works without chunking on all browsers.

runtime has been set in following sequence 'html5,silverlight,html4'.

Is there anything we can do to make it work on chrome again?

**Comment by kazaaaak** [comment]
Hello!

I ran into that problem with chunking. I had used 1.5.5 and chrome 47.0.2526.106. Updating Plupload to the latest version didn't help. I used fiddler to catch brocked post-request. It seems when it crashes blob data(as much as chunk size) is filled with empty values which causes exception on server side. 

Haven't found the solution :(

**Comment by kazaaaak** [comment]
Fixed in new version of chrome 111m.

**Comment by nishankbangera** [comment]
Thank You. 

We checked and it worked with the latest chrome update.
