### ISSUE TITLE
Make plupload responsive

### ISSUE THREAD

**Issue by Daijobou** [moxiecode/plupload#1327]
In smartphones the queue widget don't look very nice. Buttons and elements are outside of formular.

Thanks for your work!

**Comment by jayarjo** [comment]
Initially those widgets (especially Queue widget) have started as examples. One could easily come up with any kind of UI, by using Core API directly.

I don't think we will be updating Queue Widget. Fixes and pull requests are welcome though.

**Comment by dotmagic** [comment]
@jayarjo I'm asking to reopen this issue. Even its just example code, I think its essential to have a working responsive example. It's 2018 and mobile support is a must have for almost every web application.

In my case need plupload with responsive drag n drop thumbnails to change the order of uploads and I am very unsure this feature works out-of-the-box on mobile?

**Comment by dotmagic** [comment]
By default plupload use some layout tables (wahhhh!). At least this should really be changed in 3.x. I didn't digg deep enough yet to check its possible to change this Markup.
