### ISSUE TITLE
Add plupload to npm

### ISSUE THREAD

**Issue by damnedest** [moxiecode/plupload#1328]
Can you add plupload to npm packages also, it's very helpful.

**Comment by Cweili** [comment]
+1

**Comment by weilao** [comment]
+1

**Comment by magnitronus** [comment]
+1

**Comment by Catlite91** [comment]
+1

**Comment by leanplay** [comment]
+1

**Comment by xingchenboy** [comment]
+1

**Comment by eman1986** [comment]
+1

**Comment by PeakTai** [comment]
+1

**Comment by suhaotian** [comment]
+1

**Comment by janjon** [comment]
+1

**Comment by nqdy666** [comment]
+1

**Comment by matt-paul** [comment]
+1

**Comment by jayarjo** [comment]
Plupload on NPM now: https://www.npmjs.com/package/plupload.

**Comment by jayarjo** [comment]
I must confess I didn't realize properly that this was a big deal. Sorry guys.

**Comment by suhaotian** [comment]
Module not found: Error: Can't resolve 'plupload'

**Comment by suhaotian** [comment]
```js
import plupload from 'plupload'
// Module not found: error: Can't resolve 'plupload'
```

Then:
```js
import plupload from 'plupload/src/plupload'
// build pass, but in the browser console: moxie is not defined
```

**Comment by jayarjo** [comment]
@suhaotian I think it should correspond to file name, so when you import specify either: `plupload.dev`, `plupload.min` or `plupload.full.min`.

**Comment by suhaotian** [comment]
@jayarjo Did you test it in webpack ?

**Comment by cocody** [comment]
It is fully not work.  what ever "Cannot resolve module 'plupload" or "Cannot resolve module 'plupload.full.min"

**Comment by jayarjo** [comment]
@suhaotian yes, but I tested it with require. Didn't do Babel.

**Comment by jayarjo** [comment]
@cocody  how do you include it and what kind of post-processing you do on `js` files after?

**Comment by jayarjo** [comment]
Ok, I see now `package.json` lacks `main` entry. 

Could you guys be so kind to add something like this to the `package.json` of installed plupload module:

```
"main": "./js/plupload.full.min",
```

and confirm if it makes it work?

**Comment by jayarjo** [comment]
v2.2.1 [has been published](https://www.npmjs.com/package/plupload), that addresses missing entry point.
