### ISSUE TITLE
PLUpload doesn't initiate when the page is called via an ajax (pjax) request

### ISSUE THREAD

**Issue by schester44** [moxiecode/plupload#1333]
I have the uploader on a separate page and when I call that page via a pjax/ajax request, the GUI/uploader never loads. I get the default error message "Your browser doesn't have Flash, Silverlight or HTML5 support."  If I visit the page directly though, the uploader works. Is there a work around? I've tried binding plupload to $('body #uploader') instead of just $('#uploader') but no dice

**Comment by jayarjo** [comment]
There are couple of things to take into account t in such cases. You must make sure that Plupload initialisation code is run after the page is loaded through the ajax call. And that the `browse_button` element exists by that time and has dimensions.
