### ISSUE TITLE
Bug in Ajax on cirrylic domains

### ISSUE THREAD

**Issue by sibputnik** [moxiecode/plupload#1336]
Hi.
I use cirrylic domain with NextGen Gallery and can't upload photos on any widget. 
I fount, that problem is in mOxie. It converts url on wrong way and ajax request can't be send. But I can't find where it happens. Ajax url u can see below and it ok - I can encode it ro right url. But mOxie do strange url, it also below.
## in webpage:

var photocrati_ajax = {"url":"http:\/\/\u0441\u043f\u043e\u0440\u0442\u0431\u0440\u0430\u0442\u0441\u043a.\u0440\u0444\/?photocrati_ajax=1","wp_home_url":"http:\/\/\u0441\u043f\u043e\u0440\u0442\u0431\u0440\u0430\u0442\u0441\u043a.\u0440\u0444","wp_site_url":"http:\/\/\u0441\u043f\u043e\u0440\u0442\u0431\u0440\u0430\u0442\u0441\u043a.\u0440\u0444","wp_root_url":"http:\/\/\u0441\u043f\u043e\u0440\u0442\u0431\u0440\u0430\u0442\u0441\u043a.\u0440\u0444","wp_plugins_url":"http:\/\/\u0441\u043f\u043e\u0440\u0442\u0431\u0440\u0430\u0442\u0441\u043a.\u0440\u0444\/wp-content\/plugins","wp_content_url":"http:\/\/\u0441\u043f\u043e\u0440\u0442\u0431\u0440\u0430\u0442\u0441\u043a.\u0440\u0444\/wp-content","wp_includes_url":"http:\/\/\u0441\u043f\u043e\u0440\u0442\u0431\u0440\u0430\u0442\u0441\u043a.\u0440\u0444\/wp-includes\/","ngg_param_slug":"nggallery"};
/\* ]]> 
## ajax request:

http://%C3%91%C2%81%C3%90%C2%BF%C3%90%C2%BE%C3%91%C2%80%C3%91%C2%82%C3%90%C2%B1%C3%91%C2%80%C3%90%C2%B0%C3%91%C2%82%C3%91%C2%81%C3%90%C2%BA.%C3%91%C2%80%C3%91%C2%84/?photocrati_ajax=1&action=upload_image&gallery_id=4&gallery_name=&nextgen_upload_image_sec=8ddbafe3cb

**Comment by jayarjo** [comment]
Try to represent your cyrillic urls with their [Punycode](https://en.wikipedia.org/wiki/Punycode) alternative instead. Basically if you copy url that consists of such native characters from Chrome address bar, and paste it in some text editor, url will be automatically converted to Punycode.

There are also numerous libs for all languages, in case you would like to do it manually. It would unnecessarily increase our source code (already big) if we would incorporate one of this into moxie. So we - won't.
