### ISSUE TITLE
Accept parameter is not updated when 'settings.filters.mime_types' is changed after .init()

### ISSUE THREAD

**Issue by conniden** [moxiecode/plupload#1339]
If you use setOptions() to update the filters.mime_types property **after** calling init, the accept parameter for the input:file element is not updated to correspond to the new file types. This results in the file dialog displaying/allowing the selection of invalid files. Selecting an invalid file will then result in "Error #-601: File extension error.", since Plupload **is** using the updated filter.

This can be demonstrated in this [jsfiddle](https://jsfiddle.net/57z3gfp5/)

Intitially, the filter is set to 'jpg'. Clicking the select button will present a dialog with only JPG files available (as expected). Now click to change the filter to 'zip'. Clicking the select button will still show a dialog box with only JPG files available (should be ZIP files), but if you select one, you get a file extension error. 

Tested with Plupload Core API 2.1.8 on Safari (Mac), Chrome (Mac/Win), and Edge (Win).

**Comment by jayarjo** [comment]
In 2.3.1 it works properly. I moved your fiddle to: http://play.plupload.com/q__J_/1.

**Comment by wtslh** [comment]
In 2.3.3,this problem didn't get resolved.
I've spent days to find a way but failed.

**Comment by jayarjo** [comment]
@wtslh what problem didn't get resolved? Does the fiddle above fail for you?

**Comment by guptavaibhav18197** [comment]
Facing the same issue in Plupload v3.1.2

Even though I am able to see filters changed in browser's console by using this - uploader.getOption('filters')
still the dialog does work accordingly, it still behaves as if not updates on mime_type has happened.

**Comment by joshuasiegal** [comment]
This provided example is broken.

http://play.plupload.com/q__J_/1

For example, when I click on the "zip" link and then "select files", it still only allows me to select jpgs.  This happens in multiple browsers, using the 2.3.6 (latest stable) codebase.

**Comment by conniden** [comment]
That is the bug the example was meant to demonstrate. I haven’t worked on this in years, but I think the JS code was sound in terms of what it was trying to do and how (based on the documentation) it was trying to do it. Happy to be wrong, though.

**Comment by joshuasiegal** [comment]
Well, in that case it demonstrates the brokenness well.  :)

I can still get this bug to appear using the Pluploads 2.3.6 codebase.  If you have any information on how to get this working properly, I'm all ears.  I've tried a lot of different approaches.  Thanks!

**Comment by conniden** [comment]
Unfortunately, I never found a workaround, then got pulled into other projects. Not sure why it this was closed if it still doesn’t work, but it’s certainly possible my example code is not valid. Others seem to be having the same problem, though.

**Comment by cwolcott** [comment]
Having the same issue that everyone else is reporting in 2.3.6.

**Comment by joshuasiegal** [comment]
@cwolcott - I think what we ended up doing was storing the uploader config in its own object, then if the mime types change, we destroy and re-init the uploader.  It's not the best, but it seems to work.
