### ISSUE TITLE
Plupload got bugs on Microsoft Edge browser

### ISSUE THREAD

**Issue by clichedmoog** [moxiecode/plupload#1343]
1. mouse pointer on upload button not changed in Microsoft Edge browser
2. button is not working when plupload initialized on hidden element (like dropdown button)
3. drag & drop is not working like others reported

You might these bugs at the plupload example pages also. (http://www.plupload.com/examples/)
Windiws 10 64bit, Edge: 20.10240.16384.0

**Comment by warrendodsworth** [comment]
I'm seeing issue 2 present itself on edge
2. I'm finding that on MS Edge the click event isn't attached to the trigger element (the element isn't hidden). Whereas on IE 11 the click event is attached.

I'm not seeing the issue presenting itself on their example page on MS Edge.

**Comment by JamesLawrenceGSI** [comment]
I am also having this problem.  Upload button not firing in Edge, fine in other browsers.  Has there been a fix?

**Comment by Daijobou** [comment]
Here too. When plupload was hidden, after show div with plupload, the "add files"-button not working. Chrome and Firefox working fine. Windiws 10 64bit, Edge: 25

**Comment by helgefmi** [comment]
Similar problem here. I used the following code to just work around it, seemed to work fine for our purposes.

```javascript
function _open_browse_manually() {
    $container.find('input[type=file]').click();
    return false;
}

$browse.on('click', _open_browse_manually);

uploader.bind('Browse', function() {
    $browse.off('click', _open_browse_manually);
});
```

**Comment by Daijobou** [comment]
I have another workaround for you:

without Queue
```
        $(document).on('mouseenter', '#your-id', function()
		{
            myplupload.refresh();
		});
```

with Queue
```
        myplupload = $('#your-id').pluploadQueue();
        $(document).on('mouseenter', '#your-id, function()
		{
            myplupload.refresh();
		});
```

**Comment by jayarjo** [comment]
Plupload cannot initialise properly on hidden element, so after you finally show the element that should trigger browse dialog (like in the case of drop down menu), you should call `uploader.refresh()`, just as @Daijobou has suggested.
