### ISSUE TITLE
Can't drop folder in plupload queue from any browser besides chrome

### ISSUE THREAD

**Issue by mattdirk** [moxiecode/plupload#1345]
I tried this on the example site http://www.plupload.com/examples/queue.  I have a folder with 2 items in it but when I drop the folder from any browser besides chrome it throws the error "Error: Invalid file extension: test".  Test being the name of the folder that i'm trying to drop.  I am using the latest firefox (44.0.2).

**Comment by jayarjo** [comment]
Apparently it is not supported in those other browsers.
