### ISSUE TITLE
resize based on file size

### ISSUE THREAD

**Issue by wszak** [moxiecode/plupload#1346]
Hi,
Here is my simple feature request: add an option so that the image is resized only if its size is greater than the provided value. 

The use case is such that it's often irrelevant what the resolution of the image is, but it's important that it doesn't occupy too much disk space (and bandwidth during uploading).

For example:

This config:
resize: {
   filesize: 500000,
   quality: 75
}
would force resize only if image's filesize is greater than 500kB.

This one:
resize: {
   width: 2000,
   height: 2000,
   filesize: 500000,
   quality: 75
}
would also resize if resolution is greater than 2000 pixels in width/height.

**Comment by jayarjo** [comment]
You could hook onto `BeforeUpload` and `manipulate` resize option for each file yourself, switching it on and off depending on the file size of the file being uploaded.
