### ISSUE TITLE
plupload sends request for every chunk on server. How to send multiple chunks on single request to backend?

### ISSUE THREAD

**Issue by KalpanaPagariya** [moxiecode/plupload#1347]

**Comment by KalpanaPagariya** [comment]
plupload sends request for every chunk on server. Due to this plupload takes much time to upload documents.

**Comment by jayarjo** [comment]
Plupload 1.x and 2.x upload files and chunks sequentially. This is not a bug, just the way it works. Plupload 3.x will bring simultaneous file and chunk uploads.

But to address your issue - you could simply enlarge the value for `chunk_size`, or turn it off completely. There's no benefit or speed boost for chunking. Chunks are required in some scenarios where they are required. Do not use them unless you require them.

**Comment by KalpanaPagariya** [comment]
Thanks. when 3.x will be available?

**Comment by denzils** [comment]
How soon will 3.x be available?
