### ISSUE TITLE
Not Able to Access Error Message For JSON Object

### ISSUE THREAD

**Issue by BernardA** [moxiecode/plupload#1349]
I have set up some PHP security checks on top of Plupload and generating error messages as it goes by using the same JSON-RPC notation as Plupload to be consistent. Though admittedly I am not quite familiar with this process.

An error message instance that I'm generating on the server side looks like this:

This is also how the console.log(response) looks like, so it is outputting it correctly to the browser.

`     $err_msg = '{"jsonrpc" : "2.0", "error" : {"code": 204, "message": "File type not supported. "}, "id" : "id"}';`

On the receiving PHP script, the Plupload script is configured as follows ( admittedly, this is generating another issue, ie, running twice,which I logged separately ).

         ` $('#uploader2').plupload('getUploader').bind('FileUploaded', function (uploader, file, info) {
         //alt 1 = THIS WORKS
         var err_msg = JSON.parse('{"jsonrpc" : "2.0", "error" : {"code": 204, "message": "File type not       supported. "}, "id" : "id"}');
         alert(info.error.code); // prints 204

         // alt 2 = GENERATES ERROR SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
         var err_msg = JSON.parse(info);

         // alt 3 = ASSUMING JQUERY IS ALREADY PARSING JSON
        alert(info); // gives object
         alert(info.error.code); // prints UNDEFINED 
         }`
I have tried a few different alternatives, as you can notice on the code:

In alt 1, just to test, I pasted the string directly on the script; in that case it works fine and I can access the object as expected.

In alt 2, I am assuming that I need to parse the JSON and so this is what's giving me the syntax error. Looking elsewhere on SO, I found that that error indicates that jQuery is already parsing the JSON, so it should not be done again.

In alt 3, I try to access the object as one normally would but get undefined.

Is there a different setup to parse JSONRPC? 

Thanks

**Comment by jayarjo** [comment]
JSON-RPC notation is not obligatory in any way. In fact we do not even use or depend on the server response. We leave it to user. So you can use any format that you like or need - JSON-RPC, JSON, XML, plain text. Just be sure to handle it appropriately in `FIleUploaded` and other event handlers.
