### ISSUE TITLE
IE8 doesn't support removing file from list

### ISSUE THREAD

**Issue by carlshe** [moxiecode/plupload#1350]
IE8 doesn't support removing a file from list. 
error occurs for removing a file:
Object doesn't support property or method 'slice'.

Hopefully this issue can be resolved as soon as possible.

Thanks!

**Comment by jayarjo** [comment]
Here is the playground where it works: http://play.mytunes.ge/y/4. Just add some images and try to remove it. No error there.

If you mean something different, could you create a playground for your case? It will be easier to troubleshoot.
