### ISSUE TITLE
How to AddFile using ActiveX in Plupload?

### ISSUE THREAD

**Issue by jdsxzhao** [moxiecode/plupload#1352]
My machine is connected with a scanner. The scanner can return a couple of images and I can get the paths of these images in the web page. Then I want to upload these images using Plupload plugin. Now I can get these file using ActiveX. But when I call the AddFile function, it doesn't work. It seems like the file returned by ActiveX is not suitable for the AddFile function. How can I do ?

`//scanFilePath such as:  D:\image001.jpg`

```javascript
var fso = new ActiveXObject("Scripting.FileSystemObject");
var f1 = fso.GetFile(scanFilePath);
var i_upload = $("#uploader").pluploadQueue();
var tmp = scanFilePath.split("\\");
var filename = tmp[tmp.length-1];
i_upload.addFile(f1, filename);
```

**Comment by jayarjo** [comment]
Plupload doesn't support `FileSystemObject` directly, but it accepts regular `Blob`, so if you could find a way to convert `FileSystemObject` to a `Blob`, you can make it work.
