### ISSUE TITLE
o.Image can not work with IE8 & Flash

### ISSUE THREAD

**Issue by cevin** [moxiecode/plupload#1354]
```
uploader.bind('FilesAdded',function(upload,files){
    if (upload.files.length > 10) {
        plupload.each(files,function(file){upload.removeFile(file);});
        alert('Max allow 10 files.');
    } else {
        plupload.each(files,function(file){
            var img = new o.Image();
            img.onload = function(){
                var html = document.createElement('li');
                html.id = this.uid;
                html.setAttribute('fileid',file.id);
                html.setAttribute('class','li');

                $(html).appendTo('#imgList');
                this.embed(html.id,{width:140,height:140,crop:true,quality:10,type:'image/gif'});
            };
            img.onembedded = function(_o){
                // file
                //_o.target
                var html = '<p id="progress'+file.id+'" class="progress">Uploading</p><a data-fileid="'+file.id+'" href="javascript:void(0);" title="Delete" class="close"><b class="ico m-user-shareAdd-icoClose"></b></a>';
                html = $(html);
                html.appendTo($("#"+_o.target.uid));
            };
            img.load(file.getSource());
        });
        uploader.start();
    }
});
```

The DOM will be 
```
<ul id="ImgList">
    <li id="uid" fileid="file.id"/>  <!-- no image label in li -->
</ul>
```

**Comment by jayarjo** [comment]
`image/gif` is not a supported image type currently, consider `png` or `jpeg` maybe.

I'm throwing together Plupload Playground site currently, which is available at http://play.mytunes.ge for now (it will be ported to play.plupload.com as soon as possible). Could you create a case there - it will be easier to troubleshoot. You can take this one as example: http://play.mytunes.ge/v/4

**Comment by cevin** [comment]
@jayarjo in china ,the site cannot be visit. :(
Eh, change image type as `image/jpeg`, the `embedded` it's okay, label `p` and `a` can display. But not display image thumb and will display a white box.

**Comment by jayarjo** [comment]
Crap, my deployment script just re-wiped the whole database. Hope you didn't close the page with your playground yet? Can you quickly copy/paste it to a fresh one? Just do not close it, as the its' not in database anymore...

Sorry.

**Comment by jayarjo** [comment]
Also if you depend on jQuery and jQuery UI (and you should, if you are using UI Widget) be sure to choose some old versions, since new ones have dropped support for older IEs.

**Comment by jayarjo** [comment]
Our playground site has move to a permanent location at: http://play.plupload.com.
