### ISSUE TITLE
Thinking of buying the license for PLupload and have a few questions 

### ISSUE THREAD

**Issue by landmarkads** [moxiecode/plupload#1358]
I want to make sure plupload will work for my one website. 
I am using MySQL Database and would like to upload up to 8 images to an "uploads" directory and also put the filenames of these images in MySQL database along with a user_id, etc.
1. Can I limit the number of images?
2. Do I use the $_FILES['image']['tmp_name'] or assign each image $image_1 variable to capture the name and path?
3. How to I retrieve these images into some sort of preview  form to possibly delete or add to them and also view on an html page?
4. I am not part of a company and am trying to develop one website. Do I have access to support?

Currently, I have written the php code and html5 form etc, but it only seems to grab one image, even when I use multiple as input type, etc.

**Comment by jayarjo** [comment]
Multi file selection should be available in HTML5 runtime. Please post your config to help troubleshoot your situation further. Or even better, create a fiddle on our new playground site: http://play.plupload.com and post a link to it here.

**Comment by jayarjo** [comment]
Plupload is just file uploader (with some secondary features).  Additional functionality can be programmed on top of our [Core API](https://github.com/moxiecode/plupload/wiki/API).
