### ISSUE TITLE
filters.mime_types miss image file which has an ending space in the file name

### ISSUE THREAD

**Issue by lucozhao** [moxiecode/plupload#1363]
On mac, there is a file named "test.jpeg " (there is a trailing space), mac can recognize this file as image file, but plupload filter this as non-image file. The filters.mime_types setting is as below

mime_types: [{title: 'Image files', extensions: 'jpg,jpeg,gif,png'}]

**Comment by HuColin** [comment]
There is the same problem on HUAWEI honor 6

**Comment by jayarjo** [comment]
Why would there be a space at the end of the file?
