### ISSUE TITLE
cannot init with dynamic DOM element

### ISSUE THREAD

**Issue by ExinCoda** [moxiecode/plupload#1365]
plupload is a great tool but I come up with problem when using plupload with AngularJS and Angular Material.
And i don't know it is an issue of plupload or Angular Material, so i'd submit issues on both sides.

There is no initiating message shown in the console when the page is loaded. I guess there is something wrong when pluploader searching for the elements.

[JSfiddle](https://jsfiddle.net/ksygdygo/2/)

**Comment by ExinCoda** [comment]
it's an Angular Material's issue. thanks for your time.

**Comment by jayarjo** [comment]
Just be sure that dynamic DOM element already exists by the time you initialise Plupload.
