### ISSUE TITLE
Memory issue on IE11 with big files

### ISSUE THREAD

**Issue by hoetz** [moxiecode/plupload#1368]
When I try to upload a 800MB file with the HTML5 uploader I can see in the task manager that it consumes large amounts of ram. At about 75% the download stops with a HTTP error.

When I try it on chrome it works just fine and the ram usage is low. Is this a known issue?

**Comment by jayarjo** [comment]
Do you use chunking?

**Comment by hoetz** [comment]
Yes I use chunking and I have only enabled the HTML5 component, nothing else.

**Comment by jayarjo** [comment]
Can you post your config? I will try to repeat it.

**Comment by hoetz** [comment]
Sure

 $("#Uploader").pluploadQueue({
             runtimes: 'html5,html4',
             url: 'plUploadFileHandler.ashx',
             max_file_size: '<%=this.maxFileSizeMB.Value%>mb',
             chunk_size: '65kb',
             unique_names: false,
             // Resize images on clientside if we can
             // Specify what files to browse for
             multiple_queues: true
         });

         // get uploader instance
         var uploader = $("#Uploader").pluploadQueue();

         uploader.bind("Error", function (upload, error) {
             alert(JSON.parse(error.response).error.message);
         });
         var files_remaining = 0;
         uploader.bind('QueueChanged', function (up, files) {
             files_remaining = uploader.files.length;
         });

         uploader.bind('FileUploaded', function (up, file, res) {
             files_remaining--;
             if (files_remaining == 0) {
                 AllFilesFinished();
             }
         });

**Comment by hoetz** [comment]
Update: I was able to improve the situation by increasing the chung size to 260kb. The memory usage on IE11 is still way higher than on Chrome.
