### ISSUE TITLE
How to modify plupload to send multiple chunks on a single request to backend?

### ISSUE THREAD

**Issue by denzils** [moxiecode/plupload#1369]
plupload sends a request for every chunk on the server. How can I modify plupload so that it sends multiple chunks on single request to the backend? I know that this functionality will be available with Plupload 3.x as stated in this issue thread: https://github.com/moxiecode/plupload/issues/1347 but it does not make clear when that will be available to users. 

I am wondering if there is a temporary hack or change I can do to make this possible until v3.x releases?

**Comment by AngelRodRo** [comment]
You could send set a size larger piece to send and so do not have to wait for many pieces will send

**Comment by denzils** [comment]
Thank you for responding! I'm not sure setting the chunk size to be larger will solve the issue, and I'm not sure I understood your response? Can you elaborate?

**Comment by AngelRodRo** [comment]
I mean when the options are placed on the uploader instance there is a option that is ' chunk -size' default is 256kb , you can modify it to make it more and have longer chunks @denzils 

`    
    var uploader = new plupload.Uploader({
    chunk_size : '200kb',
    max_retries:25,
    url:'/myUrl',
    browse_button:'myButton'
`

**Comment by denzils** [comment]
Will that fix the problem of sending the multiple chunks as a single request? The single request is our main concern. One request for every chunk does not work for our scenario - We are already trying to send large chunk-sizes (25MB) but currently it is sending multiple requests for multiple chunks instead of a single request for multiple chunks. I see in #1347 that Plupload 3.x will bring simultaneous file and chunk uploads and that sending over a single request will be an option. However, it is not clear when Plupload 3.x will be available and I'm not sure the code you provided above is fixing the specific single request issue. Did I misunderstand how the max_retries parameter works? Will Plupload be able to provide us this functionality soon or should we be looking into other modules? Thank you for the quick responses! Hope to figure something out that works.

**Comment by denzils** [comment]
Re-pinging - What is a way for us to send multiple chunks as a single request?

**Comment by jayarjo** [comment]
@denzils I'm afraid this is not possible in Plupload 2, for number of reasons. Plupload 3 is in beta right now.

But in any case you will need some additional measures on server-side for this to work correctly, as you won't be guaranteed anymore that chunks will arrive in sequential order.

**Comment by Thunder7991** [comment]
> @denzils I'm afraid this is not possible in Plupload 2, for number of reasons. Plupload 3 is in beta right now.
> 
> But in any case you will need some additional measures on server-side for this to work correctly, as you won't be guaranteed anymore that chunks will arrive in sequential order.

I feel that there should be no need to consider the issue of sorting. After the upload is completed, the files can be sorted again and then merged. So far, some frameworks default to sorting .  Is this library currently not maintained? I still hope that contributors can add this feature
