### ISSUE TITLE
Cannot read property 'moxie' of undefined ?

### ISSUE THREAD

**Issue by wendaosanshou** [moxiecode/plupload#1374]
there are a error message when i introduced the file `plupload.full.min.js`.

```
Cannot read property 'moxie' of undefined ?
```

why would report this error message ?

**Comment by Docyue** [comment]
i got the same error in webpack use es6; 
anyone had get a solution?

**Comment by learntocoderight** [comment]
I think I have it working but I haven't fully tested it yet.

I had to change the following chunks of code in `moxie.js` from using `this` to using `window`. Final code looks like this:
```javascript
(function(exports) {
    ...
})(window)
```
```javascript
expose(...)(window);
```
You can also find and change those lines in the minified version in `plupload.full.min.js`:
```javascript
a([u,c,l,d,h,f,p,m,g,v,w,y,E,_,b,x,R,A,I,T,S,O,N])}(window);
```
```javascript
return JSON.parse(...)(window);
```

Note: I do not fully understand why it works or what the implications are of making those changes. If someone could explain it that would be great. It would also be nice if the code was updated to properly support a proper webpack include without changes.

The idea came from issue 154 from the moxiecode/moxie repo. [#154](https://github.com/moxiecode/moxie/issues/154)

**Comment by jayarjo** [comment]
There's a proper AMD/CommonJS wraper now in [v2.2.0](https://github.com/moxiecode/plupload/releases/tag/v2.2.0).

And we've finally published Plupload on NPM, so `npm install plupload` should also work.
