### ISSUE TITLE
.xlsx files are disabled in Mac safari 9.1+

### ISSUE THREAD

**Issue by vamshikumarpunjari** [moxiecode/plupload#1384]
(https://cloud.githubusercontent.com/assets/20185434/16412958/9d9c1e0e-3d4c-11e6-8338-d0d2645204fe.jpg)

.xlsx extention files are gettimg disables when trying to upload into one of our appliction.

**Comment by jayarjo** [comment]
Recent versions of Plupload do not rely on mime-types anymore and filter by extension directly. So this shouldn't be a problem anymore.
