### ISSUE TITLE
plupload.full.min.js,line15 character9601, SCRIPT16389: Unspecified error. 

### ISSUE THREAD

**Issue by lilyAlucy** [moxiecode/plupload#1385]
hi, all:
I have a problem of plupload.full.min.js,line15 character9601, SCRIPT16389: Unspecified error in ie9 and ie8.  I try the latest version or v1.2.1 also have this problem. how can i solve this problem?

**Comment by jayarjo** [comment]
Do you mean v2.1.2?

Try to load unminified versions of scripts (moxie.js and plupload.dev.js) that come with the package and see if you get more meaningful error.

**Comment by lilyAlucy** [comment]
@jayarjo  I try all the versions to have the same problem. I console.log the runtime, it use flash rumtime. I debug to find the following tips:

![flash](https://cloud.githubusercontent.com/assets/9443129/16447036/1d2d5bee-3e1d-11e6-8369-f5e92d21b870.png)

How can I solve this?

**Comment by jayarjo** [comment]
It doesn't seem to be a regular case. We have a playground here: http://play.plupload.com/, can file your case and post a link here? We will troubleshoot it.
