### ISSUE TITLE
Plupload browse button to open specific location

### ISSUE THREAD

**Issue by BakuDev** [moxiecode/plupload#1387]
Dear plupload team!
I'm wondering if it is possible to make the browse button to open specific location?
On some Android devices it opens menu of the device' default file explorer where you have to walk across folders to search for the files to upload. On others devices this menu is another (I understand it depends on UI and settings of every device). Is it possible to make browse button to open, for example, the folder of device's gallery? Or to specify an array of OS with default paths for each?

**Comment by jayarjo** [comment]
We do not have control over this. I believe it automatically opens the last used location.
