### ISSUE TITLE
Chrome / Webpack - Cannot read property 'moxie' of undefined

### ISSUE THREAD

**Issue by matt-paul** [moxiecode/plupload#1392]
Previously, plupload has been successfully used via a script tag.   However, now I try to require it within an es6 webpack module, like below..
`
require('script!./../../../static/js/plupload.full.min.js');`

i receive the following error

`Uncaught TypeError: Cannot read property 'moxie' of undefined`

```
               r[a[u]] === t && (r[a[u]] = {}),
                r = r[a[u]];
            }
            r[a[a.length - 1]] = s[o];
        }
    }
    var s = {}
      , u = "moxie/core/utils/Basic"
      , c = "moxie/core/I18n"
      , l = "moxie/core/utils/Mime"
```

**Comment by matt-paul** [comment]
In safari, i receive the following error

`TypeError: undefined is not an object (evaluating 'a[u]')`

**Comment by matt-paul** [comment]
Apologies, realised that this is a duplicate of #1374

**Comment by jayarjo** [comment]
Update in: https://github.com/moxiecode/plupload/issues/1392
