### ISSUE TITLE
Uncaught Error with flash runtime in chrome

### ISSUE THREAD

**Issue by 0x2e** [moxiecode/plupload#1394]
![snip20160724_1](https://cloud.githubusercontent.com/assets/1448791/17083071/3c0edabc-51c6-11e6-9d57-b5d3a8e6b7c6.png)

**Comment by jayarjo** [comment]
Regular `Moxie.swf` is not CDN friendly (for security purposes). We do bundle CDN friendly version in the Plupload package though - `Moxie.cdn.swf`. Try it instead.
