### ISSUE TITLE
Windows 10 Edge browser cannot upload file named app.log.2016-07-27

### ISSUE THREAD

**Issue by lucozhao** [moxiecode/plupload#1395]
This works on Mac Chrome browser, but cannot work on edge. Tried the file on http://www.plupload.com/examples/, it doesn't work either. Finally I had to rename the file to app20160727.log to get it uploaded. Suspect dash in the file name caused the issue. Please help check.

**Comment by jayarjo** [comment]
I think it simply expects extension to be the last thing in the filename.
