### ISSUE TITLE
android upload not open 

### ISSUE THREAD

**Issue by spencer-live** [moxiecode/plupload#1398]
Part android system can not open the photo album outside of the camera's buttons do not use; enter from the gallery, all pictures show a disabled state. Will this be related with the system settings?

部分安卓系统无法打开相册以外的照片也没有使用相机的按钮；从图库进入, 所有图片显示禁用状态。请问这个跟系统设置有关吗？

**Comment by jayarjo** [comment]
If you have any filter in your Plupload config, disable them. Otherwise it is something in the system.
