### ISSUE TITLE
Setting file name with drop target

### ISSUE THREAD

**Issue by szepeviktor** [moxiecode/plupload#1399]
`formData.append(up.settings.file_data_name, chunkBlob);`
https://github.com/moxiecode/plupload/blob/v2.1.8/src/plupload.js#L1488

I think it is not possible to set the file name because that would be the 3rd paramter.

`void append(USVString name, Blob value, optional USVString filename);`
https://xhr.spec.whatwg.org/#interface-formdata

Do you plan to implement that?

**Comment by szepeviktor** [comment]
I mean the XHR `filename` attribute.

```
------WebKitFormBoundaryrtDKCzluhfCGm8ra
Content-Disposition: form-data; name="async-upload"; filename="hibernation.jpg"
Content-Type: image/jpeg

```

**Comment by szepeviktor** [comment]
Oh! But that FormData is not from a browser but from moxie.
https://github.com/moxiecode/moxie/blob/f4dfe0bd86c98df1efa79d2e2a4dc06cb4250fcf/src/javascript/xhr/FormData.js#L33

And moxie does not implement `filename`.

Please advise.

**Comment by jayarjo** [comment]
You can set file name on moxies File object before you feed it to moxies FormData.

**Comment by szepeviktor** [comment]
Thank you.
