### ISSUE TITLE
can I add http request headers  when upload file

### ISSUE THREAD

**Issue by ShangXinbo** [moxiecode/plupload#1400]
I need to add a auth token in http request headers ,if this plupload surport like jquery $.ajax({headers:{}})?how can i do?

**Comment by clywind** [comment]
Like this：

**Comment by clywind** [comment]
var uploader=new plupload.Uploader({
                      headers:{token:'token'},
                     .......
});

**Comment by jayarjo** [comment]
@ShangXinbo please close this ticket, if @clywind suggestion is sufficient.
