### ISSUE TITLE
How can I rebuild this to cmd moudles?

### ISSUE THREAD

**Issue by clywind** [moxiecode/plupload#1401]
rebuid it to cmd moudles  for seajs use..

**Comment by jayarjo** [comment]
If you know what you are doing you could wrap it quickly yourself. Currently we do not provide it ourselves. But I'm thinking to incorporate a wrapper for AMD, CJS and apparently CMD as well for Plupload 3, that is in beta at the moment.

**Comment by jayarjo** [comment]
AMD/CommonJS support now in [v2.2.0](https://github.com/moxiecode/plupload/releases/tag/v2.2.0).
