### ISSUE TITLE
Preloading thumbnails doesn't work in 3.0-beta1

### ISSUE THREAD

**Issue by Petyk** [moxiecode/plupload#1406]
Error:
plupload.Image is not a constructor
on this line:
var img = new plupload.Image(); (function preloadThumb)

**Comment by Petyk** [comment]
Anybody with the same problem?

**Comment by robfaas** [comment]
Yes, me too!

**Comment by bhuvidya** [comment]
Oh wow thanks so much everyone for tracking this down and allowing me to do a patch to fix the issue. I would never have worked this out on my own.
