### ISSUE TITLE
why flash or silverlight is not work in ie9?

### ISSUE THREAD

**Issue by moahmn** [moxiecode/plupload#1408]
i set  flash_swf_url : '/admin/third-party/plupload-2.1.8/js/Moxie.swf' and silverlight_xap_url : '/admin/third-party/plupload-2.1.8/js/Moxie.xap',but the plupload use html4 to upload  in ie9 ,that's why?

this is my option 
```javascript
 var uploader = initPlupload({
            url:fileUploadUrl,
            browse_button : options.selectBtn,
            flash_swf_url : '/admin/third-party/plupload-2.1.8/js/Moxie.swf',
            silverlight_xap_url : '/admin/third-party/plupload-2.1.8/js/Moxie.xap',
            init: {}
})
```

**Comment by jayarjo** [comment]
Are you sure those paths to `swf` and `xap` shims are correct?

**Comment by moahmn** [comment]
![qq 20160928100859](https://cloud.githubusercontent.com/assets/11703322/18898354/d1ff6994-8563-11e6-9eae-1c2e2d89f210.png)

that's my code list;i think path is correct?

i meet #1267 problem,i think if i use rumtime flash success,the problem is fixed?
'

**Comment by jayarjo** [comment]
I can't tell if the path is correct or not like this. Copy/paste it into your browsers address bar and see if `swf` gets retrieved.

There are only two reasons why Flash might not initialize: 
1. path is not correct
 2. your browser either doesn't have Flash plugin or it is outdated

As for #1267 problem, solution is described in that thread.
