### ISSUE TITLE
Non image files are greyed out on iOS mobile (iPhone/iPad)

### ISSUE THREAD

**Issue by benebol** [moxiecode/plupload#1410]
When applying a filter to a **mix of image types and other file types**, it is not possible to upload non image files on **iOS mobile**, the files are **greyed out** 
This issue only occurs when applying a custom filter (ex: 'png,jpg,jpeg,docx,xlsx').
You can simply reproduce the issue on iOS mobile, by uploading any file at the [example page of the plupload website ](http://www.plupload.com/examples/).
A simple workaround is to add a non existing extension in the extensions filter (ex:'png,jpg,jpeg,docx,xlsx,iosfix')

**Comment by jayarjo** [comment]
Which iOS version is it?

**Comment by benebol** [comment]
I had the issue on both, iOS 9 & 10

**Comment by jayarjo** [comment]
If it's still an issue, I'd suggest to remove the filter altogether, since it's something that is beyond our control.
