### ISSUE TITLE
Adding files to existing form and submit without AJAX?

### ISSUE THREAD

**Issue by burzum** [moxiecode/plupload#1411]
Is it somehow possible to add files, that were added via plupload and a droparea, to the actual form? I don't want to submit the files in separated AJAX requests but together with the rest of the form so that it would submit as it would be a regular non-AJAX form.

**Comment by jayarjo** [comment]
Why would you want to use a Plupload then? Simply add regular `input[type="file"]` fields to your form and that should do.
