### ISSUE TITLE
testing plupload with capybara/selenium not generating 'change' event

### ISSUE THREAD

**Issue by hassaniftikhar** [moxiecode/plupload#1412]
I have integrated plupload with my rails application and it is working fine in production and development, but while I am writing test cases using capybara/selenium 
I tried using capybara helper method attach_file which attaches the file to input element but it is not triggering the 'change' event and thus I dont get back 'FilesAdded' event

here are the stack details
selenium-web(2.53.4)
capybara (2.7.1)
FireFox (49.0.1)

has anyone faced the same problem or a little guidance will be a great help, thanks.

**Comment by jayarjo** [comment]
We could not find a clean enough way to test file picker either. Basically because it is not possible to programmatically trigger browse dialog in Flash/Silverlight and some legacy browsers (we got to take them into account).

**Comment by hassaniftikhar** [comment]
@jayarjo thanks for the reply.
I was able to solve the problem by using the poltergeist (1.10.0) gem and it is generating the required  event.

**Comment by jayarjo** [comment]
Glad you found a solution. I will close this one then.
