### ISSUE TITLE
windows系统，遨游浏览器兼容性问题！

### ISSUE THREAD

**Issue by zhuhaibo1107** [moxiecode/plupload#1415]
windows系统，遨游浏览器兼容性问题！

**Comment by zhuhaibo1107** [comment]
例：如果 【上传】 按钮是在一个（display：none）的div元素中，当这个div元素显示之后，点击上传按钮没有触发上传事件！！（该BUG发生在windwos系统的遨游浏览器上）

**Comment by jayarjo** [comment]
Sorry, could you post a name of the browser in which it fails? And maybe a link where we could download it?

**Comment by huangxiangsai** [comment]
@zhuhaibo1107 

先调侃下你，你确定作者看的懂中文。哈哈

再来猜测下，你问题可能的情况， 你可能在使用flash模式上传，在flash初始化的时候，如果元素是隐藏(display:none之类)的，会使得flash失效。

解决方法： 可以修改隐藏的方式，不使用`display:none`改成宽高设置为0。

如猜测不正确，还望勿怪。
