### ISSUE TITLE
Plupload v1.2.1 - Security Error in only IE server deploy.

### ISSUE THREAD

**Issue by rai0101** [moxiecode/plupload#1422]
I added the latest Plupload to my website, it worked in my machine. But when I deploy in server, there have an issue "HTTP Security Error". The weird thing is just trouble only in IE browser at the deploy server, I published my web site to public, the upload file worked in all of browser in client machine.
The IE browser I tested in server is IE11. I think it related to security file in server. Please help me, thanks.

**Comment by jayarjo** [comment]
You shouldn't be using v1.2.1. It's deprecated. For quite some time actually.
