### ISSUE TITLE
Feature request:  Button to stop uploading

### ISSUE THREAD

**Issue by montalalimited** [moxiecode/plupload#1428]
I wondered if I could place a feature request.  Our system uses PLUpload for multiple file uploads.  Currently, if a user sets an upload on our system with a large quantity of photos, then, for whatever reason, if this has been set in error and they want to cancel the entire upload (move to another folder, change of criteria (private), etc. they cannot stop it but have to wait until done to then delete.  So I wondered if it would be possible to add a button that would cancel the entire bulk upload.

Many thanks in advance,

Emma

**Comment by jayarjo** [comment]
Hi Emma, in fact it is already possible to cancel current upload and our widgets have a corresponding button. Could you post your Plupload initialization code, for me to advice you further?
