### ISSUE TITLE
WRONG_FORMAT: ImageError 1

### ISSUE THREAD

**Issue by ShangXinbo** [moxiecode/plupload#1429]
I change the extension of a gif to a jpg.when I upload this jpg, plupload throw a error like that
`{code: 1, name: "WRONG_FORMAT", message: "WRONG_FORMAT: ImageError 1"}`
how can I prevent that?

**Comment by jayarjo** [comment]
What version of Plupload you are using?

**Comment by ShangXinbo** [comment]
version 2.2.0

**Comment by jayarjo** [comment]
Can you post your Plupload config? 'cause I can't reproduce that error.

**Comment by ShangXinbo** [comment]
I think this issue has nothing to do with my config. Look this picture(http://zhongxin.kameng.com/data/image/creditcard/20130409-77380718.jpg) . If you want to reproduce this issue,you should download this pic and upload it with plupload.And then you will got a same error message.

**Comment by ShangXinbo** [comment]
I review the code and find this 
`if (!~Basic.inArray(src.type, ['image/jpeg', 'image/png'])) {
						throw new x.ImageError(x.ImageError.WRONG_FORMAT);
					}`
I don't think this is a bug,but I want to prevent this error.

**Comment by jayarjo** [comment]
I've published v2.2.1, that should have this fixed.
