### ISSUE TITLE
runtime html4 not support mOxie?

### ISSUE THREAD

**Issue by ShangXinbo** [moxiecode/plupload#1431]
can I use mOxie by runtime html4?

**Comment by jayarjo** [comment]
Yes. mOxie provides all the runtimes to Plupload.

**Comment by ShangXinbo** [comment]
@jayarjo  But I use "runtimes : 'html4'",  then new mOxie.FileReader() and I got mOxie is undefined

**Comment by ShangXinbo** [comment]
maybe mOxie or moxie, Uppercase or lowercase.

**Comment by jayarjo** [comment]
FileReader is not supported by `html4`. But the error that you get is unrelated. In default build we got rid of `o.` and `mOxie.` namespaces, 'cause users were complaining that we were polluting global namespace with aliases.

`FileReader` can be accessed through `moxie.file.FileReader()`.

If you still require mOxie namespace, [repository](https://github.com/moxiecode/moxie) should be compiled with `compat=yes` argument. Or you can simply use v2.1.9 (we will be releasing a bugfix release v2.2.1 these days anyway).

**Comment by ShangXinbo** [comment]
thanks，I get the solution!
