### ISSUE TITLE
Upload not working on firefox with large files

### ISSUE THREAD

**Issue by SakocheDrop** [moxiecode/plupload#1432]
Bonjour,

i am using plupload on my website to upload larges file till 10Gb divided by chunk of 1Gb.
On chrome it works well. 
But on firefox it seems that plupload plugin do not upload the files.
In the console,  details of the request post is empty nothing is sended.
The same problem appers on Safari. I did not test on IE  yet ..
Is there a known issu with firefox and chunks or something like that ?
I think the problem is linked to the chunks because under 1Gb files are well uploaded.

Thank u for your answers and sorry for my english.

**Comment by jayarjo** [comment]
I should say I never tested chunks of such size. It might be that firefox itself fails to slice them.

**Comment by SakocheDrop** [comment]
I should  slice files with  smaller chunks like 500Mo you think  ? I am going to try this.

**Comment by SakocheDrop** [comment]
I have tried with smaller chunks, the max size of the chunk that i can apply to make the upload works is 250MB on Firefox and safari it is slower but it works.
Thank u jayaro.
