### ISSUE TITLE
Plupload not working with IPv6.

### ISSUE THREAD

**Issue by KalpanaPagariya** [moxiecode/plupload#1436]
https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/plupload/plupload.full.min.js:14 XMLHttpRequest cannot load https://[2a07:2/vm-mgmt-api/UploadAction. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.send @ https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/plupload/plupload.full.min.js:14exec @ https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/plupload/plupload.full.min.js:13shimExec @ https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/plupload/plupload.full.min.js:13exec @ https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/plupload/plupload.full.min.js:13r @ https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/plupload/plupload.full.min.js:14u @ https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/plupload/plupload.full.min.js:14send @ https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/plupload/plupload.full.min.js:14p @ https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/plupload/plupload.full.min.js:29k @ https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/plupload/plupload.full.min.js:29dispatchEvent @ https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/plupload/plupload.full.min.js:29trigger @ https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/plupload/plupload.full.min.js:13g @ https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/plupload/plupload.full.min.js:29start @ https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/plupload/plupload.full.min.js:29VM.view.fileuploader.UploadBrowseFile#PluploadFilesAdded @ https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/app/view/fileuploader/UploadBrowseFile.js?_dc=1481620983…:242dispatchEvent @ https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/plupload/plupload.full.min.js:29trigger @ https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/plupload/plupload.full.min.js:13(anonymous function) @ https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/plupload/plupload.full.min.js:29(anonymous function) @ https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/plupload/plupload.full.min.js:13
https://[2a07:2a42:adc0:1d::81]/vm-mgmt-ui/js/utils.js:4 Error in PL upload!!

**Comment by jayarjo** [comment]
That's not informative at all. I guess you better describe what has happened in your own words.

**Comment by KalpanaPagariya** [comment]
Ok. Actually we have enabled IPv6 on our system. Now while trying to login using IPv6, we use below format of URL:
https://[2a07:2a42:adc0:1d::81]/network-login/

Now what is happening after this when we try to browse the document, it failed. As per the console logs, what we can understood is somehow PLUpload is trying to build url as below to call servlet: (where u can see IPv6 address has come completely. 
**https://[2a07:2/vm-mgmt-api/UploadAction**

Now u can see in the above url formed by plupload. then below error we can see in console:
XMLHttpRequest cannot load https://[2a07:2/vm-mgmt-api/UploadAction. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.send

**Comment by jayarjo** [comment]
Ok, I see why it fails now. Need to bear it in mind for some time. Easy fix for this though, would be to map ip to domain and use domain instead.

**Comment by KalpanaPagariya** [comment]
Thanks. But as per our application requirement, we allow user to login with IPv6 also. We cannot restrict only for domain use. Can you suggest solution for this?

**Comment by KalpanaPagariya** [comment]
Is there any update on this?

**Comment by KalpanaPagariya** [comment]
Can you please help on this? This is very important and urgent.

**Comment by 201510Zong** [comment]
We have the same problem with IPv6.
google chrome error:
`https://[2001:2002:2003:2004:2005:2006:c0a8:bc]/js/csrf.jst:80 Uncaught SecurityError: Failed to execute 'open' on 'XMLHttpRequest': Refused to connect to 'https://[2001:2002/action/uploadFile?referrer=maintenance_update.asp&extendupload=1' because it violates the document's Content Security Policy.`

**Comment by jayarjo** [comment]
This has been addressed in: [moxiecode/moxie@b01cd60](https://github.com/moxiecode/moxie/commit/b01cd601140ec37a387d85180e5dcc73af579fbd?w=1). However it will only be released with 2.3, which is almost ready. For now you could [build moxie](https://github.com/moxiecode/moxie#compile-js) yourself and substitute Pluploads version with your own.

**Comment by KalpanaPagariya** [comment]
Not able to understand this build moxie. Instead of that I am planning to change the regex in plupload.min.js file which we are using? will it be ok?

**Comment by 201510Zong** [comment]
I change the regex in plupload.min.js.
Run normally, upload successfully.

**Comment by jayarjo** [comment]
@KalpanaPagariya, yes, if you can find it there.

**Comment by KalpanaPagariya** [comment]
We have taken OEM license, and doing fixes in plupload file. (this will go in production) Will it require to do something legally from our end?

**Comment by jayarjo** [comment]
@KalpanaPagariya no. You are free to make fixes and use it accordingly. In case you find it appropriate to contribute back, I'd gladly consider pulling it in as well.
