### ISSUE TITLE
Move all npm dependecies to devDependencies

### ISSUE THREAD

**Issue by eugef** [moxiecode/plupload#1437]
If i want to use plupload in my project and install it via npm, then l also get all the dependencies from the`package.json` that are not needed at all. (`jake`, `glob`, etc)

All dependencies can be safely moved to `devDependencies` section as they are needed only if you develop `plupload` itself.

**Comment by jayarjo** [comment]
@eugef we did move them on [2.2.x branch](https://github.com/moxiecode/plupload/blob/2.2.x/package.json).

**Comment by eugef** [comment]
@jayarjo Great, any plans to release soon?

**Comment by jayarjo** [comment]
Yes, this week probably.
