### ISSUE TITLE
Drag and drop order

### ISSUE THREAD

**Issue by winter69** [moxiecode/plupload#1439]
When I drag and drop a list of files selected in MS File Explorer, the order depends on where the mouse pointer is located when the drag begins i.e if you have the mouse pointer in the middle of the list, the order of the items when dropped will start in the middle of the list and go to the last item and then start at the beginning and go to the item before the middle of the list.  I have included a screenshot which hopefully explains things better - the mouse pointer is not captured but assume it is hovering over the File Explorer entry "008 Chester A. Arthur.png" when the drag begins
![screen](https://cloud.githubusercontent.com/assets/14207307/21639493/446eba88-d268-11e6-9328-ae3b4b247583.png)
.  I have tried this on both Edge and Chrome with the same results.  I'm not sure if this is expected behaviour or not?

**Comment by jayarjo** [comment]
It is expected. We do not have control over this unfortunately.
