### ISSUE TITLE
plupload taking lot of time in uploading 2.5 GB file in IE11

### ISSUE THREAD

**Issue by KalpanaPagariya** [moxiecode/plupload#1441]
plupload is taking lot of time in uploading 2.5 GB file in IE11. but on FF and chrome, it is faster.

**Comment by jayarjo** [comment]
Can you post your config? There are several reasons why it might be happening. But in general it shouldn't.

**Comment by KalpanaPagariya** [comment]
Config of what?

 selectLbl :'',	      
	      browseBtnId:'',
	      browseLableCls :'', 
	      multi_selection_browse : false,
	      runtimes : 'html5,html4',
	      chunk_size : '4mb',
	      max_file_size : '20000mb',
	      url : "/UploadAction",
	      loadingFromScreen:'',
	      extjsPanelId:'',
	      multipart :true,
	      addedFiles:[],
	      uploadLocUnderRootDir:'',
	      loadingFromScreen:'',
	      extjsUploadedFileFieldSet:'',
	      cancelUpload:true,
	      filters : [{
	          title : "Image files",
	          extensions : "jpg,gif,png"
	        }, {
	          title : "Zip files",
	          extensions : "zip,avi,ova,bin,cert,pki"
	        }],
	        max_file_count : null,

**Comment by jayarjo** [comment]
Basically it all boils down to capabilities of the browser to slice file to chunks and upload them. IE11 might be simply slower at doing this.

If you plan to upload big files regularly, I'd suggest to increase the `chunk_size` to something bigger, like `100mb` for example.
