### ISSUE TITLE
file choosed with noresponse：2.2.1

### ISSUE THREAD

**Issue by HXO-OXH** [moxiecode/plupload#1442]
ios、PC没问题；andriod系统的微信中只能选择png图片，选中jpg图片后没反应

**Comment by HXO-OXH** [comment]
jpg file choosed with noresponse: in andriod

**Comment by HXO-OXH** [comment]
# # @ @ @walter

**Comment by colorwin** [comment]
@jayarjo Hope help.
Same here, some android phones in  wechat's inner browser will stuck some problems: 
1. No response after file choose. 
2. Can't use system album. 
3. Click the file button but no  response.
#1397 
[Chinese discuss](https://www.zhihu.com/question/54623070)

**Comment by jayarjo** [comment]
@HXO-OXH have you tried solution from: https://www.zhihu.com/question/54623070?

**Comment by jayarjo** [comment]
Closing this as duplicate for: #1397.
