### ISSUE TITLE
Load order when images are being added from server

### ISSUE THREAD

**Issue by steeleauto** [moxiecode/plupload#1443]
Hi, I have my images loading from a server. The images are named numerically ie: 1.jpg, 2.jpg
They load in the preview window fine but the order they load in is random. I can't seem to sort them so when the preview window is displayed the images are in the correct numeric order. any idea what is going on? when the images are being retrieved from the server they are being requested in the correct order I can see through firebug.

Code for external loading of images to preview:
```javascript
$(document).ready(function(){

  plupload = $("#uploader").plupload('getUploader');    
  var files = new Array();
  
  <?php foreach($vehicle->images as $key => $val){ ?>
      files.push('<?php echo $val; ?>');
    <?php } ?>     
     
    files.forEach(function(entry) {
        var img = new mOxie.Image();
        var url = o.resolveUrl("/media/used_vehicles/<?php echo strtolower($vehicle->id);?>/full/" + entry + "");
            img.onload = function() {
                plupload.addFile(img.getAsBlob());
            } //end image onload
        img.load(url);
        
    });

    for(var i = 0, upPreviousSize = plupload.files.length - files.length, size = files.length; i < size; i++) {
      files[i]["initialIndex"] = (i + upPreviousSize) * -1;
    }       
});
```

**Comment by jayarjo** [comment]
Obviously whichever image loads first also displays first, since your code handles them in parallel. If you want to preserve order you should handle them sequentially - not load second image until first is not done. But it is generic javascript topic and not Plupload issue.

Also I don't quite understand what are you doing there. By using `plupload.addFile` you re-adding the file to the queue and it will re-uploaded once you start the uploader. Is it what you expect?

**Comment by steeleauto** [comment]
I did sort out the answer loading sequentially

It's for used cars site
You create the car record, upload pics but you may need to edit the car details, add pics, delete pics etc
Problem was the sort changed each time and there may be 50 pics so your hero pic may have moved from first to 10th and now the first pic showing online may be a tire instead of the beauty shot

Otherwise was working perfect. Great solution and now it's spot on

Thx todd




On Feb 1, 2017, at 1:10 PM, Davit Barbakadze <notifications@github.com<mailto:notifications@github.com>> wrote:


Obviously whichever image loads first also displays first, since your code handles them in parallel. If you want to preserve order you should handle them sequentially - not load second image until first is not done. But it is generic javascript topic and not Plupload issue.

Also I don't quite understand what are you doing there. By using plupload.addFile you re-adding the file to the queue and it will re-uploaded once you start the uploader. Is it what you expect?
