### ISSUE TITLE
Option to select folder in Chrome

### ISSUE THREAD

**Issue by shershen08** [moxiecode/plupload#1444]
In Chrome 21+ the file API available to select whole folder with following:
`<input type="file" name="files[]" multiple directory webkitdirectory>`

more on that here: https://developers.google.com/web/updates/2012/07/Drag-and-drop-a-folder-onto-Chrome-now-available

Is that possible to configure the plugin to work like this?

**Comment by jayarjo** [comment]
It is supported by underlying core engine - [moxie](https://github.com/moxiecode/moxie). But is not implemented in Plupload. The problem with the folder picker is that it cannot pick files when it is configured as folder picker. So one will need two separate buttons, or a dropdown with two separate options.

Are you using a widget or Plupload core directly?

**Comment by shershen08** [comment]
@jayarjo the core functions are just fine. But sometimes user doesn't know what's he or she going to upload, so. But yeah it's totally solvable with UI you've proposed.
