### ISSUE TITLE
requests increased if I use chunking

### ISSUE THREAD

**Issue by mus-int** [moxiecode/plupload#1446]
hi
I have used plupload for long time and everything was going well.
Few days ago I decided to use Chunking for a large file and It's working.
I test upload like this:
```
chunk_size: '1mb'
max_file_size: '2mb'
```
and my files size were < _1mb_.
I look at the console to see number of requests:
when I upload first file I got one request
second file  >>> two requests
third file  >>> 3 requests
fourth file   >>>> 4  requests

I looked at response of each request and what I saw that each chunk was sent more than one after uploading second file.
It was multiply after each request

so the problem is the requests for each chunk multiply.
even the [example](http://www.plupload.com/examples/ui) on main website has same issue
Any help or suggestion please ?

**Comment by jayarjo** [comment]
Seems a problem with 2.3.0. Can confirm that you do not observe such issue in previous versions?

**Comment by mus-int** [comment]
I made a test on plupload v2.1.2 and it worked perfectly.

**Comment by jayarjo** [comment]
I've actually published v2.3.1 right away, since this was basically a breaking regression. Could you try it out?

**Comment by mus-int** [comment]
Have you made a test ? [link](http://www.plupload.com/examples/ui)
because I can't upload any file.

**Comment by jayarjo** [comment]
It seems to be a minification bug there (not sure why uglify did that). Try dev version.
