### ISSUE TITLE
Multiple Browse Button Depressions

### ISSUE THREAD

**Issue by plippard** [moxiecode/plupload#1447]
If I initialize the plupload.uploader and then depress the browse_button... the uploader will work fine until the 3rd attempt at reuse at which point I receive an exception.  This is occurring with version 2.3.0 as downloaded from the pluploader web site.  Version 2.1.2 works fine.

**Comment by jayarjo** [comment]
Related: https://github.com/moxiecode/plupload/issues/1446.

**Comment by jayarjo** [comment]
There was a regression, that we now fixed and released 2.3.1.
