### ISSUE TITLE
in IE8, property of opacity is not work

### ISSUE THREAD

**Issue by louissl** [moxiecode/plupload#1449]
in most of computers，it works ok in IE8;
but in same IE8 browers，property of opacity is alaways not work

IE8 version : 8.0.7601.17514;
![opacity_not_work](https://cloud.githubusercontent.com/assets/11297764/23351202/bec1e42e-fcfa-11e6-9ad1-d88a072d698d.png)

**Comment by louissl** [comment]
mybe，same css style not work；
but I don't know what I can do;

little pulpload code：
……
"IE" === a.browser && a.verComp(a.version, 10, "<") && n.extend(m.style, {filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=0)"})
……

**Comment by jayarjo** [comment]
Are you running it in standalone IE8 or it is it's virtual or simulated version? Also does it happen for you on the Plupload site as well?

`opacity` rule doesn't work in IE8, but in old IEs we use their proprietary filters to achieve the same effect. So it shouldn't be a problem in general.

**Comment by louissl** [comment]
I'm sure it is in standalone IE8 ,but it happens only two PC,most PC not happen.

thanks to explain opacity rule ,  can you show how to use -ms-filter rule?
I try like this:  -ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=0)"}
but It is a mistake


I will test on Plupload site later,thanks

**Comment by jayarjo** [comment]
Plupload applies opacity to it's own structures by itself, you do not need to do anything. But yes, that's the rule:
```
filter : "progid:DXImageTransform.Microsoft.Alpha(opacity=0)"
```

**Comment by jayarjo** [comment]
Feel free to reopen if you need a followup.
