### ISSUE TITLE
v1.5.8 Tag Deleted from Github

### ISSUE THREAD

**Issue by jeffgeorge** [moxiecode/plupload#1450]
Hi Moxiecode Devs,

I know the 1.x branch is deprecated and has been for quite awhile, but it looks like the tag for "v1.5.8" was removed from Github in the past day or so, possibly in the past few hours. Some externally-managed projects (like the [Drupal Integration for Plupload](https://www.drupal.org/project/plupload)) still depends on "v1.5.8".

If this tag being removed was accidental, can we please have the tag re-added? It looks like it was previously attached to this SHA:

https://github.com/moxiecode/plupload/commit/6b1df264486bf82551236683d2a64390728a1c07

**Comment by mikecrittenden** [comment]
This just bit me as well. We'll have to patch the Drupal module to reference that specific commit in the meantime I suppose.

**Comment by jayarjo** [comment]
Sorry, it was a mistake. I will re-add it of course.

**Comment by jayarjo** [comment]
[Done](https://github.com/moxiecode/plupload/releases/tag/v1.5.8).

**Comment by jeffgeorge** [comment]
Thanks @jayarjo! I can confirm that the [build zipball](https://github.com/moxiecode/plupload/archive/v1.5.8.zip) the Drupal module references is accessible again!
