### ISSUE TITLE
bug when using filters with mime_types

### ISSUE THREAD

**Issue by luoyeshu0507** [moxiecode/plupload#1451]
I tried hard for hours to find this bug!
It is in moxie.js line 589 
```
 "image/jpeg,jpg jpeg jpe," +
```
When i set filters like this:
```
filters: {
    max_file_size : "10mb",
    prevent_duplicates : true,
    mime_types : [
        {title : "Image files", extensions : "jpg,gif,png"},
        { title : "Zip files", extensions : "zip" }
    ]
 },
```
It will generate a input element with an attribute like:
```accept="image/jpeg,image/gif,image/png,application/zip"```

I can't choose images in some new Android phones just because they can't recognize 'jpeg'！

Maybe it shoud be like this:
```
"image/jpeg,jpeg jpe," +
"image/jpg,jpg," +
```

I tested and this works well~

**Comment by jayarjo** [comment]
Are you using the latest stable version of Plupload? We've addressed related problem in one of the bugfixes.

**Comment by jayarjo** [comment]
Try to add `jpeg` extension to your list of extensions as well.
