### ISSUE TITLE
.jpeg file extensions greyed out on FF on Mac

### ISSUE THREAD

**Issue by Stiofan** [moxiecode/plupload#1454]
If you limit the extensions to "jpg,jpeg" it seems to work everywhere except on FireFox on Mac where you can't select *.jpeg files as they are greyed out, you can however select *.jpg files.

Example: http://jsfiddle.net/fo6fvnyw/

**Comment by luoyeshu0507** [comment]
@Stiofan  
 I reported this bug in issue https://github.com/moxiecode/plupload/issues/1451 ,
but seems that nobody cares about it~

**Comment by jayarjo** [comment]
@Stiofan have you tried v2.3.x?

**Comment by Stiofan** [comment]
@jayarjo just tested and yes it seem to work from 2.2.1 onward, i was testing this with WordPress which uses 2.1.8 still.
