### ISSUE TITLE
Plupload is not working on IE11.

### ISSUE THREAD

**Issue by KalpanaPagariya** [moxiecode/plupload#1455]
While uplaoding on IE11, attached pop up comes on the IE11 borwser which asks to save <action>.json file

![image](https://cloud.githubusercontent.com/assets/18165261/23788415/56a69916-059c-11e7-9502-43fb075449c6.png)

**Comment by KalpanaPagariya** [comment]
Using pluppload 2.1.8 version

**Comment by KalpanaPagariya** [comment]
Is there any response? Can anyone update?

**Comment by KalpanaPagariya** [comment]
One more thing, on IE11, we are changing the doc mode to IE9 to support legacy code.

**Comment by jayarjo** [comment]
@KalpanaPagariya are you replying to upload request with `UploadActionxxxx.json`? If yes then I'd suggest to send it back with `text/json` header, rather than `application/json`, which is known to `cause the effect similar to yours.
