### ISSUE TITLE
Unclear how to apply an accessible label to the plupload element

### ISSUE THREAD

**Issue by mryand** [moxiecode/plupload#1458]
I am trying to make sure our forms are accessible to users of screen readers and other assistive devices. Our forms use plupload in place of traditional upload elements to provide asynchornous upload and progress bars.

I would like to have a label like `<label for="something">Upload an image</label>` but it's not clear what to put in the `for` attribute.

I am not seeing any documentation on how to do this -- is there guidance somewhere? If not, can someone answer this issue with a solution?

**Comment by jayarjo** [comment]
Are you using one of the bundled widgets, or do you have your own implementation on top of the Core API?

I'm not sure I understood what you are trying to do, but files are sent using the field having `file_data_name` value as a name, which by default is equal to `file`.

**Comment by mryand** [comment]
This is an implementation on top of the Core API. Highly simplified pseudo-js:

 ```javascript
var uploader = new plupload.Uploader({
	browse_button: 'upload_browse_foo',
	drop_element: 'upload_browse_foo',
	multi_selection: false,
	url: 'https://example.com',
	multipart_params : multipartParams,
	filters: uploadFilters
});
uploader.init();
```

This appears to create a bunch of elements, including a dive with the id `upload_browse_foo` and a hidden input element with an apparently randomly generated ID.

Typically in accessible form creation we want to have a label and element strunctured like:

```html
<label for="inputID">Here's the label</label>
<input id="inputID" />
```

In this case it's not clear to me how to accomplish something similar -- which ID should the label point to?

**Comment by jayarjo** [comment]
Hidden input element is not always present. For third party runtimes like Flash/Silverlight there's no form element at all. So it's just a way to get hold of the files. 

However if you are building your implementation on top of the Core API, you can easily integrate uploader in any HTML structure, with labels among other elements.
