### ISSUE TITLE
Features cancel upload and approx time and speed

### ISSUE THREAD

**Issue by pro811-com** [moxiecode/plupload#1466]
Hi Davit & friends,
first of all: good job!, I will buy it soon.

Features from my point of view:
a) cancel an upload => showing an icon a the position of the green tickmark and than call a method to jump to the next file to upload
b) a method to calculate the approx. total upload time. answer only after uploading i.e. 1-10% depending of the size of the first file/chunk, before "0"
c) with b the speed is also calculatable

Best regards
Robert

**Comment by jayarjo** [comment]
Are you using UI widget?

**Comment by jayarjo** [comment]
Speed is calculated in `uploader.total.bytesPerSec`.
