### ISSUE TITLE
runtime value is set later

### ISSUE THREAD

**Issue by pro811-com** [moxiecode/plupload#1468]
Hi davit & friends,
I would like to hide to start upload link/button because I call start() in the FilesAdded event.
In case I have html4 as a runtime I would like to make it visible.
I tried to get uploader.runtime after init() but it's null (screenshot).
When I close the DOM Explorer and reopen it runtime is set correctly.
Is it set later, by an event, how could "wait" for it?
Thanks and greetz
Robert

**Comment by jayarjo** [comment]
Runtime is set after Plupload is initialised. You should check for it not after `uploader.init()` but from the `PostInit` event handler.

Here is an example: http://play.plupload.com/m__J_/3
