### ISSUE TITLE
INIT_ERROR

### ISSUE THREAD

**Issue by mybydhn** [moxiecode/plupload#1471]
chrome version 56,

runtimes:"flash",
Error:init_error ,how to resolve.
在chrome浏览器中设置了runtimes:"flash" 安装了 chrome for flash,会初始化失败。怎么解决呢？

**Comment by jayarjo** [comment]
Flash is disabled in Chrome by default. That might the reason for that error. I wouldn't recommend flash runtime in Chrome anyway. Use html5 wherever possible.
