### ISSUE TITLE
Plupload html4 file size issue

### ISSUE THREAD

**Issue by Userplupload** [moxiecode/plupload#1480]
I am using plupload 1.5.6 . 
When the runtime is html4 , I get a security error in place of a file size error which I understand is caused since html4 is not able to determine the file size . 
For resolving this I tried handling this problem on the server side, but plupload ignores server side messages. Can anyone help me find a resolution that can work ?

**Comment by jayarjo** [comment]
Plupload can receive server response in `FileUploaded` or `Error` events. How do you communicate the message exactly?
