### ISSUE TITLE
Cannot use plupload in index.php

### ISSUE THREAD

**Issue by YukiDayDreamer** [moxiecode/plupload#1487]
I have tried the **custom.html** under example folder, and it works well.
But once I change it to **custom.php**, the uploading status in _Network_ keeps being _pending_
I am not sure why this problem happened because I have set up the PHP environment correctly.

**Comment by jayarjo** [comment]
Are you able to load any other php file?

**Comment by YukiDayDreamer** [comment]
Yes, I do.  The only change I did was to change **custom.html** to **custom.php**
