### ISSUE TITLE
Where does plupload saves the images for the upload, where to get base64 string of these?

### ISSUE THREAD

**Issue by SDCRoman** [moxiecode/plupload#1493]
I need to either to know where the resized files are stored which plupload prepares for the upload, so I can create a base64 string of these. 

Or is there a direct method, so I can get the base64 strings of all the images which should be uploaded.

Thanks

**Comment by jayarjo** [comment]
Currently there is no way to obtain these. But you can build your own implementation on top of Plupload core - mOxie.

**Comment by jayarjo** [comment]
Related: https://github.com/moxiecode/plupload/issues/1304

**Comment by jayarjo** [comment]
Related: https://github.com/moxiecode/plupload/issues/1064
