### ISSUE TITLE
When uploading files using IE8 IE9 IE10 on Windows7 there is no status displayed of the ongoing progress until the file is completed.

### ISSUE THREAD

**Issue by ymecho** [moxiecode/plupload#1495]
When uploading files using IE8 IE9 IE10 on Windows7 there is no status displayed of the ongoing progress until the file is completed.
 
The UploadProgress event doesn't seem to be fired at all.
 
Have tested with the same backend and client code on Chrome, Firefox and Safari and it works perfectly.

**Comment by jayarjo** [comment]
Can you post your config or better provide your case here: http://play.plupload.com?

**Comment by ymecho** [comment]
my code:

    function initUploadBpl()
	{
	    uploader = new plupload.Uploader({
		runtimes : 'html5,html4,flash,silverlight',
		multipart:true,
		multipart_params: { "<%getTokenFormName();%>": "<%getTokenValue();%>"},
		browse_button : 'browse',
		multi_selection:false, 
		url : '/action/uploadFile?referrer=maintenance_update.asp&extendupload=1',
		filters : {
			max_file_size : maxUploadFileSize,
			mime_types: [{title : "uploadFile", extensions : "tar.gz,zip"},]
		},
		init: {
			PostInit: function() {
				document.getElementById('upload_file').onclick = function() {
                    clearSameNameColor();
                    
					var fileNum = uploader.files.length;
					if(0  == fileNum)
					{alert(pleaseSelectFile);return false;}
					//上传前，先校验是否有人在上传
					checkFileUploadProgress();
					return false;};	
			},
			FilesAdded: function(up, files) {
				plupload.each(files, function(file) {$('#fileName').val(file.name);});
			},
			QueueChanged: function(uploader) {
				var fileLen = uploader.files.length;
				for(var i = 0; i < fileLen-1; i++)
				{uploader.removeFile(uploader.files[i]);}
			},
			UploadProgress: function(up, file) {
				if(file.percent.toString() == "100"){$('#loadingLan').html(decompressingLang);}
				else{$('#loadingLan').html(loadingLang + "  " + file.percent.toString() + "%");}},
            FileUploaded: function(uploader,file,responseObject) {
                var context = responseObject.response;
                FindAlertMsg(context);
            },
			Error: function(up, err) {
				switch (err.code) {  
					case plupload.FILE_EXTENSION_ERROR:  
						alert(uploadText + ".tar.gz " + fileTypeLang + " .zip!");  
						break;  
					case plupload.FILE_SIZE_ERROR: 
						alert(FileTooBigLang);
						top.location.href = '/home.asp';
						break; 	
					case plupload.HTTP_ERROR:
						alert(netWorkErrLang);
						top.location.href = '/home.asp';							
						break;  
					case plupload.GENERIC_ERROR:  
						alert(uploadFileFailLang);
						top.location.href = '/home.asp';
						break;   
					default:  
						alert(uploadFileFailLang);
						top.location.href = '/home.asp';
						break;  
				} 
			}
		}});
		uploader.init();		
	}

**Comment by ymecho** [comment]
I am single-step debugging and found that UploadProgress does not trigger

**Comment by jayarjo** [comment]
@ymecho from what I see progress is not reported for you, because your config makes Plupload to fallback to `html4` runtime, which cannot provide progress. I'd suggest to move `html4` to the end of the runtime list, like this: 

`runtimes : 'html5,flash,silverlight,html4'`

This way Plupload will first try `flash`, then `silverlight` and if they both fail, will fallback to `html4`.

You will also need to define `flash_swf_url` and `silverlight_xap_url` [in your config](https://github.com/moxiecode/plupload/wiki/Options#flash_swf_url).

**Comment by jayarjo** [comment]
Here's simplified fiddle for your code: http://play.plupload.com/p__J_/8 (I had to remove undefined blocks, progress is reported to the console - old IEs do not have console, so be sure to alter it accordingly).
