### ISSUE TITLE
Login on plupload.com broken, eats accounts!

### ISSUE THREAD

**Issue by MatsSvensson** [moxiecode/plupload#1500]
There is something seriously broken with your code that handles logins on plupload.com

I tried to login, but my password was rejected.

I used the function for forgotten password, and got an email to a PW-reset page.
I **pasted** my new password, and got an ok.

Then tried to login withe the new password (pasted the same)
"Wrong login" WTF?!

Tried the function for forgotten password again,
 now it says the email could not be found.

Tried the same with another old account, connected to another email.
Same thing.

All info password, email, etc 100% correct.

So the function for resetting the password instead deletes the account/email from your database?

It also says no new registrations can be made, so there is no way back in.

Have you been hacked?

**Comment by jayarjo** [comment]
We are considering to close the forum on plupload.com, since it is mostly used by spammer human-bots with an alarming intensity. 

I'd suggest to post your questions on StackOverflow and tag them with `plupload` tag instead. For issues we have this bugtracker on github.

**Comment by MatsSvensson** [comment]
Is it hacked then?
Or Why doesn't the login  works?
I see others post there.

Whatever you do, don't delete the forum.
Its full of useful info.
I use it all the time to find solutions.

StackOverflow can be a tad soupnazi-ish, especially towards noobs.
Maybe not the best replacement for a  dedicated support forum.

**Comment by jayarjo** [comment]
It is not hacked. We've simply closed new registrations. I'm not sure why you weren't able to login, maybe you've used the wrong password. I'm looking into the password reset problem.

**Comment by jayarjo** [comment]
@MatsSvensson maybe try now? I was able to successfully reset my passowrd and log in.

**Comment by jayarjo** [comment]
Forum will stay where it is, since as @MatsSvensson has mentioned - lots of info there. But I guess we will close it for new registrations for now. Everybody, use StackOverflow with #plupload tag.
