### ISSUE TITLE
html 5 cross-domain upload is not working

### ISSUE THREAD

**Issue by leoloso** [moxiecode/plupload#1503]
Hi, I'm using the Plupload that is shipped with WordPress 4.6.1, that is Plupload v2.1.8 with mOxie v1.3.4. I also tried with Plupload v2.3.1, but it also failed. I'm using with Chrome Version 59.0.3071.115 (Official Build) (64-bit)

I want to upload a file from one domain to another, using the html 5 runtime. I've done all that was supposed to be done: set option `"send_browser_cookies"` under `required_features`, and added in my .htaccess:

```
<IfModule mod_headers.c>
<FilesMatch "(async-upload)\.php$">
    Header set Access-Control-Allow-Origin "*"
    Header add Access-Control-Allow-Headers Content-Type
    Header add Access-Control-Expose-Headers Content-Type
</FilesMatch>
</IfModule>
```

(async-upload.php is WordPress server file doing the upload).

However it doesn't work. Basically, it never sends the cookies along, so the other domain keeps saying I'm not logged in there, while in fact I was. So it's evidently a CORS problem. I tried also hacking file plupload.full.min.js, adding `.withCredentials=true` just before opening the xhr connection everywhere, and it didn't work either.

I noticed that, when normally uploading to the same domain, it sends a POST, however when changing the domain, it sends OPTIONS. Is that alright?

I hope this can be set to work, even if with a hack? Anyone would know how? I need to do cross-domain uploading for my [open source project](https://github.com/leoloso/PoP). Thanks!

**Comment by jayarjo** [comment]
I would suggest that you try our sample `upload.php` first (to exclude other factors). It has CORS related code [commented out by default](https://github.com/moxiecode/plupload/blob/2.2.x/examples/upload.php#L26), so be sure to uncomment it.

OPTIONS header is sent by browser, not by Plupload, so your server-side handlers should be ready for it and respond according to specs.

**Comment by leoloso** [comment]
Dear David, thanks so much, you got it right! Adding this code to async-upload.php solved the problem:

```
if ($_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
	exit; // finish preflight CORS requests here
```

I'm extremely grateful 😄 
Cheers
