### ISSUE TITLE
Client resizing crashes IE on few pictures

### ISSUE THREAD

**Issue by lion1906** [moxiecode/plupload#1512]
Hi. 
I can use plupload with success, but sometimes the browser crashes with a few pictures
As i can see, no error in the console, and it happens not randomly, but always with the same pictures.

I've tested a lot of pictures, bigger in size and bigger in Mb. 
It seems to crash with the pictures by the same model of camera...

No problem with firefox.
No problem with IE when the client resizing is off.

Here is a zip wich contains an example of one picture that crashes.
[2202659_original_batwf_18.zip](https://github.com/moxiecode/plupload/files/1300180/2202659_original_batwf_18.zip)

Hope this helps

Sorry for my english, it's not my natural language.

**Comment by jayarjo** [comment]
Could you also provide a setup here: http://play.plupload.com?

**Comment by lion1906** [comment]
Hi jayarjo.

Here is my code : 
http://play.plupload.com/6__J_/1

Note that Firefox runs perfectly, The Crash comes with IE11 with the picture zip link in this thread. Other pictures can be ok with IE11.
What IE11 says is just 'IE doesn't answer'
IF you want i can put here another zip file with the same problem pictures.

Thanks

**Comment by lion1906** [comment]
For information, i've tried to setup preserve_headers to false, but not change.

**Comment by jayarjo** [comment]
Not able to make it crash in IE11 on Windows 10. What is your OS? Are you testing it through VM maybe?

**Comment by jayarjo** [comment]
I've reordered your fiddle a bit: http://play.plupload.com/6__J_/2.

**Comment by lion1906** [comment]
Hi Jayarjo.
Thanks for your answer.
My OS is Windows 7 Enterprise (64). No VM
I tried with IE 64 and IE 32. The result is the same.
![ie crash](https://user-images.githubusercontent.com/31932609/30695236-bd3d1d42-9ed7-11e7-93b1-063c35ba8ddf.png)

As you can see with my screenshot, IE just informs 'plupload.com doesn't answer'.
I just repeat that the problem comes with this picture (and a few others examples i can put here if you want), It seems there's something in the picture than can not be understood by IE...

I will try to test with another pc with the same config as mine.
Thanks again for your help.

**Comment by jayarjo** [comment]
Hm... seems that IE10 and early versions of IE11 do not support `blob:` uris as a source for the image. Interesting how Microsoft managed to land two incompatible versions of IE11.

**Comment by lion1906** [comment]
Hi jayarjo.
Thanks again for looking what is wrong with this test.
Additionnal : I've tried with IE 11 on Windows 7 32b starter Edition. Result is the same: IE doesn't answer.
I think the problem comes with all Win 7
Do you have an idea why it appears with a few pictures, and runs well with others ?

**Comment by jayarjo** [comment]
It seems that blob uris are unreliable in older IE11 and IE10 and since there's basically no way to intercept the failure, I think I will simply mark the feature as not available in those browsers.
