### ISSUE TITLE
IE 11, Edge doesn't support Drag and Drop

### ISSUE THREAD

**Issue by binal24** [moxiecode/plupload#1514]
Window 8.1 IE 11, Edge doesn't support drag and drop.
Even your example link is not working in IE 11. http://play.plupload.com/y/4
Please let me know if you have any solution for this issue.

**Comment by jayarjo** [comment]
Tried it in both - IE11 and Edge, seems to work. Do you drag the file from the desktop and it fails to drop into the UI, or what exactly doesn't work?

**Comment by binal24** [comment]
No, I have not drag file from desktop.
I am dragging video file(.mp4) from browse file.
Even I have tested with this sample link. But Its not working in my browser.
Is there any specific requirement for IE 11?

**Comment by jayarjo** [comment]
Sorry, not sure what you mean by dragging from browse file. Do you mean from file explorer?

Example that you reference is configured to filter all files except images and zip archives (check the config). I've modified an example to accept `.mp4`, try it out: http://play.plupload.com/y/5.

**Comment by binal24** [comment]
![image](https://user-images.githubusercontent.com/22168572/30732638-1e00a5e0-9f91-11e7-9a16-a46a16155aa6.png)
Please check this attached screenshot.

**Comment by jayarjo** [comment]
Browser dialogs are for picking files not dragging them over. If you are looking to drag the file open File Explorer.

**Comment by jayarjo** [comment]
Seems to work here.
