### ISSUE TITLE
Drag to upload folder make the browser(chrome, fiefox...) unresponsive for a period of time 

### ISSUE THREAD

**Issue by shawpo** [moxiecode/plupload#1515]
I want to support folder upload, but when I drag a big folder to the upload area, the browser will unresponsive for a period of time ,and events is not activated(like QueueChanged, FilesAdded). How  can I solve it?

**Comment by jayarjo** [comment]
How big is the folder? Bear in mind that Plupload has to cycle through each and every file in the folder in its subfolders.

**Comment by wuxiaobo2014** [comment]
1.87 GB

**Comment by wuxiaobo2014** [comment]
Perhaps have an event that can be activated when cycle through each and every file in the folder? So I can inform the user program is  in operation.
I am sorry to my poor English.

**Comment by jayarjo** [comment]
For every processed file we fire `FileFiltered` even, perhaps you could use it show some feedback.
