### ISSUE TITLE
Pupload 2.3.4 version can not work well in IE8 browser

### ISSUE THREAD

**Issue by wang-joy** [moxiecode/plupload#1526]
Pupload 2.3.4 version can not work well in IE8 browser, there is an error: **"plupload" is undefined**, in the file "plupload.full.min.js, row: 13, column: 1972", missing identifier. The 2.1.9 version works well in IE8 browsers

**Comment by jayarjo** [comment]
It works fine in our tests. Could you provide a case in our playground, here: http://play.plupload.com?

**Comment by wang-joy** [comment]
![image](https://user-images.githubusercontent.com/20333189/32357365-082af0b6-c077-11e7-8f4a-5971ae4223ab.png)
![image](https://user-images.githubusercontent.com/20333189/32357379-1960153c-c077-11e7-9a5f-ea0522e65fe6.png)
`var uploader = new plupload.Uploader({
	runtimes : 'html5,flash,silverlight,html4',
	browse_button : 'pickfiles', // you can pass an id...
	container: document.getElementById('container'), // ... or DOM Element itself
	url : 'upload.php',
	flash_swf_url : '../js/Moxie.swf',
	silverlight_xap_url : '../js/Moxie.xap',
	
	filters : {
		max_file_size : '10mb',
		mime_types: [
			{title : "Image files", extensions : "jpg,gif,png"},
			{title : "Zip files", extensions : "zip"}
		]
	},

	init: {
		PostInit: function() {
			document.getElementById('filelist').innerHTML = '';

			document.getElementById('uploadfiles').onclick = function() {
				uploader.start();
				return false;
			};
		},

		FilesAdded: function(up, files) {
			plupload.each(files, function(file) {
				document.getElementById('filelist').innerHTML += '<div id="' + file.id + '">' + file.name + ' (' + plupload.formatSize(file.size) + ') <b></b></div>';
			});
		},

		UploadProgress: function(up, file) {
			document.getElementById(file.id).getElementsByTagName('b')[0].innerHTML = '<span>' + file.percent + "%</span>";
		},

		Error: function(up, err) {
			document.getElementById('console').appendChild(document.createTextNode("\nError #" + err.code + ": " + err.message));
		}
	}
});

uploader.init();`
Custom.html in Pupload 2.3.4version  can not work well in IE8 browser

**Comment by jayarjo** [comment]
You could have saved that case on the playground site and post a link to it here instead of screenshot and code.
