### ISSUE TITLE
ie8, ie9 Error #-600 help!

### ISSUE THREAD

**Issue by olyy111** [moxiecode/plupload#1532]
some wired thing happened when I open upload image use plupload in my project, my project is useing PHP server, and it send the template to client, I almost copy the plupload start example, ,  the initial options:
```javascript
var uploader = new plupload.Uploader({
	browse_button: 'browse', // this can be an id of a DOM element or the DOM element itself
	url: 'uploadImage.php',
});
```
case 1:
In chrome ie10 it's ok. but in ie8 and ie9,  when i upload the image locally,  error: "Error #-600: File size error",  this error happened when I added the file into the queqe,  havn't upload image yet.
case 2:
this error also happend when I locally open the html file（plupload start example）

Plupload upload files with flash in ie8 ie9 , may be this is a Cross-domain problem ?  but  It didn't interact with backend really, I am poor in flash, and so sad, help me, please!

**Comment by olyy111** [comment]
yet resolve it

**Comment by Mohaiyo** [comment]
Did you resolve this issue?
