### ISSUE TITLE
How to unset default headers in the upload request?

### ISSUE THREAD

**Issue by HFO4** [moxiecode/plupload#1545]
Some upload API (such as [b2_upload_file](https://www.backblaze.com/b2/docs/b2_upload_file.html)) have some special requirements to the headers sent with the file data. I noticed that a `Cache-Control` header is sent by default. How should I remove this header?

**Comment by jayarjo** [comment]
We do not impose any headers on the uploads ourselves. There might be some added by the runtimes (Flash does that definitely). Other than that headers on the customer side can be added through the [headers](https://www.plupload.com/docs/v2/Options#headers) option.
