### ISSUE TITLE
Resize to smaller side possible?

### ISSUE THREAD

**Issue by pjforde1978** [moxiecode/plupload#1573]
resize is (predictably/understandably/logically) implemented to use the larger side as maximum.

Since I can't have nice things, my application requires me to use the smaller side as maximum. On the server, I specify 300x300^ in ImageMagick and if I send it a 400x600 image, it will come back as 300x450.

Is it possible to do this on the client in plupload without a lot of pain?

**Comment by warrenkc** [comment]
Your question is: Can PLUpload do client side image resizing? The answer is yes.

**Comment by pjforde1978** [comment]
Thanks, Warren.

In the end, I just did it on the server because it was not self-evident how to get PLUpload to resize using the smaller size as the constraint in an aspect ratio. It is admittedly a strange requirement.
