### ISSUE TITLE
图片限制问题，在小米自带浏览器上出现无法选择图片问题

### ISSUE THREAD

**Issue by yangweiwei12345** [moxiecode/plupload#1582]
![image](https://user-images.githubusercontent.com/8935926/45527273-55e5a880-b80d-11e8-83c5-4097cc16368f.png)

**Comment by 712059392** [comment]
你处理好了这个问题了吗？我也遇到了这个问题，而且不知道该如何处理！

**Comment by yangweiwei12345** [comment]
生成的<input accept="jpg,jpeg,png" />小米手机不识别，改成<input accept="image/jpg,image/jpeg,image/png" />

**Comment by yangweiwei12345** [comment]
> 你处理好了这个问题了吗？我也遇到了这个问题，而且不知道该如何处理！

生成的《input accept="jpeg,jpg,png" /》小米手机不识别，改成《input accept="image/jpeg,image/jpg,image/png" /》

**Comment by yangweiwei12345** [comment]
> 你处理好了这个问题了吗？我也遇到了这个问题，而且不知道该如何处理！

![image](https://user-images.githubusercontent.com/8935926/49566168-b136bb00-f964-11e8-9bfa-a843426ac7ef.png)

**Comment by 712059392** [comment]
这样子修改会出现部分手机无法在相册中选择图片的问题，为了完美兼容各种终端，我已经取消这个格式限制，并在后端程序中进行文件验证和返回错误信息！
