### ISSUE TITLE
How to Get File MD5 in Browser

### ISSUE THREAD

**Issue by lingliMr** [moxiecode/plupload#1592]
How to Get File MD5 in Browser

**Comment by lingliMr** [comment]
` BeforeChunkUpload:function(up,file,args,chunkBlob,Offset){
                get_filemd5sum(file)
            },`
use spark-md5.js
`function get_filemd5sum(files) {
        var blobSlice = File.prototype.slice || File.prototype.mozSlice || File.prototype.webkitSlice,
        file = files[0],
        chunkSize = 1048560,                             // Read in chunks of 2MB
        chunks = Math.ceil(file.size / chunkSize),
        currentChunk = 0,
        spark = new SparkMD5.ArrayBuffer(),
        fileReader = new FileReader();
        fileReader.onload = function (e) {
            console.log('read chunk nr', currentChunk + 1, 'of', chunks);
            console.log(e.target.result)
            spark.append(e.target.result);                   // Append array buffer
            currentChunk++;

            if (currentChunk < chunks) {
                loadNext();
            } else {
                console.log('finished loading');
                console.info('computed hash', spark.end());  // Compute hash
            }
        };

        fileReader.onerror = function () {
            console.warn('oops, something went wrong.');
        };

        function loadNext() {
            var start = currentChunk * chunkSize,
                end = ((start + chunkSize) >= file.size) ? file.size : start + chunkSize;
                // blobSlice(file, start, end)
            fileReader.readAsArrayBuffer(blobSlice.call(file, start, end));
        }

        loadNext();
    }`

but 
![image](https://user-images.githubusercontent.com/25763495/50443285-8b864b80-093d-11e9-855e-7a4cfd04de15.png)
![image](https://user-images.githubusercontent.com/25763495/50443308-a8228380-093d-11e9-95e4-ba76420f2ea2.png)

**Comment by lingliMr** [comment]
I solved it.
use **getNative()**
Returns native window.File object, when it's available.

**Comment by kartiknaithani** [comment]
use getNative() how and where?
