### ISSUE TITLE
plupload insecure

### ISSUE THREAD

**Issue by esraanaem** [moxiecode/plupload#1599]
I used wordpress to create a website but when i scanned using acuneitx tools it is gave me an error a vulnerable java script library and asked me to upgrade the library and it was plupload.js file. I don't know how to upgrade it? helllllllllllllllllllllllllllp

**Comment by Afraithe** [comment]
Not sure how old your setup is, but there are no active security issues around Plupload right now, it might be one in Wordpress implementation though, you need to talk to them.
