### ISSUE TITLE
pasos manejador de  imagenes 

### ISSUE THREAD

**Issue by olodrim** [moxiecode/plupload#1600]
1 un uploader , multiple y remoto
2 subo imagenes
remotamente se evaluan y buscan los productos con el SKU
se guardan las imagenes en orden ascendente, las imagenes que no tuvieron coincidencia se guardan en un modelo alternativo para su posterior utilizacion
3 se renderea asincronamente la seccion de productos con sus imagenes y se permite drag and drop por cada fila .
4 se permite guardado por unidad (producto)
5 se quiere hacer guardado general de productos
6 el cover será siempre la primera imagen

**Comment by Afraithe** [comment]
Sorry, can't respond to non-english issues.
