### ISSUE TITLE
关于在vue中使用setOption()报错的问题

### ISSUE THREAD

**Issue by Agony95z** [moxiecode/plupload#1604]
up.setOption({
        // url: this.host,
        url: 'http://null.oss-cn-zhangjiakou.aliyuncs.com',
        multipart_params: newMultipartParams
 })
总是报错：vue.esm.js?efeb:628 [Vue warn]: Error in v-on handler: "TypeError: Cannot read property 'url' of null"
请问如何解决

**Comment by Afraithe** [comment]
Sorry, we can't really respond to non-english posts.
