### ISSUE TITLE
Upload File's Content-Type not submitted in POST payload by Chrome 8.0.552

### ISSUE THREAD

**Issue by edave** [moxiecode/plupload#204]
Using Plupload 1.4.1 HTML5, when a file is uploaded, the file's content-type is not submitted in the POST payload by Chrome 8.0.552, but is submitted when using other browsers. Here are some example header/relevant post payloads when trying to upload the same png file across different browsers.

Plupload Code:
    $("#uploader").pluploadQueue({  
       // General settings
       runtimes : 'html5,flash,silverlight,html4',
       url : '/uploads.js',
       max_file_size : '10mb',
       chunk_size : '1mb',
       container: 'uploader',
       autostart: true,
       // Flash settings
       flash_swf_url : '/plupload/js/plupload.flash.swf',

```
   // Silverlight settings
   silverlight_xap_url : '/plupload/js/plupload.silverlight.xap'
 });
```

_Chrome Request Headers/Payload:_
    Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryl8UosmAtkBQFvoYm
    User-Agent:Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_6; en-US) AppleWebKit/534.10 (KHTML, like Gecko) Chrome/8.0.552.231 Safari/534.10
    ------WebKitFormBoundaryl8UosmAtkBQFvoYm
    Content-Disposition: form-data; name="file"; filename="Blob5f8af60a0bdc4aa3adb9410c0fb35271"

```
------WebKitFormBoundaryl8UosmAtkBQFvoYm--
```

_Safari 5.1 Headers/Payload:_
    Content-Type:multipart/form-data; boundary=----WebKitFormBoundarycb2tIyZv9By757NQ
    User-Agent:Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_6_6; en-us) AppleWebKit/533.19.4 (KHTML, like Gecko) Version/5.0.3 Safari/533.19.4
    ------WebKitFormBoundarycb2tIyZv9By757NQ
    Content-Disposition: form-data; name="file"; filename="moleskine_helvetica_red_512.png"
    Content-Type: image/png

```
------WebKitFormBoundarycb2tIyZv9By757NQ--
```

_FireFox 3.6 Headers/Payload:_
    Content-Type    multipart/form-data; boundary=----pluploadboundaryp15nnd7e5s9q81qu6pmq14sgp1r4
    User-Agent  Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.6; en-US; rv:1.9.2.13) Gecko/20101203 Firefox/3.6.13
    ------pluploadboundaryp15nnd7e5s9q81qu6pmq14sgp1r4
    Content-Disposition: form-data; name="file"; filename="moleskine_helvetica_red_512.png"
    Content-Type: image/png

**Comment by jayarjo** [comment]
Shouldn't be a problem in Plupload 2.x.
