### ISSUE TITLE
[Feature Request] Allow to cancel the ramaining chunk loading and move to the next file in the queue

### ISSUE THREAD

**Issue by MikePeterson** [moxiecode/plupload#220]
Should have a method that would stop the loading of the remaining chunks for the current file and move to the next file in the upload queue.

This could very useful if the server makes file name or format validation when it receives the first chunk. If the validation fails, no need to load the rest of the files chunks.

**Comment by jayarjo** [comment]
This is possible in Plupload 2.x.
