### ISSUE TITLE
S3 upload: 'unique_names: true' doesn't work

### ISSUE THREAD

**Issue by ramonv** [moxiecode/plupload#254]
If you add 'unique_names: true' to the S3 example, files are uploaded to Amazon S3 with the original filename instead of the unique filename.

**Comment by jayarjo** [comment]
This is related: https://github.com/moxiecode/plupload/issues/785

**Comment by jayarjo** [comment]
As in the case with `rename` option new file name is sent as separate param and handled by our `upload.php`. Obviously in the case of S3 there is nothing on Amazon Side to handle custom params, so one basically has to set it manually in the config.
