### ISSUE TITLE
Docs lack a list of string representations of features for required features option

### ISSUE THREAD

**Issue by tommedema** [moxiecode/plupload#259]
In order to set the required features option, one has to know the string representations that plupload looks for.

These should be added to the API/docs:

```
            html5
            dragdrop
            jpgresize
            pngresize
            multipart
            progress
            chunks
```

Note: this may not be a complete list!

**Comment by jayarjo** [comment]
Required features are documented [here](http://www.plupload.com/docs/v2/Required-Features).
