### ISSUE TITLE
Add files button isn't triggered in the HTML5 and HTML4 runtimes (Firefox 4)

### ISSUE THREAD

**Issue by kristinn** [moxiecode/plupload#278]
There is an issue with the "Add files" button when you are creating a custom file uploading form using the HTML4 runtime. I've debugged the problem and have found out what's wrong.

When using the HTML4 runtime the hidden element that is placed above the "Add files" button doesn't seem to have enough z-index value. Firefox 4 (at least) think it's placed below the "Add files" button and thus doesn't trigger an event when it gets clicked. I have changed the z-index value to a high number in Firebug and after that the button works perfectly.

The button works perfectly when I use the HTML5 runtime using exactly the same form (only the runtime gets changed).

Notice: This isn't a problem in Chrome. I haven't tried Internet Explorer but at least this is a problem in Firefox 4.

**Comment by jayarjo** [comment]
@downquark yes. After the panel is displayed, call `uploader.refresh()` and the shim will get repositioned properly.
