### ISSUE TITLE
HTTP_USER_AGENT for silverlight

### ISSUE THREAD

**Issue by IngusSkaistkalns** [moxiecode/plupload#340]
Hi, 

for me is seems that HTTP_USER_AGENT is empty for silverlight requests.

Maybe it could be useful to add some meaningful value, like "Microsoft Silverlight" or something like that.

**Comment by jayarjo** [comment]
We cannot control that, because `User-Agent` is listed under [restricted headers](https://msdn.microsoft.com/en-us/library/system.net.webheadercollection(v=vs.95).aspx#remarksToggle), which means that they cannot be changed from within Silverlight.
