### ISSUE TITLE
HTML5 Upload fails for multiple files on latest Safari for Windows

### ISSUE THREAD

**Issue by MCF** [moxiecode/plupload#363]
The current stable Safari for Windows has a bug that causes the upload of multiple files through the HTML5 runtime to fail.  Curiously upload through HTML5 still works if only a single file is selected.

The problem seems to be related to the FileList object available through the input element.  When more than one file is selected the file sizes are set to 0, the modification time is also set to 0.  The resulting upload through the FormData object will upload a zero length (i.e. empty) file.

This bug does not seem to be a web-kit bug as the latest Chrome does not have the same problem.

I've logged an issue with Apple against Safari.

I've also created a basic test case that uses the same technique to upload files that plupload does using HTML5 on Safari.  The test case is available here:

https://gist.github.com/1169709

(By the way I have not coded the test case to work around [this webkit form bug](https://bugs.webkit.org/show_bug.cgi?id=66907) which you may run into the second time you select files using the test)

**Comment by maridansoft** [comment]
Hi All, I have the same issue with multiple files in Chrome which I have reported at #1222  . Does anybody of you have similiar experience?????  When you try to select multiple items it is always posting first one.

**Comment by meilixie** [comment]
can plupload upload multiple files at once?

**Comment by kaige11** [comment]
I met the problem too and i fixed it just by download the latest version of plupload , good luck!

**Comment by jayarjo** [comment]
I guess now that Apple has dropped Safari for Windows (quite a while ago already), we gotta close this one.
