### ISSUE TITLE
Double clicking results in 2 file open dialogs (Chrome/Flash)

### ISSUE THREAD

**Issue by Kajakske** [moxiecode/plupload#373]
If I quickly double click a plupload instance that is running the flash runtime in chrome 13 I manage to open 2 file open dialogs.
1 appears immediatly, the second appears after the first closes (by selecting a file to upload).

The same behaviour has been simulated in IE/Html4 runtime.

**Comment by jayarjo** [comment]
When browse_button is clicked Plupload generates Browse event, that can be used to disable browse_button (among other things) via `uploader.disableBrowse()`.
