### ISSUE TITLE
html5 firefox 7.01 and chromium 12

### ISSUE THREAD

**Issue by Visualq** [moxiecode/plupload#398]
When I upload a file in multipart mode using the HTML 5 runtime, the filename is lost and the browsers just sends:

-----------------------------1117779921282589049853871300 Content-Disposition: form-data; name="file"; filename="blob"

This problem occurs when using FireFox 7.01 as well as Chromium 12.0 although I get hash appended to the filename e.g.: "blob891902399ef9a9b1123de9a". I tried it on a windows VM image and it also gave me 'blob' as filename. I also uploaded a file on: http://www.plupload.com/example_all_runtimes.php and noticed filename="blob" in the headers aswell. 

I'm running ubuntu 11.04 64bit

**Comment by khanzadimahdi** [comment]
i have done it by adding filename into each chunk using "BeforeChunkUpload" method , here is my code
``` js
init:{
       BeforeChunkUpload: function(uploader, file, post, currentBlob, currentOffset) {
              currentBlob.name=file.name;
       },
},
```
then you have the filename in each chunk instead of that shit "blob" name.
