### ISSUE TITLE
Accept header not honored in Safari

### ISSUE THREAD

**Issue by doxavore** [moxiecode/plupload#402]
Safari 5 on Mac ignores setting the Accept header, and uses `text/html,application/xhtml+xml,application/xml`.

When a JSON response then comes back instead of HTML or XML, Safari wraps it in a `<pre>` tag. For real. I don't yet know if this is only the HTML5 uploader or others, but will continue testing and update.

**Comment by jayarjo** [comment]
If it's about sending JSON for server, send it with `text/json` header instead of `application/json`, which is not supported on older browsers and consequently by our `html4` runtime.
