### ISSUE TITLE
Extensions filter is case-sensitive

### ISSUE THREAD

**Issue by daflip** [moxiecode/plupload#404]
At least on Linux anyway, the extensions filter is case sensitive. Using the following filter:

```
filters: [ {title : "Image files", extensions : "jpg,png"} ],                                    
```

Results in filters which have extensions like JPG or JpG to be filtered out - I've confirmed this with the html5 and flash runtimes. The only solution right now is to specify all possible cases which gets real messy real quick.

Is there any solution?

**Comment by wickstargazer** [comment]
Is this fixed already?
