### ISSUE TITLE
FileUploaded and UploadComplete events not firing with Flash

### ISSUE THREAD

**Issue by stephenlam** [moxiecode/plupload#455]
Files are uploaded successfully, but somehow these two events are not being triggered when using Flash. UploadProgress IS being triggered, however. I'm testing on Mac Snow Leopard with Firefox 6 and plupload 1.5.2.

I think this may be related to this issue on the forum:

http://www.plupload.com/punbb/viewtopic.php?id=1405

Is there a valid reason for the Flash runtime to require a response body? SWFUpload, a popular Flash uploader solution, still functions when a response header is returned without a body.

**Comment by ally0708** [comment]
Reinstall Iolo system mechanic download [url=https://iolo-system mechanic.com/]system mechanic download[/url]  in your device to protect your computer from unwanted problems. It protects security and privacy. Improves the speed of your pc. System Mechanic secure your PC free from un-required spyware and viruses. Chat with customer care team for reinstall system mechanic.

**Comment by ally0708** [comment]
Iolo activate system mechanic(https://iolo-install.com/url) is the best tuneup utilities for windows operating system. It optimizes PC, protects privacy, manages passwords, deletes malware, recovers data, boosts your pc speed. It protects privacy and security and secures your pc from unwanted problems. It improves the speed of your pc. For quick assistance talk with an expert!

**Comment by ally0708** [comment]
Iolo(https://activate-iolo.online/)  is a set of PC system utilities, also known as PC optimization software, that helps manage and maintain useful shape devices. System Mechanic Ultimate Defense reinstall speeds up your computer, and if the computer has a virus, it also removes. Talk with customer care team for any queries.

**Comment by ally0708** [comment]
Iolo System Mechanic ultimate defense (https://systemmechanic-iolo.com/url)  one of the best security software for your pc, you can protect your computer against internet worms, viruses, and hacker threats. It will also increase the speed of your computer. It improves the speed of your pc and Protects Privacy and Security. For quick assistance talk with an expert!

**Comment by ally0708** [comment]
system mechanic iolo one of the best security software https://systemmechanic-iolo.com/url) for your device, you can protect your computer against hacker threats, viruses and internet worms. It improves the speed of your pc and Protects Privacy and Security. It will also increase the speed of your computer. For quick assistance talk with an expert!
