### ISSUE TITLE
Continuing upload of multiple files after Error #2038

### ISSUE THREAD

**Issue by maettyhawk** [moxiecode/plupload#457]
Hi there,

I'm trying to use Plupload for uploading to YouTube. Right now I'm trying to upload diffent files to different urls. The problem is that the flash runtime I wanted to use (only way to get information about the upload progress) triggers an error after the upload is done, because the YouTube server returns a 302 redirect, which Flash isn't able to handle.

My question is if there's a way to easily continue the upload of the other files in the queue even if an error occurs (which is no error!)? I thought that manually triggering the FileUploaded event would help, but obviously I was wrong!

Thanks in advance.

Regards

maetty

**Comment by jayarjo** [comment]
Flash understands only 200 and 404 - that's technology limitation.
