### ISSUE TITLE
z-index problems in webkit browsers html5 runtime

### ISSUE THREAD

**Issue by duwaned** [moxiecode/plupload#468]
Hi There.

This problem has been around for a while but figured I would create an issue so it can be tracked and hopefully fixed in the core code in the next update.

In plupload.html5.js (version 1.5.2) the code (starting at line 468) that changes the "Add Files" button and shims z-index is problematic in certain circumstances.

Consider the situation where the element or window that plupload is running in is already at a z-index higher than 0. What happens is that the add files button doesnt work after this code runs as the shim gets a z-index of -1 which effectivly hides it and breaks uploads for all webkit browsers.

Surely theres a better way to do this? Maybe get the z-index of the parent container and set the buttons z-index dynamically based on the parents z-index? Its just that a static value means it gets hidden and breaks uploads using the html5 runtime which makes me a sad panda :).

**Comment by jayarjo** [comment]
Shouldn't be relevant for Plupload 2.x I guess?
