### ISSUE TITLE
Flash upload on a cookie protected URL

### ISSUE THREAD

**Issue by sgnix** [moxiecode/plupload#469]
If the upload url is cookie protected, the flash upload fails the authentication. A workaround is to specify a resize parameter. Oddly enough in this case the flash upload authenticates well.

**Comment by aik099** [comment]
Was the `urlstream_upload` option removed in future Plupload versions? I don't see it on http://www.plupload.com/docs/Options page. Is there any way to pass through cookies, when Flash runtime is used?
