### ISSUE TITLE
Standalone jQuery Plugin for custom setup

### ISSUE THREAD

**Issue by sislamoglu** [moxiecode/plupload#483]
Greetings,

I would definitely like a simple jQuery Plugin similiar to TinyMCE or SWFUpload's JQuery Plugin that, we can bind to an element, add binding events to element which binds it to plupload...

Yes, there is jquery and jqueryui versions with a GUI. But for those who would like custom setups , it would be lovely such as

$("#mydiv").plupload( { setting and such}).bind('init', function(e, ui) { do this });

The calling it like $('#mydiv').plupload('startUpload'); 

etc.

**Comment by jayarjo** [comment]
There's a `ready` event now (for quite some time), that is fired when uploader is initialized and - ready.

Also I should have mentioned probably this by now, but those widgets have started as examples of Core API (which is _the_ real - Plupload code base). So basically anyone can implement their own widget in any framework. That _was_ the intention.
