### ISSUE TITLE
Add files window not focused and disappears on Flash runtime (Fedora 15 64 bit, KDE, Firefox)

### ISSUE THREAD

**Issue by pdrosos** [moxiecode/plupload#534]
Hello,

I am currently using a laptop with Fedora 15 64 bit, KDE desktop, Firefox 11 and Flash plugin 11.2 r202. When I try the examples on your page, especially the flash upload example, when I press the Add files button, the browse files window opens, but in background and disappears in a couple of seconds. When I try the same with Chrome the browse files window opens, but in a couple of seconds the browser gives me a message "Unresponsive page". This doesn't happen with the HTML5 example.

I have the same issue with another library - jQuery uploadify.

Please, tell me is that a Flash plugin issue and how could it be fixed.

Thank you.

**Comment by jayarjo** [comment]
I was never able to reproduce this. Also we probably do not have any control over that. So, I will close this one.
