### ISSUE TITLE
[tutorial][docs] suggestions

### ISSUE THREAD

**Issue by djot** [moxiecode/plupload#552]
1. assuming you open the queue_widget.html (examples) in your browser, the form submit button is really hard to see. So make it more visible in the html page. Also write clearly in doc, tut, etc. that there is this button and that you have to click it even if the uploads look like being completely done already.
2. upload.php: $targetDir should be mentionend in doc/tut to be set to something, the user/developer expects
3. docs, tut is completely missing, what should be done, after (visually) all files have been uploaded.

3a. If $targetDir is set to (your) default, the files are not really visible to everyone that easy, because they "sit" in the tmp folder for uploads

3b. Ok, visually uploaded, you receive something to work with if you press the forms submit button (echos dump.php). Ok, now what to do with this? The part handling the POST values and moving the uploaded file to a directory in the project/htdocs path is totally missing.

3c. The examples are fine, look good. But there could be a little bit more "out of the box" for using plupload in a real project. 

This starts with a different file structure in the download file. Why most important files are located in "examples" directory? 

Why everyone hast to find out which files are needed, where to copy them instead of just placing them inside a "bin" or whatever folder?

It is better to have the demo html files link to sth like ../../js/... (e.g. <script type="text/javascript" src="../../js/plupload.js"></script>) instead of the other way round, a file "below" or in the plupload folder has should have to link to ./plubload/js/ or just ./js/

It took me 3 hours to get an example upload running, 
- meaning using the queue_widget (html5 runtime) without "HTTP error." (because url: 'upload.php') IS incorrect
- finding the uploaded file
- finding out (or more to say hacked it in upload.php, because documentation is missing) how to move the uploaded tmp file to a destination (not target) folder and rename it correctly.

Hope this helps others to get into plupload faster. (I can't really imagine how novice developers should get plupload to run in their project with the current download file and documentation given). Also I bet you lose a lot of users, because not everyone has the energy for hours to get plupload running (like stated from others in the forum also).

**Comment by jayarjo** [comment]
We have a Getting Started page here: https://github.com/moxiecode/plupload/wiki/Getting-Started
