### ISSUE TITLE
Cannot upload large files to Amazon S3 using Flash runtime

### ISSUE THREAD

**Issue by ReLrO** [moxiecode/plupload#555]
Hey. 
I have been trying to solve a problem for the last few days and came up empty. 
I configured the plupload to upload directly to Amazon S3 in my RoR environment. Everything worked well until I tried to upload larger files (>200mb). The upload just hangs after 30-50mb and I see no error or anything to indicate what's wrong. 
I tried switching to another solution and configured SWFUpload, but the same exact thing happens there as well. 

It happens both in my local development environment and in my production environment. 

I am using the latest flash ver. (11.2.232.235) on a mac. It happens both in Chrome and in FF. 

I really have no idea what to do anymore. I thought of using chunks, but it is currently not supported for direct S3 uploading.

Any ideas?

Thanks,
Ariel.

**Comment by jayarjo** [comment]
This might be relevant: https://github.com/moxiecode/plupload/issues/594#issuecomment-323582533.
