### ISSUE TITLE
Flash runtime + non-renewable session cookies

### ISSUE THREAD

**Issue by Artod** [moxiecode/plupload#564]
Algorithm:
1. Log in as User1.
2. Log out
3. Log in as User2.
4. Load the image using Flash runtime.

Result: Server receives User1's session cookies.

This happens in all browsers except IE.

**Comment by jayarjo** [comment]
Flash doesn't send cookies by default - it is a known issue. One  has to initialize Plupload with[ required_features](https://github.com/moxiecode/plupload/wiki/Required-Features) requesting capability to `send_browser_cookies` explicitly. Flash then will be switched to another mode which can send cookies (however it loses feedback progress, however that's whole separate story).
