### ISSUE TITLE
Enable resume upload

### ISSUE THREAD

**Issue by bh213** [moxiecode/plupload#57]
Not sure if this is even possible but if flash or silverlight can calculate md5 of chunk, you could send  md5 to server. Server would then check and respond if it already has this chunk and plupload would then skip upload the upload. 

For large file uploads that would be an amazing feature.

**Comment by foaly-nr1** [comment]
I agree with you, @DaveVdE. I published code examples and explanations in an article on Medium: https://medium.com/@fourlabsldn/error-proofing-plupload-1c64ab28bed0.

**Comment by savroff** [comment]
I have simple way to resumable uploading, just add 4 lines of javascript:
https://gist.github.com/savroff/1c8593fdcd3327748613

**Comment by taijisun** [comment]
+1

**Comment by ngjermundshaug** [comment]
+1

**Comment by hpvd** [comment]
+1 for implementing http://tus.io/ as suggest by @vangheem 
would be a perfect combination maybe on should open a new issue for this?

**Comment by DaveVdE** [comment]
TUS requires as much server side as it requires client side. I suppose if plupload supports the client side matters that I'd take the effort to implement it server side. But everyone has a different server story.

**Comment by hpvd** [comment]
hmmm... sorry I couldn't catch it. Maybe you can clearify it with just 2-3 more words?

**Comment by DaveVdE** [comment]
Well, TUS is a protocol that is different from the well established FORM POST uploads of today. If I want to use it in my product or project in ASP.NET, I'll have to implement the server side. Also, I would need some kind of tracking in a database to keep tabs on what's being uploaded, retention, that sort of thing. 

Everybody's story will be different. I don't think it's too complicated to implement the server side part with MVC or Web API, or even the new ASP.NET Core, so if plupload supports the client side, I might be persuaded to use it and implement the server side myself. Don't know if I'd do it openly though, perhaps a blog post should suffice to explain it.

**Comment by jayarjo** [comment]
As others have stated above basic upload resume is already possible, so pausing - by stopping uploader and resuming by manually setting loaded offset in the file object.

Better resuming of chunk uploads is implemented in Plupload 3.x, that is being prepared for a stable release at the moment. More details in: https://github.com/moxiecode/plupload/issues/1472.
