### ISSUE TITLE
File upload error in chrome v 21.0.1180.60

### ISSUE THREAD

**Issue by naveenmadhawa** [moxiecode/plupload#594]
File upload error in chrome v 21.0.1180.60 and Chrome 21.0.1180.75 please check this issue. I'm using Windows 7 and Windows server 2008.

**Comment by jayarjo** [comment]
Amazon specifically mentions `201 Created` problem with Flash and pprovidesa workaround: http://docs.aws.amazon.com/AmazonS3/latest/dev/HTTPPOSTFlash.html.

> Some versions of the Adobe Flash Player do not properly handle HTTP responses that have an empty body. To configure POST to return a response that does not have an empty body, set success_action_status to 201. Amazon S3 will then return an XML document with a 201 status code.
