### ISSUE TITLE
HTML5 input type=file has issues with triggered click.

### ISSUE THREAD

**Issue by stevemayhew** [moxiecode/plupload#605]
The crux of this issue is you cannot have the HTML5 upload button in a jQuery dialog, even if you make it contained by body (common offsetParent) and call plupload.refresh() to position it invisible 'overlaying' the dialog button.

Here is a fiddle that shows the issue, it works on Gecko (FF), but not on Safari 5.1 or Chrome 12 (WebKit).

http://jsfiddle.net/stevemayhew/y8CM2/3/embedded/result/

**Comment by jayarjo** [comment]
I guess not relevant anymore?
