### ISSUE TITLE
HTML5 file input accept breaks for mimetype `application/x-shockwave-flash`

### ISSUE THREAD

**Issue by lwc** [moxiecode/plupload#626]
Minimum proof here: http://jsfiddle.net/2m5dK/

Tested on Chrome 22, will not allow swf uploads.

Clearly this is a bug in chrome and not with plupload, but it seems to me that relying on the accept attribute could be a little premature - it straight up does nothing in FF15...

**Comment by jayarjo** [comment]
I guess it's not relevant anymore, especially because `accept` attribute now allows filtering directly by extensions (filtering by mime-types was absolute absurd anyway).
