### ISSUE TITLE
jQuery UI Widget doesn't work with Twitter Bootstrap Button JS

### ISSUE THREAD

**Issue by dv336699** [moxiecode/plupload#632]
If you use jQuery 1.8.2 + http://twitter.github.com/bootstrap/assets/js/bootstrap-button.js on your code when using jQuery UI Widget (https://github.com/moxiecode/plupload/blob/master/examples/jquery/jquery_ui_widget.html) the 'Start Upload' button doesn't work. Also the button style is changed.

Thanks

**Comment by Sweetog** [comment]
var btn = $.fn.button.noConflict();
 $.fn.btn = btn;

Worked for me, using Bootstrap v3.3.5
