### ISSUE TITLE
Unable to upload .jpeg file extensions

### ISSUE THREAD

**Issue by frantzs** [moxiecode/plupload#643]
We are having an issue uploading jpeg file types. I've already set to allow for them in all ares of the code, including in the cms we are using (joomla), but I still continue to get Error: -601, Message: File extension eror.

I'm not quite sure where else to check at this point. I can upload .jpeg files via the build in media manager of joomla so I at least know I've isolated it to be a plupload issue...

Thoughts?

**Comment by mfsi-santoshp** [comment]
I am facing the same issue.

**Comment by derhecht** [comment]
Same here, in FireFox only.

**Comment by jayarjo** [comment]
@derhecht which firefox version do you have, what platform?

**Comment by derhecht** [comment]
FF 48.0.1 but I solve the problem by hacking my local moxie.js where "filter_by_extension" ist tested. I just added FF >= 37 as found in newest moxie.js version.
