### ISSUE TITLE
Upload a big files some chunks fall

### ISSUE THREAD

**Issue by cokuna** [moxiecode/plupload#657]
Hi, 

we have a Problem, if user upload a file bigger than 150mb some parts missing, the file is not fully loaded. We have tested in two servers, only one of them has this trouble, although the servers settings are equal, except that access to the problematic server is via proxy.

I canceled upload and copied log infos
http://www.4shared.com/office/ugoXRm_D/log.html
Please look on lines 328 - 335 here is something strange. Also some values percent are conversely.
34% ... 35% ... 34% ... 38% ... 38% ...  39% ... 38% ... 42%  

my best regards

include: 
/webupload/js/plupload.full.js
/webupload/js/jquery.ui.plupload/jquery.ui.plupload.js

Settings:
runtimes: 'html5,flash,silverlight',
url: '/uploadtool2.php',
max_file_count: '1',
max_file_size: '10000mb',
chunk_size: '20mb',
flash_swf_url: '/webupload/js/plupload.flash.swf',
silverlight_xap_url: '/md/webupload/js/plupload.silverlight.xap',
drop_element: true,
dragdrop: true,
multipart: true,
multiple_queues: true,
multipart_params: {},
unique_names: false,

**Comment by srees** [comment]
jayarjo,

I'm modifying the Drupal 6 plupload module for an installation that requires chunking of multi-GB files. We recently had users complaining of large lost portions of files, so it started me down the path of what may have happened and how to fix it.

I've modified the module to work with the latest plupload library. However, I don't find any examples that address how to properly handle chunking on the server side. To be clear, https://github.com/moxiecode/plupload-handler-php does handle them, but does not appear to address the file offset that you speak of here. I also do not see any method to address retry of a failed chunk. How does the client side know the chunk failed and to resend it? And is there any sample code to address putting the chunk at the correct offset?

**Comment by cokuna** [comment]
Sehr geehrte Damen und Herren,

vielen Dank für Ihre Nachricht. Ich bin vom 5. Januar 2015 bis einschließlich 9. Januar 2015 nicht im Büro.
Ihre E-Mail wird nicht automatisch weitergeleitet.

Bitte wenden Sie sich in dringenden Fällen an  support@cokuna.com.

Mit freundlichen Grüßen

Lydia Metz
Programmierung, Grafikdesign,
Projektmanagement

cokuna communication
___________________

Könneritzstraße 29
01067 Dresden
Tel.:+49 (0) 3 51 - 89 21 93-35
Fax:+49 (0) 3 51 - 89 21 93-39
l.metz@cokuna.com
www.cokuna.com

Inhaber: Roman Thronicke
USt-IdNr.: DE 244071643
______________________


www.coconutbox.com
Kommunizieren. Verwalten. Einfach und Sicher.
