### ISSUE TITLE
plupload 2.0 - Queuing is blocking asynchronous I/O in node.js

### ISSUE THREAD

**Issue by ghost** [moxiecode/plupload#662]
I'm using node.js and it allows me to upload each file simultaneously, but plupload queuing waits for each file to be uploaded. I deleted the queuing code from plupload1 in my project, but plupload2 has the same problem. It should be fixed or at least you should provide a variable to control it.

**Comment by jayarjo** [comment]
Simultaneous upload of files and chunks is now possible in Plupload 3.x. I'm preparing bugfix release now.
