### ISSUE TITLE
File selection window can get hidden behind browser's window

### ISSUE THREAD

**Issue by roman02** [moxiecode/plupload#665]
I wouldn't have believed this had I not seen this myself. I was just observing a few minutes ago that after a user of my site opened the file open dialog box and (probably) clicked on the browser window or elsewhere, the dialog disappeared. When I minimized the browser's window, we saw the file open dialog sitting in the background. It was still functional and did its job.

She was running Firefox 17 on Windows XP. She had version 11.5.xxx of Flash player, which is new enough. I couldn't reproduce this in my Firefox 20a1 running on Windows 7. Maybe somebody else will be able to.

**Comment by jayarjo** [comment]
I don't think we can affect this in any way.
