### ISSUE TITLE
Thumbnails not being generated with Safari

### ISSUE THREAD

**Issue by gjb83** [moxiecode/plupload#671]
Environment:
- Mac OS X 10.8.2
- Safari 6.0.2
- Plupload 2.0a Beta
- HTML 5 runtime
- Using example `examples/jquery/jquery_ui_widget.html`

When adding a JPEG image to the queue, the client-side thumbnail is not generated. Instead, a spinner is displayed indefinitely:

![Safari](https://f.cloud.github.com/assets/402955/33975/23da613e-50e7-11e2-8ee6-8df88d1ae573.png)

For comparison, I ran the same test using Firefox 17.0.1, and the thumbnail displayed correctly:

![Firefox](https://f.cloud.github.com/assets/402955/33977/2e2d8ce2-50e7-11e2-9202-f0cb3a500c69.png)

I have tested this with a number of different JPEG files, including some smaller ones (~500KB), but cannot get this to work under Safari.

**Comment by Pawnerd** [comment]
Is there any fix yet?
