### ISSUE TITLE
Plupload 2.0 - report of problem with RIM BlackBerry PlayBook tablet

### ISSUE THREAD

**Issue by aliwatters** [moxiecode/plupload#673]
Sorry for the vague nature of this report - I do not have a  RIM BlackBerry PlayBook tablet to test with - hopefully someone does to confirm or provide more details.

Got an error report from a beta user.

Using the jquery  queue widget - "Start Upload button after selecting one or more pictures simply sits there with 0% progress" - working in other browers (firefox chrome etc)

resize option is set on.

User agent reported as;

Mozilla/5.0 (PlayBook; U; RIM Tablet OS 2.1.0; en-US) AppleWebKit/536.2+ (KHTML, like Gecko) Version/7.2.1.0 Safari/536.2+

**Comment by jayarjo** [comment]
Still do not have access to that platform to do anything meaningful to it.
