### ISSUE TITLE
Selecting muliple files in file browser triggers Error (correct invalid) as well as FilesAdded file

### ISSUE THREAD

**Issue by x00** [moxiecode/plupload#674]
Expected behaviour: For invalid file error to show without FilesAdded files containing the invalid file. 

Why? Consistency,  becuase it doesn't trigger when selecting individual invalid files.

Workaround: filter files param. 

Steps to repeat:
- Custom Upload Script
- Select in filebrowser multiple valid files the last being invalid. 

You should see the file error plus the FilesAdded line. 

Linux Mint 13 Maya
FireFox 16.0.2

Perhaps this is debatable, but filtering again you are almost  reinventing the wheel. 

it doesn't try to upload but it is a bit messy.

**Comment by jayarjo** [comment]
In Plupload 2.x and up files that do not meet requirements are filtered out, be it single file or multiple.
