### ISSUE TITLE
Multipart without urlparams

### ISSUE THREAD

**Issue by altitude-vbox** [moxiecode/plupload#68]
Greetings,

I was wondering if it's possible to disable urlparams when uploading using multiparts. Here is a fork with this issue solved: http://github.com/mentat/plupload/commit/fbd34f28750127a2d7150cfbb425e9e6b3b0a1b7

But i belive the best aproach is to put a flag to enable and disable urlparms.

Best regards.

**Comment by jayarjo** [comment]
In the recent release we now have a similar property - `send_file_name` which by default is set to true (for backward compatibility). One can set it to false to disable sending of additional params with the request.
