### ISSUE TITLE
v1.5.4 ,flash runtime. show "Error: -700,Message:Image error "

### ISSUE THREAD

**Issue by syncml** [moxiecode/plupload#686]
![S73F5187](https://f.cloud.github.com/assets/2890035/77181/738e8484-611e-11e2-90d7-b224d4aa9eb0.JPG)

Hi

When i upload this image,

If the Uploader setting contain "   resize : {width : 800,height : 600, quality : 90}",  ,  "Error: -700,Message:Image error " was appeared. But if I removed the resize setting,everything was ok.

it's a bug??

btw, photoshop can't open this image.

Contact if you have any query further.

Thanks

**Comment by jayarjo** [comment]
Seems like  `.bmp` image. Plupload currently considers only `.png` and `.jpg` as being images, the rest are just files.
