### ISSUE TITLE
IE + Flash: Don't return HTTP204!

### ISSUE THREAD

**Issue by DaveVdE** [moxiecode/plupload#688]
I was having an issue with using the Flash runtime in IE9.

When doing uploading in chunks, I return HTTP 204 from the server to indicate that the request was fulfilled, but no resource was created yet (because it's only a chunk). I return 201 on completion of the last chunk to relay the URL of the new resource (I'm into REST and all that). 

That worked fine with the HTML5 runtime and the Flash runtime in FF, Chrome, Safari and so forth, but it didn't work in IE8 or IE9 due to some obscure error message "Stream Error #3032", which led me to frustration and back.

I found this article that goes somewhat in the same direction, blaming it on cache control:
http://faindu.wordpress.com/2008/04/18/ie7-ssl-xml-flex-error-2032-stream-error/

but that wasn't the issue. I tested it with returning HTTP 200's (returning something trivial) and now all of a sudden it works.

So if you have this same problem, look no further.

**Comment by jayarjo** [comment]
I didn't know at the time, but as turned out Flash can only return 200 and 404. The rest is beyond it.
