### ISSUE TITLE
Feature request. Would be nice to be able to limit the size of uploaded file AFTER resize.

### ISSUE THREAD

**Issue by ovkhasch** [moxiecode/plupload#717]
Resize functionality can be used to downscale the images before upload. But as I understand, not all image formats can be resized (and also there's a max dimension limitation). It would be nice to be able to control the size of uploaded images as it is can be done with max_file_size but check the size after resizing an image (currently it is done befor resizing). In this case it would be possible to upload large images that were resized to small ones but don't upload large images that cannot be resized.

**Comment by jayarjo** [comment]
Relevant: https://github.com/moxiecode/plupload/issues/547
