### ISSUE TITLE
Not able to detect if the file can be resized or displayed as a thumbnail.

### ISSUE THREAD

**Issue by ovkhasch** [moxiecode/plupload#719]
I use plupload with a custom UI. When html5 or flash runtime is initialized it is possible to display a thumbnail. However, for ie9 with html4 the code which loads image from file.getSource() fails with a javascript error (index out of range) somewhere in the onerror function (I commented out my own onerror handlers). I wanted to check if the runtime is html4 an don't try to load a thumbnail in this case and display a file name instead but didn't find any API for this. Another concern is that not all images can be resized - as I understand only JPG and PNG. This means that again, I cannot display a thumbnail for GIF or BMP. It would be nice to be able to check if the given file can be resized or not.

**Comment by jayarjo** [comment]
We do follow existing APIs there, that do not have detailed error messages. I'm not sure why but it probably won't change. :/
