### ISSUE TITLE
Does plupload support the new Clipboard API and events

### ISSUE THREAD

**Issue by cherian** [moxiecode/plupload#734]
Chrome has implemented the [event.clipboardData.items](http://dev.w3.org/2006/webapi/clipops/) and [it’s an incredible time saver](http://stackoverflow.com/a/6338207/22039).  
Does plupload support this?

**Comment by WeweTom** [comment]
+1

**Comment by jayarjo** [comment]
https://github.com/moxiecode/plupload/issues/1092
