### ISSUE TITLE
Plupload jquery library not working in IE10

### ISSUE THREAD

**Issue by Jugsal** [moxiecode/plupload#758]
I have a website where user's can upload their images. I am struck at IE10 not bringing file upload folder. I am using Plupload jQuery files with latest version(v1.5.6). It works very well with Firefox, Opera, Chrome and IE9 but not IE10.

Clicking on 'Upload' button does nothing but i can see new Div and input control created as

``` javascript
<div id="p17nd09rko1s8c1vaf1a401nkm1ph00_html5_container" class="plupload html5" style="position: absolute; background: none repeat scroll 0% 0% transparent; width: 0px; height: 0px; overflow: hidden; z-index: -1; opacity: 0; top: 0px; left: 0px;">
<input id="p17nd09rko1s8c1vaf1a401nkm1ph00_html5" type="file" multiple="multiple" accept="image/jpeg,image/gif,image/png" style="font-size: 999px; float:right">
</div>
```

I think it is unable to hook with 'browse_button' value in var uploader = new plupload.Uploader({.. })

Another thing I see is CSS generated is different in IE as compared to Mozilla.

My javascript

``` javascript
var uploader = new plupload.Uploader({
            runtimes : 'gears,html5,flash,silverlight,browserplus',
            browse_button : 'pickfiles',
            container : 'container',
            chunk_size: '1mb',
            unique_names: true,
            max_file_size : '5mb',
            max_file_count : 1,
            multi_selection: true,
            url: '<!-- my url -->',
            filters: [{ title: "Image files", extensions: 'jpg'}],
            flash_swf_url: '@Url.Content( "~/Scripts/plup/plupload.flash.swf" )',
            silverlight_xap_url: '@Url.Content("~/Scripts/plup/plupload.silverlight.xap")'
        });
```

Hope someone please help me with this?

**Comment by Singh29** [comment]
I tried but drag and drop of photos not working in IE 10,11 and edge..

Any suggestions how to fix it..?
