### ISSUE TITLE
alert in uploader event crashes ipad-browser (workaround included)

### ISSUE THREAD

**Issue by MatsSvensson** [moxiecode/plupload#791]
This locks up the standard-browser on ipad (4), with plupload 1.5.7:
```javascript
 uploader.bind('FilesAdded', function (up, files) {
    alert('test');
  });
```
You have to go to the start-screen and kill it.
alert on other places outside plupload works fine.
I havent seen this on any other systems (haven't tested on other ipad/iphone).

This seems to fix it:
```javascript
  uploader.bind('FilesAdded', function (up, files) {
    setTimeout(function () {
      alert('test');
    }, 0);
  });
```

**Comment by jayarjo** [comment]
`alert()` is blocking and primitive. Better print it the message into a `pre` container or use remote debugging.
