### ISSUE TITLE
HTML5 File Select not firering in Firefox 22

### ISSUE THREAD

**Issue by srissel** [moxiecode/plupload#828]
Hello,

this is a rather important issue, please help.

I just experienced a strange problem:
We are developing an ExtJs-based Windows-Explorer-like web application which contains plupload 1.5.x.

Recently we upgraded to Firefox 22. Now we are facing the problem, that HTML5 file upload dialog is not opening anymore.
If you roll back to Firefox 21, everything is fine again.

Could you please provide any help?

Thanks in advance,
Sascha.

**Comment by jayarjo** [comment]
Will close this for now.
