### ISSUE TITLE
javascript error plupload not defined plupload.gears.min.js

### ISSUE THREAD

**Issue by soporte1122** [moxiecode/plupload#83]
We get that error when the page containing the upload control loads...in (IE8, Firefox 3.6, Opera 10.60...we havent tested others but suspect its the same in all)
In opera the error is detailed as:  
Uncaught exception: ReferenceError: Undefined variable: plupload
Error thrown at line 1, column 0 in http://websitex/plupload/js/plupload.gears.min.js

Removed gears from the list of runtimes with no differences...anyone knows what could be wrong?
Thanks in advance

**Comment by lakeydesigner** [comment]
err i dont see a solution, is a forum for the benefit of everybody, im having the same problem and would like some details about what i have to do to resolve this please

**Comment by jayarjo** [comment]
@lakeydesigner this thread is not actual anymore. It's about deprecated 1.x version. What exactly is your problem?

**Comment by lakeydesigner** [comment]
well i have a jomsocial website and the upload image feature has stopped working, 

SyntaxError: expected expression, got <!doctype html>
jquery-....3.0.js (line 1) NetworkError: A network error occurred.

ReferenceError: plupload is not defined
....gears){google.gears={factory:a}}})();(function(e,b,c,d){var f={};function a(h,j...

ReferenceError: plupload is not defined
(function(a){a.runtimes.BrowserPlus=a.addRuntime("browserplus",{getFeatures:func...

ReferenceError: plupload is not defined
(function(d,a,b,c){function e(f){return a.getElementById(f)}b.runtimes.Html4=b.a...

ReferenceError: plupload is not defined
....gears){google.gears={factory:a}}})();(function(e,b,c,d){var f={};function a(h,j...	

this is the error im getting and i cant see the upload button

**Comment by jayarjo** [comment]
First error seems to be a `NetworkError`, that is not related to Plupload. I'd suggest that that you resolve it first. The rest might just go away after you do so.

**Comment by lakeydesigner** [comment]
Ok thanks very much for you help

Best Wishes
Michael Lake
