### ISSUE TITLE
new very simple feature request: single file instant upload (programmatic)

### ISSUE THREAD

**Issue by pilavdzic** [moxiecode/plupload#832]
I noticed in your FAQ you said: Can I trigger file dialog programmatically?

It depends on the runtime, but the short answer is - no, since it is not possible to achieve consistent behavior across the runtimes

However, many people (like me) have a need to use plupload for all it's other benefits, ajax upload with progress bar, etc and only use it with HTML5, I don't use plugins like flash or silverlight anyway. 

Would it be a lot of trouble to add this feature to have a function that, for html5 only, allows me to click a simple "Upload" button, allows me to select a single file, then as soon as it is selected begins upload immediately?

In my scenario users want to just click upload, select the file, and watch my progress bar upload it into my app and then view all the files they uploaded before, so I don't need plupload to do much, only to allow me to actually do the most basic thing - upload a single file!

All this file queue multiple file stuff just gets in the way - in my app they have to tag each file with various things, so I only want to allow them to select one file at a time.

I am trying to hack something like this in but it would really be a lot more user friendly if you had the option to programatically trigger the upload dialog and then the upload itself.

I know it is possible to do this because plupload is doing it internally - can you just expose that API please?

Would be much appreciated.

Thanks!

**Comment by jayarjo** [comment]
By programmatic triggering we meant triggering of file dialog. If user actually clicks a button, of course browse dialog will appear. In all runtimes.
