### ISSUE TITLE
bytesPerSec accuracy problems

### ISSUE THREAD

**Issue by kntem** [moxiecode/plupload#837]
I try to show the current upload speed using the `uploader.total.bytesPerSec`
but when there is already one file uploaded, the number it returns is much bigger than the actual speed .
I tried the `uploader.total.reset()` and it doesn't work.
It works right (with realistic values according to the time it takes to uploade the file) 
only when I set the `loaded` of all files to 0

**Comment by jayarjo** [comment]
Related: https://github.com/moxiecode/plupload/issues/837
