### ISSUE TITLE
Uploader.total.uploaded value differs between browsers

### ISSUE THREAD

**Issue by soporte1122** [moxiecode/plupload#84]
We have the following function to do a postback after it uploads all the files:

```javascript
function attachCallbacks(Uploader) {
        Uploader.bind('FileUploaded', function (Up, File, Response) {
            alert('epatu' + Uploader.total.uploaded + 'lenght:' + Uploader.files.length);
            if (Uploader.total.uploaded == Uploader.files.length) {
                alert('Archivos subidos correctamente. Pulse \'Refrescar\' si no los ve en la lista');
                __doPostBack('lbRefrescar', '');
            }
        });
```
The problem is that in IE8 and Opera10.60 the Uploader.total.uploaded starts at 0 and in Firefox 3.6 it starts at 1. (We havent tested other browsers but suspect could happen the same)

**Comment by jayarjo** [comment]
Doesn't seem to be a problem with Plupload 2.x. Try here: http://play.plupload.com/s__J_/2.
