### ISSUE TITLE
Can't upload many files - HTML5 / Google Chrome / Windows

### ISSUE THREAD

**Issue by geoffyoungs** [moxiecode/plupload#86]
(This is really a bug in Windows/Google Chrome.)

When browsing for files using the HTML5 upload in Google Chrome on Windows and the length of the contents of the file names field exceeds ~260 characters, Google Chrome reports that no files were selected.

This only affects the file browse dialog - it doesn't affect drag & drop.

It seems to be related to this:
http://code.google.com/p/chromium/issues/detail?id=44068
http://msdn.microsoft.com/en-us/library/aa365247.aspx#maxpath

**Comment by jayarjo** [comment]
Even if it's still an issue (which it shouldn't be) I do not think we can do anything about it.
