### ISSUE TITLE
Bug Report: 2.0beta - Corrupted File with Flash Runtime and 'resumed' uploads.

### ISSUE THREAD

**Issue by filmo** [moxiecode/plupload#866]
Using plupload_2_0_0beta.1308111349 and the UI widget.

I upload a test file into the UI widget. The file is 10mb and chunking size is set to 1mb.

I hit the 'start' button, then 'stop', then 'start' again. I do this several times during the upload.

With HTML5 and Silverlight the file arrives safely and the MD5 hashes match.

If I do the same thing with the Flash runtime, I end up with a file on the server that does not match. The file on the server is larger. (data is appended to the file more than once.) For example with a 10 MB local file, the server file might end up being 12MB (and is obviously corrupted.)

Here's a snippet of my uploader code. 

``` javascript
    $("#uploader").plupload({
        // General settings
        runtimes : 'html5,flash,silverlight',
        url : 'plup_upload.php',
        max_file_size : '1000mb',
        max_file_count: 100, // user can add no more then 20 files at a time
        chunk_size : '1mb',
        unique_names : false,
        multiple_queues : true,
        // this used to be 'access_binary'
        required_features: 'chunks', // forces Safari 5.x to dump HTML5 and move to Flash
```

**Comment by jayarjo** [comment]
Related: https://github.com/moxiecode/plupload/issues/57
