### ISSUE TITLE
Progress bar not working on Windows 8

### ISSUE THREAD

**Issue by jgrossi** [moxiecode/plupload#913]
Hi all!

I tested in Windows 7, Windows XP, Windows 8, Mac, Linux, etc. My app actually uses html5 first and then flash. No one can display de progress correcly. All browsers in Windows 8 the progress goes from 0% to 100% fast, but the file is still uploading.

Any suggestion?

**Comment by Cloetn** [comment]
@romainjanvier 
Wow... Insane. I had the same problem with a Forticlient webdefender. Thanks for the hint!

**Comment by jgrossi** [comment]
@romainjanvier I think this is not a `plupload` problem, but some antivirus are blocking that :-(
