### ISSUE TITLE
html4 runtime in IE10 IE8-9 browser mode doesn't open file dialog.

### ISSUE THREAD

**Issue by AlmostDan** [moxiecode/plupload#940]
The setup is simply the custom example with runtimes changed to html4 only. 
It works in IE10, but not in the IE8 or IE9 mode - the select files button doesn't do anything. No js error.
The original runtimes setup works in all versions. In IE8 it loads correctly into the flash runtime, but what is also strange is that it reports the runtime to be html5.

**Comment by jayarjo** [comment]
Currently it seems operational. But just in case if you or anyone else would need to file a report and provide a fiddle that works all the way down to IE6, we have our own playground now: http://play.plupload.com.
