### ISSUE TITLE
With IE+Flash plUpload does not fire progress events

### ISSUE THREAD

**Issue by alsh905** [moxiecode/plupload#949]
1) Set runtimes to 'flash'
2) Try to upload large file in multiple chunks
3) The upload occurs fine, however the progress report is not updated, coming from 0 to 100% in a single step

Reproducible with IE8-IE11.

**Comment by jayarjo** [comment]
You should not enforce chunking for Flash environment, since it does exactly opposite. Flash works best without chunking.

Check our writeup about [When to Use Chunking and When Not](https://github.com/moxiecode/plupload/wiki/Frequently-Asked-Questions#when-to-use-chunking-and-when-not).
