### ISSUE TITLE
"TypeError: o is null" when upgrading from 1.5.7 to 2.1.0

### ISSUE THREAD

**Issue by v1nc3n4** [moxiecode/plupload#979]
Hi,

I'm facing an issue just upgrading from 1.5.7 to 2.1.0. I found this post http://www.plupload.com/punbb/viewtopic.php?id=3960 about how to upgrade, and I followed the few steps, but it's not working on the website I'm working on. After loading the page, here's the console output in FF/Firebug:

```
TypeError: o is null
[...]/plupload-2.1.0/plupload.full.min.js
Line 14
```

Then, when I try to upload a file, nothing happens, as it seems the library did not setup correctly.

Are there additional steps for upgrade?
Thanks in advance for your help.

BR.

**Comment by bhawani007** [comment]
Thank you sir...
its work....
issue is that container id not found...
i resolve ... thank you sir....
